// @generated by notes/_gen_nemeth_from_braille_tests.py from tests/braille/Nemeth/chemistry.rs
// Do not edit by hand unless updating the generator.
#![allow(non_snake_case)]

use crate::common::*;
use anyhow::Result;

#[test]
fn bond_2_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>H</mi><mo>:</mo><mi>Be</mi><mo>:</mo><mi>H</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠓⠸⠒⠻⠠⠃⠑⠸⠒⠻⠠⠓")?;
    Ok(())
}

#[test]
fn bond_2_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msub><mi>H</mi><mn>2</mn></msub><mi>C</mi><mo>=</mo><mi>C</mi><msub><mi>H</mi><mn>2</mn></msub></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠓⠆⠠⠉⠸⠶⠻⠠⠉⠠⠓⠆")?;
    Ok(())
}

#[test]
fn bond_2_2_mhchem() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msub><mi>H</mi><mn>2</mn></msub><mi>C</mi><mo>=</mo><mi>C</mi><msub><mi>H</mi><mn>2</mn></msub></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠓⠆⠠⠉⠸⠶⠻⠠⠉⠠⠓⠆")?;
    Ok(())
}

#[test]
fn bond_2_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>H</mi><mo>:</mo><mi>C</mi><mo>&#x2261;</mo><mi>C</mi><mo>:</mo><mi>H</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠓⠸⠒⠻⠠⠉⠸⠿⠻⠠⠉⠸⠒⠻⠠⠓")?;
    Ok(())
}

#[test]
fn bond_2_5() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>Fe</mi><mo>+</mo><msub><mi>Cl</mi><mn>2</mn></msub><mo>=</mo><mi>Fe</mi><msub><mi>Cl</mi><mn>3</mn></msub></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠋⠑⠬⠠⠉⠇⠆⠀⠨⠅⠀⠠⠋⠑⠠⠉⠇⠒")?;
    Ok(())
}

#[test]
fn arrow_bond_sec_2_2_2_c() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>2</mn><mi>Na</mi><mo>+</mo><msub><mi>Cl</mi><mn>2</mn></msub><mo>&#x2192;</mo><mn>2</mn><mi>Na</mi><mi>Cl</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠆⠠⠝⠁⠬⠠⠉⠇⠆⠀⠫⠕⠀⠼⠆⠠⠝⠁⠠⠉⠇")?;
    Ok(())
}

#[test]
fn arrow_bond_sec_2_2_2_d() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>R</mi><mi>N</mi><msub><mi>H</mi><mn>2</mn></msub><mo>+</mo><mi>R</mi><mi>X</mi><mo>&#x2192;</mo><msub><mi>R</mi><mn>2</mn></msub><msup><mrow><mi>N</mi><msub><mi>H</mi><mn>2</mn></msub></mrow><mo>+</mo></msup><msup><mi>X</mi><mo>-</mo></msup></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠗⠠⠝⠠⠓⠆⠬⠠⠗⠠⠭⠀⠫⠕⠀⠠⠗⠆⠠⠝⠠⠓⠆⠐⠘⠬⠐⠠⠭⠘⠤")?;
    Ok(())
}

#[test]
fn arrow_bond_sec_2_2_2_d_mhchem() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>R</mi><mi>N</mi><msub><mi>H</mi><mn>2</mn></msub><mo>+</mo><mi>R</mi><mi>X</mi><mo>&#x2192;</mo><msub><mi>R</mi><mn>2</mn></msub><msup><mrow><mi>N</mi><msub><mi>H</mi><mn>2</mn></msub></mrow><mo>+</mo></msup><msup><mi>X</mi><mo>-</mo></msup></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠗⠠⠝⠠⠓⠆⠬⠠⠗⠠⠭⠀⠫⠕⠀⠠⠗⠆⠠⠝⠠⠓⠆⠐⠘⠬⠐⠠⠭⠘⠤")?;
    Ok(())
}

#[test]
fn lewis_2_20() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>H</mi><msub><mi>O</mi><mn>2</mn></msub><mo>+</mo><mi>N</mi><mi>O</mi><mo>&#x2192;</mo><mi>N</mi><msub><mi>O</mi><mn>2</mn></msub><mo>+</mo><mo>&#xB7;</mo><mi>O</mi><mi>H</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠓⠠⠕⠆⠬⠠⠝⠠⠕⠀⠫⠕⠀⠠⠝⠠⠕⠆⠬⠡⠠⠕⠠⠓")?;
    Ok(())
}

#[test]
fn lewis_2_21() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>R</mi><mo>&#xB7;</mo><mo>+</mo><mo>&#xB7;</mo><mi>C</mi><msub><mi>H</mi><mn>3</mn></msub><mo>&#x2192;</mo><mi>R</mi><mi>C</mi><msub><mi>H</mi><mn>3</mn></msub></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠗⠡⠬⠡⠠⠉⠠⠓⠒⠀⠫⠕⠀⠠⠗⠠⠉⠠⠓⠒")?;
    Ok(())
}

#[test]
fn lewis_2_22() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mrow><mo>[</mo><mrow><mi>C</mi><msub><mi>H</mi><mn>3</mn></msub></mrow><mo>]</mo></mrow><mo>&#xB7;</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠈⠷⠠⠉⠠⠓⠒⠈⠾⠡")?;
    Ok(())
}

#[test]
fn dots_2_37_a() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mfrac><mrow><mi>N</mi><mi>&#x3B8;</mi><mi>N</mi><mfrac><mtext>&#xFFFD;</mtext><mtext>&#xFFFD;</mtext></mfrac></mrow><mtext>&#xFFFD;</mtext></mfrac></math>";
    test_from_braille("Nemeth", expr, "⠹⠠⠝⠨⠹⠠⠝⠹")?;
    Ok(())
}

#[test]
fn dots_2_37_b() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>H</mi><mfrac><mrow><mi>C</mi><mi>&#x3B8;</mi><mi>C</mi><mfrac><mi>H</mi><mtext>&#xFFFD;</mtext></mfrac></mrow><mtext>&#xFFFD;</mtext></mfrac></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠓⠹⠠⠉⠨⠹⠠⠉⠹⠠⠓")?;
    Ok(())
}

#[test]
fn yields_3_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>C</mi><msub><mi>H</mi><mn>4</mn></msub><mrow><mo>(</mo><mi>g</mi><mo>)</mo></mrow><mo>+</mo><mn>2</mn><msub><mi>O</mi><mn>2</mn></msub><mrow><mo>(</mo><mi>g</mi><mo>)</mo></mrow><mo>&#x2192;</mo><mi>C</mi><msub><mi>O</mi><mn>2</mn></msub><mrow><mo>(</mo><mi>g</mi><mo>)</mo></mrow><mo>+</mo><mn>2</mn><msub><mi>H</mi><mn>2</mn></msub><mi>O</mi><mrow><mo>(</mo><mi>g</mi><mo>)</mo></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠉⠠⠓⠲⠷⠛⠾⠬⠆⠠⠕⠆⠷⠛⠾⠀⠫⠕⠀⠠⠉⠠⠕⠆⠷⠛⠾⠬⠆⠠⠓⠆⠠⠕⠷⠛⠾")?;
    Ok(())
}

#[test]
fn reverse_3_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msub><mi>N</mi><mn>2</mn></msub><mo>+</mo><mn>3</mn><msub><mi>H</mi><mn>2</mn></msub><mo>&#xA0;</mo><mo>&#x21E0;</mo><mo>&#xA0;</mo><mn>2</mn><mi>N</mi><msub><mi>H</mi><mn>3</mn></msub></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠝⠆⠬⠒⠠⠓⠆⠀⠫⠪⠒⠒⠀⠼⠆⠠⠝⠠⠓⠒")?;
    Ok(())
}

#[test]
fn reaction_arrow_3_9() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msub><mi>H</mi><mn>2</mn></msub><mrow><mo>(</mo><mi>g</mi><mo>)</mo></mrow><mo>+</mo><msub><mi>I</mi><mn>2</mn></msub><mrow><mo>(</mo><mi>g</mi><mo>)</mo></mrow><mo>&#xA0;</mo><mo>&#x1F8D1;</mo><mo>&#xA0;</mo><mn>2</mn><mi>H</mi><mi>I</mi><mrow><mo>(</mo><mi>g</mi><mo>)</mo></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠓⠆⠷⠛⠾⠬⠠⠊⠆⠷⠛⠾⠀⠫⠒⠕⠫⠪⠒⠀⠼⠆⠠⠓⠠⠊⠷⠛⠾")?;
    Ok(())
}

#[test]
fn reaction_arrow_3_13() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msub><mi>H</mi><mn>3</mn></msub><mi>C</mi><mo>:</mo><mi>C</mi><mo>&#x2261;</mo><msup><mi>C</mi><mo>-</mo></msup><msup><mi>Na</mi><mo>+</mo></msup><mo>+</mo><mi>N</mi><msub><mi>H</mi><mn>3</mn></msub><mo>&#xA0;</mo><mo>&#x2943;</mo><mo>&#xA0;</mo><msub><mi>H</mi><mn>3</mn></msub><mi>C</mi><mo>:</mo><mi>C</mi><mo>&#x2261;</mo><mi>C</mi><mo>:</mo><mi>H</mi><mo>+</mo><msup><mi>Na</mi><mo>+</mo></msup><msup><mrow><mi>N</mi><msub><mi>H</mi><mn>2</mn></msub></mrow><mo>-</mo></msup></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠓⠒⠠⠉⠸⠒⠻⠠⠉⠸⠿⠻⠠⠉⠘⠤⠐⠠⠝⠁⠘⠬⠐⠬⠠⠝⠠⠓⠒⠀⠫⠪⠒⠒⠫⠒⠕⠀⠠⠓⠒⠠⠉⠸⠒⠻⠠⠉⠸⠿⠻⠠⠉⠸⠒⠻⠠⠓⠬⠠⠝⠁⠘⠬⠐⠠⠝⠠⠓⠆⠐⠘⠤")?;
    Ok(())
}

#[test]
fn reaction_arrow_3_14_a() -> Result<()> {
    let expr = "<math intent=':chemical-equation'><mi mathvariant=\"normal\">R</mi><mo>⥂</mo><mi mathvariant=\"normal\">P</mi></math>";
    test_from_braille("Nemeth", expr, "⠠⠗⠀⠫⠒⠒⠕⠫⠪⠒⠀⠠⠏")?;
    Ok(())
}

#[test]
fn reaction_arrow_3_14_b() -> Result<()> {
    let expr = "<math intent=':chemical-equation'><mi mathvariant=\"normal\">R</mi><mo>⥄</mo><mi mathvariant=\"normal\">P</mi></math>";
    test_from_braille("Nemeth", expr, "⠠⠗⠀⠫⠒⠕⠫⠪⠒⠒⠀⠠⠏")?;
    Ok(())
}

#[test]
fn arrow_3_36() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>2</mn><mi>Al</mi><mo>+</mo><mn>2</mn><mi>Na</mi><mi>O</mi><mi>H</mi><mo>+</mo><mn>2</mn><msub><mi>H</mi><mn>2</mn></msub><mi>O</mi><mo>&#x2192;</mo><msub><mi>Na</mi><mn>2</mn></msub><msub><mi>Al</mi><mn>2</mn></msub><msub><mi>O</mi><mn>4</mn></msub><mo>+</mo><mn>3</mn><msub><mi>H</mi><mn>2</mn></msub><mo>&#x2191;</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠆⠠⠁⠇⠬⠆⠠⠝⠁⠠⠕⠠⠓⠬⠆⠠⠓⠆⠠⠕⠀⠫⠕⠀⠠⠝⠁⠆⠠⠁⠇⠆⠠⠕⠲⠬⠒⠠⠓⠆⠫⠣")?;
    Ok(())
}

#[test]
fn arrow_3_37() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>Ca</mi><msub><mrow><mo>(</mo><mrow><mi>H</mi><mi>C</mi><msub><mi>O</mi><mn>3</mn></msub></mrow><mo>)</mo></mrow><mn>2</mn></msub><mo>+</mo><mi>Ca</mi><msub><mrow><mo>(</mo><mrow><mi>O</mi><mi>H</mi></mrow><mo>)</mo></mrow><mn>2</mn></msub><mo>&#x2192;</mo><mn>2</mn><mi>Ca</mi><mi>C</mi><msub><mi>O</mi><mn>3</mn></msub><mo>&#x2193;</mo><mo>&#xA0;</mo><mo>+</mo><mn>2</mn><msub><mi>H</mi><mn>2</mn></msub><mi>O</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠉⠁⠷⠠⠓⠠⠉⠠⠕⠒⠾⠰⠆⠐⠬⠠⠉⠁⠷⠠⠕⠠⠓⠾⠰⠆⠀⠫⠕⠀⠼⠆⠠⠉⠁⠠⠉⠠⠕⠒⠫⠩⠀⠬⠆⠠⠓⠆⠠⠕")?;
    Ok(())
}

#[test]
fn dot_4_5() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msub><mi>K</mi><mn>1</mn></msub><mrow><mo>[</mo><mrow><mi>P</mi><msub><mi>Cl</mi><mn>5</mn></msub></mrow><mo>]</mo></mrow><mo>=</mo><msub><mi>K</mi><mn>2</mn></msub><mrow><mo>[</mo><mrow><mi>P</mi><msub><mi>Cl</mi><mn>3</mn></msub></mrow><mo>]</mo></mrow><mo>&#xB7;</mo><mrow><mo>[</mo><msub><mi>Cl</mi><mn>2</mn></msub><mo>]</mo></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠅⠂⠈⠷⠠⠏⠠⠉⠇⠢⠈⠾⠀⠨⠅⠀⠠⠅⠆⠈⠷⠠⠏⠠⠉⠇⠒⠈⠾⠡⠈⠷⠠⠉⠇⠆⠈⠾")?;
    Ok(())
}

#[test]
fn charge_5_1_c() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>2</mn><mi>Al</mi><mo>&#x2192;</mo><mn>2</mn><msup><mi>Al</mi><mrow><mn>3</mn><mo>+</mo></mrow></msup><mo>+</mo><mn>6</mn><msup><mi>e</mi><mo>-</mo></msup></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠆⠠⠁⠇⠀⠫⠕⠀⠼⠆⠠⠁⠇⠘⠒⠬⠐⠬⠖⠑⠘⠤")?;
    Ok(())
}

#[test]
fn charge_5_3_a() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><mrow><mi>H</mi><mi>P</mi><msub><mi>O</mi><mn>4</mn></msub></mrow><mrow><mn>2</mn><mo>-</mo></mrow></msup></math>";
    test_from_braille("Nemeth", expr, "⠠⠓⠠⠏⠠⠕⠲⠐⠘⠆⠤")?;
    Ok(())
}

#[test]
fn charge_5_3_b() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><mmultiscripts><mi>He</mi><mprescripts/><mn>2</mn><mn>4</mn></mmultiscripts><mrow><mn>2</mn><mo>+</mo></mrow></msup></math>";
    test_from_braille("Nemeth", expr, "⠰⠆⠘⠲⠐⠠⠓⠑⠘⠆⠬")?;
    Ok(())
}

#[test]
fn simultaneious_scripts_5_8_b() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><mrow><mi>S</mi><msub><mi>O</mi><mn>4</mn></msub></mrow><mrow><mn>2</mn><mo>-</mo></mrow></msup></math>";
    test_from_braille("Nemeth", expr, "⠠⠎⠠⠕⠲⠘⠆⠤")?;
    Ok(())
}

#[test]
fn staggered_scripts_5_9_a() -> Result<()> {
    let expr = "<math><mn>5</mn><msub><mi mathvariant=\"normal\">C</mi><mn>2</mn></msub> <msup><msub><mi mathvariant=\"normal\">O</mi><mn>4</mn></msub><mrow><mn>2</mn><mo>-</mo></mrow></msup> <mo>(</mo><mi>a</mi><mi>q</mi><mo>)</mo></math>";
    test_from_braille("Nemeth", expr, "⠼⠢⠠⠉⠆⠠⠕⠲⠐⠘⠆⠤⠐⠷⠁⠟⠾")?;
    Ok(())
}

#[test]
fn staggered_scripts_5_9_b() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><msub><mrow><mo>(</mo><mrow><mi>Si</mi><msub><mi>O</mi><mn>3</mn></msub></mrow><mo>)</mo></mrow><mi>n</mi></msub><mrow><mn>2</mn><mi>n</mi><mo>-</mo></mrow></msup></math>";
    test_from_braille("Nemeth", expr, "⠷⠠⠎⠊⠠⠕⠒⠾⠰⠝⠐⠘⠆⠝⠤")?;
    Ok(())
}

#[test]
fn state_5_10() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msubsup><mrow><mi>&#x394;</mi><mi>H</mi></mrow><mrow><mo>(</mo><mi>reaction</mi><mo>)</mo></mrow><mo>&#xB0;</mo></msubsup></math>";
    test_from_braille("Nemeth", expr, "⠨⠠⠙⠠⠓⠘⠨⠡⠰⠷⠗⠑⠁⠉⠞⠊⠕⠝⠾")?;
    Ok(())
}

#[test]
fn state_as_subscript_5_13() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><mi>Sn</mi><mrow><mn>2</mn><mo>+</mo></mrow></msup><mrow><mo>(</mo><mi>aq</mi><mo>)</mo></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠎⠝⠘⠆⠬⠐⠷⠁⠟⠾")?;
    Ok(())
}

#[test]
fn prescripts_5_14() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mmultiscripts><mi>Es</mi><mprescripts/><mn>99</mn><mn>254</mn></mmultiscripts><msubsup><mo>+</mo><mn>2</mn><mn>4</mn></msubsup><mi>He</mi><mo>&#x2192;</mo><mmultiscripts><mi>Md</mi><mprescripts/><mn>101</mn><mn>256</mn></mmultiscripts><mo>+</mo><msubsup><mn>2</mn><mn>0</mn><mn>1</mn></msubsup><mi>n</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠰⠔⠔⠘⠆⠢⠲⠐⠠⠑⠎⠬⠰⠆⠘⠲⠐⠠⠓⠑⠀⠫⠕⠀⠰⠂⠴⠂⠘⠆⠢⠖⠐⠠⠍⠙⠬⠆⠰⠴⠘⠂⠐⠝")?;
    Ok(())
}
