// @generated by notes/_gen_nemeth_from_braille_tests.py from tests/braille/Nemeth/other.rs
// Do not edit by hand unless updating the generator.
#![allow(non_snake_case)]

use crate::common::*;
use anyhow::Result;

#[test]
fn not_number_space_blocks() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>123</mn><mo>&#xA0;</mo><mn>456</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠂⠆⠒⠀⠼⠲⠢⠖")?;
    Ok(())
}

#[test]
fn space_between_digits() -> Result<()> {
    let expr = "<math><mn>1</mn><mtext>&#x00a0;</mtext><mn>3</mn><mtext>&#x00a0;</mtext><mn>5</mn></math>";
    test_from_braille("Nemeth", expr, "⠼⠂⠀⠼⠒⠀⠼⠢")?;
    Ok(())
}

#[test]
fn space_hack_between_digits() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>1</mn><mo>&#xA0;</mo><mn>3</mn><mo>&#xA0;</mo><mn>5</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠂⠀⠼⠒⠀⠼⠢")?;
    Ok(())
}

#[test]
fn tilde_prefix_bug_244() -> Result<()> {
    let expr = "<math> <mo>~</mo> <mi>p</mi> </math>";
    test_from_braille("Nemeth", expr, "⠈⠱⠏")?;
    Ok(())
}

#[test]
fn double_struck_bug_334() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>&#x1D7D9;</mn><mo>,</mo><mn>&#x1D7D0;</mn><mo>,</mo><mn>&#x1D7EF;</mn><mo>,</mo><mn>4</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠸⠼⠂⠠⠀⠸⠼⠆⠠⠀⠠⠨⠸⠼⠒⠠⠀⠼⠲")?;
    Ok(())
}

#[test]
fn extra_indicators_bug_343() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><mi>e</mi><msup><mrow><mo>-</mo><mi>x</mi></mrow><mn>2</mn></msup></msup><mo>+</mo><msub><mi>C</mi><mn>1</mn></msub></mrow></math>";
    test_from_braille("Nemeth", expr, "⠑⠘⠤⠭⠘⠘⠆⠐⠬⠠⠉⠂")?;
    Ok(())
}

#[test]
fn no_omission_for_spaces_at_start_or_end_single() -> Result<()> {
    let expr = "<math><mtext> </mtext><mtext> </mtext><mi>x</mi><mtext> </mtext><mtext> </mtext></math>";
    test_from_braille("Nemeth", expr, "⠰⠭")?;
    Ok(())
}

#[test]
fn no_omission_for_spaces_at_start() -> Result<()> {
    let expr = "<math><mtext> </mtext><mtext> </mtext><mn>2</mn><mo>+</mo><mi>x</mi></math>";
    test_from_braille("Nemeth", expr, "⠼⠆⠬⠭")?;
    Ok(())
}

#[test]
fn no_omission_for_spaces_at_end() -> Result<()> {
    let expr = "<math><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><mn>9</mn> <mtext> </mtext><mtext> </mtext><mtext> </mtext><mtext> </mtext><mtext> </mtext></math>";
    test_from_braille("Nemeth", expr, "⠭⠘⠆⠐⠬⠔")?;
    Ok(())
}

#[test]
fn no_omission_for_spaces_in_middle() -> Result<()> {
    let expr = "<math xmlns=\"http://www.w3.org/1998/Math/MathML\" display=\"block\"> <mstyle displaystyle=\"true\" scriptlevel=\"0\"> <mfrac> <mn>1</mn> <mn>2</mn> </mfrac> </mstyle> <mo stretchy=\"false\">(</mo> <mi>p</mi> <mo>+</mo> <mi>q</mi> <mo stretchy=\"false\">)</mo> <mtext>&#xA0;</mtext> <mtext>&#xA0;</mtext> <mtext>&#xA0;</mtext> <mtext>&#xA0;</mtext> <mtext>or</mtext> <mtext>&#xA0;</mtext> <mtext>&#xA0;</mtext> <mtext>&#xA0;</mtext> <mtext>&#xA0;</mtext> <mstyle displaystyle=\"true\" scriptlevel=\"0\"> <mfrac> <mrow> <mi>p</mi> <mo>+</mo> <mi>q</mi> </mrow> <mn>2</mn> </mfrac> </mstyle> </math>";
    test_from_braille("Nemeth", expr, "⠹⠂⠌⠆⠼⠷⠏⠬⠟⠾⠀⠕⠗⠀⠹⠏⠬⠟⠌⠆⠼")?;
    Ok(())
}

#[test]
fn dots() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mover><mi>x</mi><mo>&#xB7;</mo></mover><mo>+</mo><mover><mi>x</mi><mrow><mo>&#xB7;</mo><mo>&#xB7;</mo></mrow></mover><mo>+</mo><mover><mi>x</mi><mrow><mo>&#xB7;</mo><mo>&#xB7;</mo><mo>&#xB7;</mo></mrow></mover></mrow></math>";
    test_from_braille("Nemeth", expr, "⠐⠭⠣⠡⠻⠬⠐⠭⠣⠡⠡⠻⠬⠐⠭⠣⠡⠡⠡⠻")?;
    Ok(())
}
