// @generated by notes/_gen_nemeth_from_braille_tests.py from tests/braille/Nemeth/rules.rs
// Do not edit by hand unless updating the generator.
#![allow(non_snake_case)]

use crate::common::*;
use anyhow::Result;

#[test]
fn num_indicator_9_a_1() -> Result<()> {
    let expr = "<math><mn>27</mn></math>";
    test_from_braille("Nemeth", expr, "⠼⠆⠶")?;
    Ok(())
}

#[test]
fn num_indicator_9_a_4() -> Result<()> {
    let expr = "<math><mrow><mi>y</mi><mo>=</mo><mrow><mn>2</mn><mo>&#x2062;</mo><mrow><mi>sin</mi><mo>&#x2061;</mo><mi>x</mi></mrow></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠽⠀⠨⠅⠀⠼⠆⠎⠊⠝⠀⠭")?;
    Ok(())
}

#[test]
fn num_indicator_9_a_5() -> Result<()> {
    let expr = "<math><mrow><mi>sin</mi><mo>&#x2061;</mo><mn>1</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠎⠊⠝⠀⠼⠂")?;
    Ok(())
}

#[test]
fn num_indicator_9_a_9() -> Result<()> {
    let expr = "<math><mrow><mo>∠</mo><mn>1</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠫⠪⠀⠼⠂")?;
    Ok(())
}

#[test]
fn num_indicator_9_a_14() -> Result<()> {
    let expr = "<math><mo>-</mo><mn>1</mn></math>";
    test_from_braille("Nemeth", expr, "⠤⠼⠂")?;
    Ok(())
}

#[test]
fn num_indicator_9_a_15() -> Result<()> {
    let expr = "<math><mo>-</mo><mn>.3</mn></math>";
    test_from_braille("Nemeth", expr, "⠤⠼⠨⠒")?;
    Ok(())
}

#[test]
fn test_9_b_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mtext>&#x201C;</mtext><mn>3</mn><mo>&#xA0;</mo><mi>dogs</mi><mn>0</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠦⠼⠒⠀⠙⠕⠛⠎⠴")?;
    Ok(())
}

#[test]
fn test_9_b_1_mtext() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mtext>&#x201C;</mtext><mn>3</mn><mo>&#xA0;</mo><mi>dogs</mi><mn>0</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠦⠼⠒⠀⠙⠕⠛⠎⠴")?;
    Ok(())
}

#[test]
fn test_9_b_4() -> Result<()> {
    let expr = "<math><mrow><mo>“</mo><mrow><mo>-</mo><mn>4</mn></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠦⠤⠼⠲")?;
    Ok(())
}

#[test]
fn test_9_c_1_linear() -> Result<()> {
    let expr = "<math><mo>|</mo><mtable> <mtr><mtd><mn>1</mn></mtd><mtd><mn>2</mn></mtd></mtr> <mtr><mtd><mo>-</mo><mn>3</mn></mtd><mtd><mo>-</mo><mn>4</mn></mtd></mtr> </mtable><mo>|</mo></math>";
    test_from_braille("Nemeth", expr, "⠠⠳⠼⠂⠀⠼⠆⠀⣍⠤⠒⠀⠤⠼⠲⠠⠳")?;
    Ok(())
}

#[test]
fn num_indicator_9_d_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>3</mn><mo>#</mo><mn>4</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠒⠨⠼⠼⠲")?;
    Ok(())
}

#[test]
fn num_indicator_9_d_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>3</mn><mtext>&#x283C;</mtext><mn mathvariant=\"script\">4</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠒⠈⠼⠼⠲")?;
    Ok(())
}

#[test]
fn num_indicator_9_e_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mn>&#x1D7CE;</mn></math>";
    test_from_braille("Nemeth", expr, "⠸⠼⠴")?;
    Ok(())
}

#[test]
fn num_indicator_9_e_5() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mn>&#x1D7D2;&#x1D7D1;56</mn></math>";
    test_from_braille("Nemeth", expr, "⠸⠼⠲⠒⠼⠢⠖")?;
    Ok(())
}

#[test]
fn num_indicator_9_e_6() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mo>&#x2464;</mo></math>";
    test_from_braille("Nemeth", expr, "⠫⠉⠸⠫⠼⠢⠻")?;
    Ok(())
}

#[test]
fn num_indicator_9_f_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>1</mn><mo>-</mo><mi>to</mi><mo>-</mo><mn>1</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠂⠤⠞⠕⠤⠼⠂")?;
    Ok(())
}

#[test]
fn non_list_10_4() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>(</mo><mrow><mn>1</mn><mo>,</mo><mn>2</mn><mo>,</mo><mi>and</mi><mo>&#xA0;</mo><mn>3</mn></mrow><mo>)</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠷⠂⠠⠀⠼⠆⠠⠀⠁⠝⠙⠀⠼⠒⠾")?;
    Ok(())
}

#[test]
fn list_10_6_1() -> Result<()> {
    let expr = "<math><mrow><mn>1</mn><mo>,</mo><mi>i</mi><mo>,</mo><mrow><mo>−</mo><mn>1</mn></mrow><mo>,</mo><mrow><mo>−</mo><mi>i</mi></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠂⠠⠀⠰⠊⠠⠀⠤⠼⠂⠠⠀⠤⠊")?;
    Ok(())
}

#[test]
fn list_10_6_8() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>[</mo><mrow><mo>&#x2220;</mo><mo>&#xA0;</mo><msup><mn>1</mn><mo>&#xB0;</mo></msup><mo>,</mo><mi>sin</mi><mo>&#xA0;</mo><msup><mn>1</mn><mo>&#xB0;</mo></msup></mrow><mo>]</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠈⠷⠫⠪⠀⠼⠂⠘⠨⠡⠠⠀⠎⠊⠝⠀⠼⠂⠘⠨⠡⠐⠈⠾")?;
    Ok(())
}

#[test]
fn list_10_6_11() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>(</mo><mrow><mi>x</mi><mo>=</mo><mn>1</mn><mo>,</mo><mn>2</mn><mo>,</mo><mo>&#x2026;</mo><mo>,</mo><mn>10</mn></mrow><mo>)</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠷⠭⠀⠨⠅⠀⠼⠂⠠⠀⠼⠆⠠⠀⠄⠄⠄⠠⠀⠼⠂⠴⠾")?;
    Ok(())
}

#[test]
fn list_10_6_14() -> Result<()> {
    let expr = "<math><mfenced><mrow><mn>1</mn><mo>,</mo><mn>2</mn><mo>,</mo><mn>3</mn></mrow></mfenced></math>";
    test_from_braille("Nemeth", expr, "⠷⠂⠠⠀⠆⠠⠀⠒⠾")?;
    Ok(())
}

#[test]
fn list_num_ind_11_a_1() -> Result<()> {
    let expr = "<math><mo>[</mo><mn>0</mn><mo>,</mo><mn>1</mn><mo>]</mo></math>";
    test_from_braille("Nemeth", expr, "⠈⠷⠴⠠⠀⠂⠈⠾")?;
    Ok(())
}

#[test]
fn list_num_ind_11_a_2() -> Result<()> {
    let expr = "<math><mo>(</mo><mo>-</mo><mn>1</mn><mo>,</mo><mo>-</mo><mn>2</mn><mo>,</mo><mo>-</mo><mn>3</mn><mo>)</mo></math>";
    test_from_braille("Nemeth", expr, "⠷⠤⠂⠠⠀⠤⠆⠠⠀⠤⠒⠾")?;
    Ok(())
}

#[test]
fn list_num_ind__11_a_3() -> Result<()> {
    let expr = "<math><mo>(</mo><mn>1</mn><mo>+</mo><mi>h</mi><mo>,</mo><mn>2</mn><mo>+</mo><mi>k</mi><mo>,</mo><mn>0</mn><mo>)</mo></math>";
    test_from_braille("Nemeth", expr, "⠷⠂⠬⠓⠠⠀⠆⠬⠅⠠⠀⠴⠾")?;
    Ok(())
}

#[test]
fn list_num_ind__11_a_4() -> Result<()> {
    let expr = "<math><mfenced><mrow><mn>0</mn><mo>,</mo><mrow><mo>−</mo><mn>1</mn></mrow><mo>,</mo><mrow><mo>±</mo><mn>2</mn></mrow></mrow></mfenced></math>";
    test_from_braille("Nemeth", expr, "⠷⠴⠠⠀⠤⠂⠠⠀⠬⠤⠆⠾")?;
    Ok(())
}

#[test]
fn list_num_ind_11_a_5() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>(</mo><mrow><mn>2</mn><mi>sin</mi><mo>&#xA0;</mo><msup><mn>30</mn><mo>&#xB0;</mo></msup><mo>,</mo><mn>3</mn><mi>cos</mi><mo>&#xA0;</mo><msup><mn>60</mn><mo>&#xB0;</mo></msup></mrow><mo>)</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠷⠆⠎⠊⠝⠀⠼⠒⠴⠘⠨⠡⠠⠀⠒⠉⠕⠎⠀⠼⠖⠴⠘⠨⠡⠐⠾")?;
    Ok(())
}

#[test]
fn lesson_11_35_1() -> Result<()> {
    let expr = "<math><mrow><mrow><mo>(</mo><mrow><mo>∠</mo><mn>1</mn><mo>,</mo><mo>∠</mo><mn>2</mn><mo>,</mo><mo>∠</mo><mn>3</mn></mrow><mo>)</mo></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠷⠫⠪⠀⠼⠂⠠⠀⠫⠪⠀⠼⠆⠠⠀⠫⠪⠀⠼⠒⠾")?;
    Ok(())
}

#[test]
fn list_num_ind_11_a_7() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>(</mo><mrow><mi>x</mi><mo>,</mo><mn>7</mn><mo>,</mo><mn>&#x1D7D6;</mn><mo>,</mo><mi>y</mi></mrow><mo>)</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠷⠭⠠⠀⠶⠠⠀⠸⠼⠦⠠⠀⠽⠾")?;
    Ok(())
}

#[test]
fn list_num_ind_11_c_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>&#x3D6;</mi><mo>=</mo><mn>3.14159</mn><mo>&#xA0;</mo><mtext>&#x2806;</mtext><mtext>&#x2816;</mtext><mtext>&#x2822;</mtext><mtext>&#x2812;</mtext><mtext>&#x2822;</mtext><mo>&#xA0;</mo><mo>&#x2026;</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠨⠏⠀⠨⠅⠀⠼⠒⠨⠂⠲⠂⠢⠔⠀⠆⠖⠢⠒⠢⠀⠄⠄⠄")?;
    Ok(())
}

#[test]
fn list_num_ind_11_d_1() -> Result<()> {
    let expr = "<math><mrow><mn>65</mn><mo>-</mo><mn>75</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠖⠢⠤⠶⠢")?;
    Ok(())
}

#[test]
fn list_num_ind_11_d_2() -> Result<()> {
    let expr = "<math><mn>3</mn><mo>:</mo><mn>30</mn><mo>&#x2212;</mo><mn>4</mn><mo>:</mo><mn>45</mn></math>";
    test_from_braille("Nemeth", expr, "⠼⠒⠸⠒⠼⠒⠴⠤⠲⠸⠒⠼⠲⠢")?;
    Ok(())
}

#[test]
fn no_num_ind_11_e_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mi>r5</mi></math>";
    test_from_braille("Nemeth", expr, "⠗⠐⠢")?;
    Ok(())
}

#[test]
fn cap_roman_numeral_18_a_3() -> Result<()> {
    let expr = "<math><mtext>VII</mtext><mo>+</mo><mtext>V</mtext><mo>=</mo><mtext>XII</mtext></math>";
    test_from_braille("Nemeth", expr, "⠠⠠⠧⠊⠊⠬⠠⠧⠀⠨⠅⠀⠠⠠⠭⠊⠊")?;
    Ok(())
}

#[test]
fn lower_roman_numeral_18_b_4() -> Result<()> {
    let expr = "<math><mtext>vi</mtext><mo>+</mo><mtext>iv</mtext><mo>=</mo><mtext>x</mtext></math>";
    test_from_braille("Nemeth", expr, "⠧⠊⠬⠊⠧⠀⠨⠅⠀⠭")?;
    Ok(())
}

#[test]
fn cap_22_a_1() -> Result<()> {
    let expr = "<math><mo>&#x25B3;</mo><mo>&#xA0;</mo><mi>A</mi><mi>B</mi><mi>C</mi></math>";
    test_from_braille("Nemeth", expr, "⠫⠞⠀⠠⠁⠠⠃⠠⠉")?;
    Ok(())
}

#[test]
fn greek_24_a_1() -> Result<()> {
    let expr = "<math><mi>α</mi></math>";
    test_from_braille("Nemeth", expr, "⠨⠁")?;
    Ok(())
}

#[test]
fn german_24_a_7() -> Result<()> {
    let expr = "<math><mi>𝔄</mi></math>";
    test_from_braille("Nemeth", expr, "⠸⠠⠁")?;
    Ok(())
}

#[test]
fn hebrew_24_a_8() -> Result<()> {
    let expr = "<math><msub><mi>ℵ</mi><mn>0</mn></msub></math>";
    test_from_braille("Nemeth", expr, "⠠⠠⠁⠴")?;
    Ok(())
}

#[test]
fn russian_24_a_10() -> Result<()> {
    let expr = "<math><mi>А</mi></math>";
    test_from_braille("Nemeth", expr, "⠈⠈⠠⠁")?;
    Ok(())
}

#[test]
fn greek_24_b_1_together() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>&#x3B1;</mi><mi>&#x3B2;</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠨⠁⠨⠃")?;
    Ok(())
}

#[test]
fn greek_24_b_1() -> Result<()> {
    let expr = "<math><mi>α</mi><mi>β</mi></math>";
    test_from_braille("Nemeth", expr, "⠨⠁⠨⠃")?;
    Ok(())
}

#[test]
fn eli_nemeth_UEB_rule_book_4_11_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>p</mi><mo>&#xA0;</mo><mi>D</mi><mo>&#xA0;</mo><mi>z</mi><mo>&#xA0;</mo><mi>R</mi><mo>&#xA0;</mo><mi>x</mi><mo>,</mo><msub><mn>8</mn><msup><mrow><mrow><msup><mrow><mrow><mi>y</mi><mtext>&#x201D;</mtext></mrow><mo>&#xA0;</mo><mtext>&#x201C;</mtext></mrow><mi>w</mi></msup><mo>&#xA0;</mo><mrow><mi>S</mi><mtext>&#x201D;</mtext></mrow></mrow><mo>&#xA0;</mo><mtext>&#x201C;</mtext></mrow><mrow><mi>x</mi><mtext>&#x201D;</mtext><mo>+</mo><mo>?</mo><mi>y</mi><mtext>&#x201D;</mtext></mrow></msup></msub></mrow></math>";
    test_from_braille("Nemeth", expr, "⠰⠏⠀⠰⠠⠙⠀⠰⠵⠀⠰⠠⠗⠀⠰⠭⠠⠀⠦⠰⠽⠸⠴⠀⠦⠰⠺⠀⠰⠠⠎⠸⠴⠀⠦⠰⠭⠸⠴⠬⠸⠦⠰⠽⠸⠴")?;
    Ok(())
}

#[test]
fn letter_26_b_18() -> Result<()> {
    let expr = "<math><mo>(</mo><mi>p</mi><mo>&#xA0;</mo><mtext>and</mtext><mo>&#xA0;</mo><mi>q</mi><mo>)</mo></math>";
    test_from_braille("Nemeth", expr, "⠷⠰⠏⠀⠁⠝⠙⠀⠰⠟⠾")?;
    Ok(())
}

#[test]
fn letter_26_b_19() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>(</mo><mrow><mi>l</mi><mo>,</mo><mi>m</mi><mo>,</mo><mi>n</mi><mo>,</mo><mi>are</mi><mo>&#xA0;</mo><mi>in</mi><mo>&#xA0;</mo><mi>set</mi><mo>&#xA0;</mo><mi>R</mi></mrow><mo>)</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠷⠰⠇⠠⠀⠰⠍⠠⠀⠰⠝⠠⠀⠁⠗⠑⠀⠊⠝⠀⠎⠑⠞⠀⠰⠠⠗⠾")?;
    Ok(())
}

#[test]
fn boldface_32_a_7() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mi>&#x1D586;</mi></math>";
    test_from_braille("Nemeth", expr, "⠸⠸⠁")?;
    Ok(())
}

#[test]
fn boldface_32_a_14() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mi>&#x1D60F;</mi></math>";
    test_from_braille("Nemeth", expr, "⠠⠨⠰⠠⠓")?;
    Ok(())
}

#[test]
fn boldface_32_b_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mn mathvariant=\"script\">2</mn></math>";
    test_from_braille("Nemeth", expr, "⠈⠼⠆")?;
    Ok(())
}

#[test]
fn boldface_32_b_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mn>&#x1D7D1;&#x1D7D2;&#x1D7D3;</mn></math>";
    test_from_braille("Nemeth", expr, "⠸⠼⠒⠲⠢")?;
    Ok(())
}

#[test]
fn boldface_32_b_6() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mn>&#x1D7D2;35</mn></math>";
    test_from_braille("Nemeth", expr, "⠸⠼⠲⠼⠒⠢")?;
    Ok(())
}

#[test]
fn punct_37_1_1() -> Result<()> {
    let expr = "<math> <mfrac><mn>1</mn><mn>2</mn></mfrac> <mo>,</mo> <mfrac><mn>3</mn><mn>4</mn></mfrac> <mo>.</mo> </math>";
    test_from_braille("Nemeth", expr, "⠹⠂⠌⠆⠼⠠⠀⠹⠒⠌⠲⠼⠸⠲")?;
    Ok(())
}

#[test]
fn punct_37_1_2() -> Result<()> {
    let expr = "<math> <mover> <mi>velocity</mi> <mo>_</mo> </mover> <mtext>.</mtext> </math>";
    test_from_braille("Nemeth", expr, "⠐⠧⠑⠇⠕⠉⠊⠞⠽⠣⠱⠻⠸⠲")?;
    Ok(())
}

#[test]
fn punct_37_2_2() -> Result<()> {
    let expr = "<math><mtext>“</mtext> <mn>49</mn> <mtext>”</mtext></math>";
    test_from_braille("Nemeth", expr, "⠦⠼⠲⠔⠸⠴")?;
    Ok(())
}

#[test]
fn punct_37_3_1() -> Result<()> {
    let expr = "<math><mtext>I</mtext><mo>,</mo><mtext>II</mtext><mo>,</mo><mtext>III</mtext><mo>.</mo></math>";
    test_from_braille("Nemeth", expr, "⠰⠠⠊⠠⠀⠠⠠⠊⠊⠠⠀⠠⠠⠊⠊⠊⠸⠲")?;
    Ok(())
}

#[test]
fn punct_37_4_2() -> Result<()> {
    let expr = "<math><mn>1</mn><mo>,</mo><mn>3</mn><mo>,</mo><mo>…</mo><mo>.</mo></math>";
    test_from_braille("Nemeth", expr, "⠼⠂⠠⠀⠼⠒⠠⠀⠄⠄⠄⠸⠲")?;
    Ok(())
}

#[test]
fn punct_37_6_1() -> Result<()> {
    let expr = "<math><mn>5</mn><mo>×</mo><mn>3</mn><mo>=</mo><mo>?</mo><mo>.</mo></math>";
    test_from_braille("Nemeth", expr, "⠼⠢⠈⠡⠒⠀⠨⠅⠀⠿⠸⠲")?;
    Ok(())
}

#[test]
fn punct_37_7_1() -> Result<()> {
    let expr = "<math><mi>a</mi><mo>,</mo><mi>b</mi><mo>,</mo><mi>c</mi><mo>.</mo></math>";
    test_from_braille("Nemeth", expr, "⠰⠁⠠⠀⠰⠃⠠⠀⠰⠉⠸⠲")?;
    Ok(())
}

#[test]
fn punct_37_8_1() -> Result<()> {
    let expr = "<math><mo>&#x25B3;</mo><mi>A</mi><mi>B</mi><mi>C</mi><mo>.</mo></math>";
    test_from_braille("Nemeth", expr, "⠫⠞⠀⠠⠁⠠⠃⠠⠉⠸⠲")?;
    Ok(())
}

#[test]
fn punct_37_11_1() -> Result<()> {
    let expr = "<math><mover><mi>x</mi><mo>&#xAF;</mo></mover><mo>.</mo></math>";
    test_from_braille("Nemeth", expr, "⠭⠱⠸⠲")?;
    Ok(())
}

#[test]
fn punct_37_16_1() -> Result<()> {
    let expr = "<math><mn>100</mn><mo>%</mo><mo>.</mo></math>";
    test_from_braille("Nemeth", expr, "⠼⠂⠴⠴⠈⠴⠸⠲")?;
    Ok(())
}

#[test]
fn punct_37_17_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>0</mn><mo>&#x1D7D8;</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠴⠠⠸⠴")?;
    Ok(())
}

#[test]
fn punct_38_1_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>&#x1F101;</mo><mn>49</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠴⠼⠲⠔")?;
    Ok(())
}

#[test]
fn punct_38_4_12() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>rate</mi><mo>&#xD7;</mo><mi>time</mi><mn>4</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠗⠁⠞⠑⠈⠡⠞⠊⠍⠑⠲")?;
    Ok(())
}

#[test]
fn punct_38_6_1() -> Result<()> {
    let expr = "<math><mn>0</mn><mo>,</mo><mn>1</mn><mo>,</mo><mn>2</mn></math>";
    test_from_braille("Nemeth", expr, "⠼⠴⠠⠀⠼⠂⠠⠀⠼⠆")?;
    Ok(())
}

#[test]
fn punct_38_6_3() -> Result<()> {
    let expr = "<math><mo>(</mo><mn>1</mn><mo>)</mo><mo>,</mo><mo>(</mo><mn>2</mn><mo>)</mo><mo>,</mo><mo>(</mo><mn>3</mn><mo>)</mo><mo>.</mo></math>";
    test_from_braille("Nemeth", expr, "⠷⠂⠾⠠⠀⠷⠆⠾⠠⠀⠷⠒⠾⠸⠲")?;
    Ok(())
}

#[test]
fn colon_40_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>3</mn><mo>:</mo><mn>30</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠒⠸⠒⠼⠒⠴")?;
    Ok(())
}

#[test]
fn colon_40_1_mtext() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>3</mn><mo>:</mo><mn>30</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠒⠸⠒⠼⠒⠴")?;
    Ok(())
}

#[test]
fn colon_40_2() -> Result<()> {
    let expr = "<math><mi>f</mi><mo>:</mo><mo>(</mo><mi>x</mi><mo>,</mo><mi>y</mi><mo>)</mo></math>";
    test_from_braille("Nemeth", expr, "⠰⠋⠸⠒⠷⠭⠠⠀⠽⠾")?;
    Ok(())
}

#[test]
fn dash_42_4() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mfrac><mrow><mo>-</mo><mo>-</mo><mo>-</mo><mo>-</mo><mo>&#xA0;</mo></mrow><mn>15</mn></mfrac><mo>=</mo><mfrac><mn>2</mn><mn>3</mn></mfrac></mrow></math>";
    test_from_braille("Nemeth", expr, "⠹⠤⠤⠤⠤⠀⠌⠂⠢⠼⠀⠨⠅⠀⠹⠆⠌⠒⠼")?;
    Ok(())
}

#[test]
fn dash_42_6() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>$</mo><mn>2</mn><mo>+</mo><mo>$</mo><mn>3</mn><mo>=</mo><mo>$</mo><mo>-</mo><mo>-</mo><mo>-</mo><mo>-</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠈⠎⠆⠬⠈⠎⠒⠀⠨⠅⠀⠈⠎⠤⠤⠤⠤")?;
    Ok(())
}

#[test]
fn ellipsis_43_a_1() -> Result<()> {
    let expr = "<math><mn>1</mn><mo>,</mo><mn>3</mn><mo>,</mo><mn>5</mn><mo>,</mo><mo>…</mo><mo>,</mo><mn>15</mn><mo>.</mo></math>";
    test_from_braille("Nemeth", expr, "⠼⠂⠠⠀⠼⠒⠠⠀⠼⠢⠠⠀⠄⠄⠄⠠⠀⠼⠂⠢⠸⠲")?;
    Ok(())
}

#[test]
fn ellipsis_43_b_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msubsup><mi>p</mi><mn>1</mn><msub><mi>&#x3B1;</mi><mn>1</mn></msub></msubsup><mo>&#x2026;</mo><mo>&#xA0;</mo><msubsup><mi>p</mi><mi>r</mi><msub><mi>&#x3B1;</mi><mi>r</mi></msub></msubsup></mrow></math>";
    test_from_braille("Nemeth", expr, "⠏⠂⠘⠨⠁⠘⠰⠂⠐⠄⠄⠄⠀⠏⠰⠗⠘⠨⠁⠘⠰⠗")?;
    Ok(())
}

#[test]
fn ellipsis_43_b_4() -> Result<()> {
    let expr = "<math><mo>(</mo><mo>…</mo><mo>,</mo><mo>-</mo><mn>1</mn><mo>,</mo><mn>0</mn><mo>,</mo><mn>1</mn><mo>,</mo><mo>…</mo><mo>)</mo></math>";
    test_from_braille("Nemeth", expr, "⠷⠄⠄⠄⠠⠀⠤⠂⠠⠀⠴⠠⠀⠂⠠⠀⠄⠄⠄⠾")?;
    Ok(())
}

#[test]
fn ellipsis_43_b_5() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>12</mn><mo>&#xFFE0;</mo><mo>+</mo><mn>14</mn><mo>&#xFFE0;</mo><mo>=</mo><mo>&#x2026;</mo><mo>&#xFFE0;</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠂⠆⠈⠉⠬⠂⠲⠈⠉⠀⠨⠅⠀⠄⠄⠄⠈⠉")?;
    Ok(())
}

#[test]
fn omission_57_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><mrow><mo>(</mo><mo>?</mo><mo>)</mo></mrow><mn>3</mn></msup><mo>=</mo><mn>27</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠷⠿⠾⠘⠒⠀⠨⠅⠀⠼⠆⠶")?;
    Ok(())
}

#[test]
fn omission_57_3() -> Result<()> {
    let expr = "<math><mn>7</mn><mo>&#xD7;</mo><mn>2</mn><mo>?</mo><mn>14</mn></math>";
    test_from_braille("Nemeth", expr, "⠼⠶⠈⠡⠆⠀⠿⠀⠼⠂⠲")?;
    Ok(())
}

#[test]
fn omission_57_4() -> Result<()> {
    let expr = "<math><mo>?</mo><mo>+</mo><mo>?</mo><mo>=</mo><mn>10</mn></math>";
    test_from_braille("Nemeth", expr, "⠿⠬⠿⠀⠨⠅⠀⠼⠂⠴")?;
    Ok(())
}

#[test]
fn omission_57_5() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>7</mn><mo>-</mo><mo>?</mo><mo>=</mo><mn>5</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠶⠤⠿⠀⠨⠅⠀⠼⠢")?;
    Ok(())
}

#[test]
fn omission_57_6() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>9</mn><mo>-</mo><mn>5</mn><mo>=</mo><mo>?</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠔⠤⠢⠀⠨⠅⠀⠿")?;
    Ok(())
}

#[test]
fn omission_57_7() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mrow><mo>(</mo><mrow><mn>5</mn><mo>,</mo><mo>?</mo></mrow><mo>)</mo></mrow><mo>+</mo><mrow><mo>(</mo><mrow><mo>?</mo><mo>,</mo><mn>15</mn></mrow><mo>)</mo></mrow><mo>=</mo><mrow><mo>(</mo><mrow><mn>7</mn><mo>,</mo><mn>13</mn></mrow><mo>)</mo></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠷⠢⠠⠀⠿⠾⠬⠷⠿⠠⠀⠂⠢⠾⠀⠨⠅⠀⠷⠶⠠⠀⠂⠒⠾")?;
    Ok(())
}

#[test]
fn omission_57_8() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>5</mn><mo>&#xD7;</mo><mn>25</mn><mo>=</mo><mo>?</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠢⠈⠡⠆⠢⠀⠨⠅⠀⠿")?;
    Ok(())
}

#[test]
fn simple_frac_62_a_3() -> Result<()> {
    let expr = "<math><mfrac><mrow><mi>a</mi><mo>+</mo><mi>b</mi></mrow><mi>c</mi></mfrac></math>";
    test_from_braille("Nemeth", expr, "⠹⠁⠬⠃⠌⠉⠼")?;
    Ok(())
}

#[test]
fn beveled_frac_62_b_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mrow><mi>a</mi><mo>+</mo><mi>b</mi></mrow><mo>/</mo><mrow><mi>c</mi><mo>+</mo><mi>d</mi></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠹⠁⠬⠃⠸⠌⠉⠬⠙⠼")?;
    Ok(())
}

#[test]
fn mixed_frac_63_a_1() -> Result<()> {
    let expr = "<math><mn>4</mn><mfrac><mn>3</mn><mn>8</mn></mfrac></math>";
    test_from_braille("Nemeth", expr, "⠼⠲⠸⠹⠒⠌⠦⠸⠼")?;
    Ok(())
}

#[test]
fn mixed_frac_64_2() -> Result<()> {
    let expr = "<math><mn>4</mn><mn>3</mn><mo>/</mo><mn>8</mn></math>";
    test_from_braille("Nemeth", expr, "⠼⠲⠸⠹⠒⠸⠌⠦⠸⠼")?;
    Ok(())
}

#[test]
fn complex_frac_66_1() -> Result<()> {
    let expr = "<math><mfrac><mfrac><mn>3</mn><mn>8</mn></mfrac><mn>5</mn></mfrac></math>";
    test_from_braille("Nemeth", expr, "⠠⠹⠹⠒⠌⠦⠼⠠⠌⠢⠠⠼")?;
    Ok(())
}

#[test]
fn non_hyper_complex_frac_67_1() -> Result<()> {
    let expr = "<math><mfrac><mi>a</mi><msup><mi>b</mi> <mfrac> <mfrac><mn>3</mn><mn>4</mn></mfrac> <mfrac><mn>5</mn><mn>6</mn></mfrac> </mfrac> </msup></mfrac></math>";
    test_from_braille("Nemeth", expr, "⠹⠁⠌⠃⠘⠠⠹⠹⠒⠌⠲⠼⠠⠌⠹⠢⠌⠖⠼⠠⠼⠐⠼")?;
    Ok(())
}

#[test]
fn hyper_complex_frac_68_a_1() -> Result<()> {
    let expr = "<math><mfrac> <mfrac> <mrow><mn>1</mn><mfrac><mn>1</mn><mn>4</mn></mfrac></mrow> <mrow><mn>1</mn><mfrac><mn>3</mn><mn>5</mn></mfrac></mrow> </mfrac> <mn>5</mn> </mfrac></math>";
    test_from_braille("Nemeth", expr, "⠠⠠⠹⠠⠹⠂⠸⠹⠂⠌⠲⠸⠼⠠⠌⠂⠸⠹⠒⠌⠢⠸⠼⠠⠼⠠⠠⠌⠢⠠⠠⠼")?;
    Ok(())
}

#[test]
fn nested_sup_74_b_1() -> Result<()> {
    let expr = "<math><msup><mi>n</mi><msup><mi>x</mi><mi>y</mi></msup></msup></math>";
    test_from_braille("Nemeth", expr, "⠝⠘⠭⠘⠘⠽")?;
    Ok(())
}

#[test]
fn nested_sup_mmultiscripts_74_b_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><mi>n</mi><msup><mi>x</mi><mi>y</mi></msup></msup></math>";
    test_from_braille("Nemeth", expr, "⠝⠘⠭⠘⠘⠽")?;
    Ok(())
}

#[test]
fn nested_sup_74_b_4() -> Result<()> {
    let expr = "<math><msub><mi>n</mi><msub><mi>x</mi><mi>y</mi></msub></msub></math>";
    test_from_braille("Nemeth", expr, "⠝⠰⠭⠰⠰⠽")?;
    Ok(())
}

#[test]
fn nested_sub_sup_74_c_5() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><mi>n</mi><msub><msub><msub><mi>x</mi><mi>a</mi></msub><mi>j</mi></msub><mi>j</mi></msub></msup></math>";
    test_from_braille("Nemeth", expr, "⠝⠘⠭⠘⠰⠁⠘⠰⠰⠚")?;
    Ok(())
}

#[test]
fn as_multiscript_nested_sub_sup_74_c_5() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><mi>n</mi><msub><msub><msub><mi>x</mi><mi>a</mi></msub><mi>j</mi></msub><mi>j</mi></msub></msup></math>";
    test_from_braille("Nemeth", expr, "⠝⠘⠭⠘⠰⠁⠘⠰⠰⠚")?;
    Ok(())
}

#[test]
fn left_sup_75_1() -> Result<()> {
    let expr = "<math><mmultiscripts><mi>n</mi><mprescripts/><none/><mi>x</mi></mmultiscripts></math>";
    test_from_braille("Nemeth", expr, "⠘⠭⠐⠝")?;
    Ok(())
}

#[test]
fn left_sup_75_4() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msub><mmultiscripts><mi>n</mi><mprescripts/><mi>x</mi><none/></mmultiscripts><mi>y</mi></msub></math>";
    test_from_braille("Nemeth", expr, "⠰⠭⠐⠝⠰⠽")?;
    Ok(())
}

#[test]
fn left_sup_75_7() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mmultiscripts><mi>x</mi><mprescripts/><none/><msup><msub><mtext>&#xFFFD;</mtext><mi>a</mi></msub><mi>n</mi></msup></mmultiscripts></math>";
    test_from_braille("Nemeth", expr, "⠘⠰⠁⠘⠝⠐⠭")?;
    Ok(())
}

#[test]
fn left_sup_75_8() -> Result<()> {
    let expr = "<math><mmultiscripts><mi>x</mi><mprescripts/><msup><mi>n</mi><mi>a</mi></msup><none/></mmultiscripts></math>";
    test_from_braille("Nemeth", expr, "⠰⠝⠰⠘⠁⠐⠭")?;
    Ok(())
}

#[test]
fn left_sup_75_12() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><msup><mi>p</mi><mi>b</mi></msup><mi>c</mi></msup><mi>q</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠏⠘⠃⠐⠘⠉⠐⠟")?;
    Ok(())
}

#[test]
fn left_sub_14_104() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msub><msub><mi>P</mi><mi>b</mi></msub><mi>c</mi></msub><mi>Q</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠏⠰⠃⠐⠰⠉⠐⠠⠟")?;
    Ok(())
}

#[test]
fn german_base_77_4_3() -> Result<()> {
    let expr = "<math><msub> <mi>𝔄</mi> <mn>1</mn> </msub></math>";
    test_from_braille("Nemeth", expr, "⠸⠠⠁⠂")?;
    Ok(())
}

#[test]
fn prime_77_4_4() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><mi>x</mi><mo>&#x2032;</mo></msup><mtext>&#x2802;</mtext></mrow></math>";
    test_from_braille("Nemeth", expr, "⠭⠄⠂")?;
    Ok(())
}

#[test]
fn prescript_77_4_6() -> Result<()> {
    let expr = "<math><mmultiscripts> <mi>x</mi> <mprescripts/> <mn>3</mn><none/></mmultiscripts></math>";
    test_from_braille("Nemeth", expr, "⠰⠒⠐⠭")?;
    Ok(())
}

#[test]
fn prescript_77_4_7() -> Result<()> {
    let expr = "<math><msub><mi>x</mi><msub><mi>i</mi><mn>1</mn></msub></msub></math>";
    test_from_braille("Nemeth", expr, "⠭⠰⠊⠰⠰⠂")?;
    Ok(())
}

#[test]
fn log_77_4_8() -> Result<()> {
    let expr = "<math><msub><mi>log</mi><mn>2</mn></msub> <mi>x</mi></math>";
    test_from_braille("Nemeth", expr, "⠇⠕⠛⠆⠀⠭")?;
    Ok(())
}

#[test]
fn mmultiscripts_77_4_10() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msub><mrow><mo>(</mo><mrow><mi>C</mi><msub><mi>O</mi><mn>3</mn></msub></mrow><mo>)</mo></mrow><mn>2</mn></msub></math>";
    test_from_braille("Nemeth", expr, "⠷⠠⠉⠠⠕⠒⠾⠰⠆")?;
    Ok(())
}

#[test]
fn word_77_4_12() -> Result<()> {
    let expr = "<math><msub><mi>seven</mi><mn>3</mn></msub></math>";
    test_from_braille("Nemeth", expr, "⠎⠑⠧⠑⠝⠰⠒")?;
    Ok(())
}

#[test]
fn prescript_77_4_18() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msub><mmultiscripts><mi>x</mi><mprescripts/><mn>3</mn><none/></mmultiscripts><mn>1</mn></msub></math>";
    test_from_braille("Nemeth", expr, "⠰⠒⠐⠭⠂")?;
    Ok(())
}

#[test]
fn mmultiscripts_77_4_18() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msub><mmultiscripts><mi>x</mi><mprescripts/><mn>3</mn><none/></mmultiscripts><mn>1</mn></msub></math>";
    test_from_braille("Nemeth", expr, "⠰⠒⠐⠭⠂")?;
    Ok(())
}

#[test]
fn comma_number_77_4_20() -> Result<()> {
    let expr = "<math><msub><mi>x</mi><mrow><mn>10</mn><mo>,</mo><mn>000</mn></mrow></msub></math>";
    test_from_braille("Nemeth", expr, "⠭⠂⠴⠠⠴⠴⠴")?;
    Ok(())
}

#[test]
fn sum_77_4_23() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msubsup><mi>&#x3A3;</mi><mn>0</mn><mi>n</mi></msubsup><msub><mi>a</mi><mi>k</mi></msub></mrow></math>";
    test_from_braille("Nemeth", expr, "⠨⠠⠎⠴⠘⠝⠐⠁⠰⠅")?;
    Ok(())
}

#[test]
fn product_77_4_24() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msubsup><mi>&#x3A0;</mi><mn>0</mn><mi>n</mi></msubsup><msub><mi>a</mi><mi>k</mi></msub></mrow></math>";
    test_from_braille("Nemeth", expr, "⠨⠠⠏⠴⠘⠝⠐⠁⠰⠅")?;
    Ok(())
}

#[test]
fn integral_77_4_26() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msubsup><mo>&#x222B;</mo><mn>0</mn><msqrt><mrow><mn>1</mn><mo>-</mo><msup><mi>x</mi><msup><msup><mtext>&#xFFFD;</mtext><mn>2</mn></msup><mrow></mrow></msup></msup></mrow></msqrt></msubsup><mi>f</mi><mrow><mo>(</mo><mi>x</mi><mo>)</mo></mrow><mi>dx</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠮⠰⠴⠘⠜⠂⠤⠭⠘⠘⠆⠘⠻⠐⠋⠷⠭⠾⠙⠭")?;
    Ok(())
}

#[test]
fn comma_space_78_1() -> Result<()> {
    let expr = "<math><msub><mi>x</mi> <mrow><mi>i</mi><mo>,</mo><mo>&#xA0;</mo><mi>j</mi><mo>,</mo><mo>&#xA0;</mo><mi>k</mi></mrow></msub></math>";
    test_from_braille("Nemeth", expr, "⠭⠰⠊⠪⠚⠪⠅")?;
    Ok(())
}

#[test]
fn comma_78_2() -> Result<()> {
    let expr = "<math><msub><mi>x</mi><mrow><mo>(</mo><mi>a</mi><mo>,</mo><mi>b</mi><mo>)</mo></mrow></msub></math>";
    test_from_braille("Nemeth", expr, "⠭⠰⠷⠁⠪⠃⠾")?;
    Ok(())
}

#[test]
fn comma_78_2_invisible() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msub><mi>x</mi><mrow><mo>(</mo><mrow><mi>a</mi><mo>,</mo><mi>b</mi></mrow><mo>)</mo></mrow></msub></math>";
    test_from_braille("Nemeth", expr, "⠭⠰⠷⠁⠪⠃⠾")?;
    Ok(())
}

#[test]
fn comma_78_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msub><mi>x</mi><mrow><mn>1</mn><mo>,</mo><mtext>&#x2806;</mtext></mrow></msub></math>";
    test_from_braille("Nemeth", expr, "⠭⠰⠂⠪⠆")?;
    Ok(())
}

#[test]
fn comma_78_6() -> Result<()> {
    let expr = "<math><mo>(</mo><mi>x</mi><mo>,</mo><mo>&#xA0;</mo><mi>y</mi><mo>)</mo></math>";
    test_from_braille("Nemeth", expr, "⠷⠭⠠⠀⠽⠾")?;
    Ok(())
}

#[test]
fn nested_super_79_a_2() -> Result<()> {
    let expr = "<math><msub><mi>x</mi><mi>a</mi></msub><mo>+</mo><msup><mi>y</mi><mn>2</mn></msup></math>";
    test_from_braille("Nemeth", expr, "⠭⠰⠁⠐⠬⠽⠘⠆")?;
    Ok(())
}

#[test]
fn nested_super_79_a_3() -> Result<()> {
    let expr = "<math><mfrac><mrow><msup><mi>e</mi><mrow><msup><mi>x</mi><mn>2</mn></msup></mrow></msup></mrow><mn>2</mn></mfrac></math>";
    test_from_braille("Nemeth", expr, "⠹⠑⠘⠭⠘⠘⠆⠐⠌⠆⠼")?;
    Ok(())
}

#[test]
fn punctuation_after_sup_79_b_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><mi>x</mi><msup><mrow><mn>2</mn><mo>,</mo><mi>x</mi></mrow><mn>3</mn></msup></msup></math>";
    test_from_braille("Nemeth", expr, "⠭⠘⠆⠠⠀⠭⠘⠒")?;
    Ok(())
}

#[test]
fn comma_in_number_in_sup_79_b_3() -> Result<()> {
    let expr = "<math><msup><mi>x</mi><mrow><mn>10</mn><mo>,</mo><mn>000</mn></mrow></msup></math>";
    test_from_braille("Nemeth", expr, "⠭⠘⠂⠴⠠⠴⠴⠴")?;
    Ok(())
}

#[test]
fn comma_in_sup_79_b_4() -> Result<()> {
    let expr = "<math><msub><mi>x</mi><mrow><mi>i</mi><mo>,</mo><mi>j</mi></mrow></msub></math>";
    test_from_braille("Nemeth", expr, "⠭⠰⠊⠪⠚")?;
    Ok(())
}

#[test]
fn comma_ellipsis_in_sub_79_b_5() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msub><mi>P</mi><mrow><msup><msub><msup><msub><mi>n</mi><mn>1</mn></msub><mrow><mo>,</mo><mi>n</mi></mrow></msup><mn>2</mn></msub><mo>,</mo></msup><mo>&#xA0;</mo><mo>&#x2026;</mo></mrow></msub></math>";
    test_from_braille("Nemeth", expr, "⠠⠏⠰⠝⠰⠰⠂⠰⠪⠝⠰⠰⠆⠰⠪⠀⠄⠄⠄")?;
    Ok(())
}

#[test]
fn text_after_sup_79_c_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>6.696</mn><mo>&#xD7;</mo><msup><mn>10</mn><mn>8</mn></msup><mo>&#xA0;</mo><mi>mph</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠖⠨⠖⠔⠖⠈⠡⠂⠴⠘⠦⠀⠍⠏⠓")?;
    Ok(())
}

#[test]
fn table_entry_after_sup_79_c_4() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>(</mo><mrow><msup><mi>x</mi><mn>2</mn></msup><mo>&#xA0;</mo><msup><mi>y</mi><mn>2</mn></msup></mrow><mo>)</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠷⠭⠘⠆⠀⠽⠘⠆⠐⠾")?;
    Ok(())
}

#[test]
fn nested_super_space_79_d_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><mi>cos</mi><mn>2</mn></msup><mo>&#xA0;</mo><mi>x</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠉⠕⠎⠘⠆⠀⠭")?;
    Ok(())
}

#[test]
fn nested_super_space_79_d_7() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><mi>e</mi><mrow><msup><mi>cos</mi><mn>2</mn></msup><mo>&#xA0;</mo><mi>x</mi></mrow></msup></math>";
    test_from_braille("Nemeth", expr, "⠑⠘⠉⠕⠎⠘⠘⠆⠀⠭")?;
    Ok(())
}

#[test]
fn nested_sup_sup_space_79_d_9() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><mi>q</mi><mrow><msub><mi>log</mi><mi>q</mi></msub><mo>&#xA0;</mo><mi>a</mi></mrow></msup></math>";
    test_from_braille("Nemeth", expr, "⠟⠘⠇⠕⠛⠘⠰⠟⠀⠁")?;
    Ok(())
}

#[test]
fn whitespace_in_sup_79_e_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><mi>e</mi><mn>3.14159</mn></msup><mo>&#xA0;</mo><mtext>&#x2806;</mtext><mtext>&#x2816;</mtext><mtext>&#x2822;</mtext><mtext>&#x2812;</mtext><mtext>&#x2822;</mtext></mrow></math>";
    test_from_braille("Nemeth", expr, "⠑⠘⠒⠨⠂⠲⠂⠢⠔⠀⠆⠖⠢⠒⠢")?;
    Ok(())
}

#[test]
fn ellipsis_level_79_f_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><mi>x</mi><mrow><mn>1</mn><mo>+</mo><mn>1</mn></mrow></msup></math>";
    test_from_braille("Nemeth", expr, "⠭⠘⠂⠬⠂⠸⠌⠆⠬⠂⠸⠌⠒⠬⠀⠄⠄⠄⠀⠬⠂⠸⠌⠝")?;
    Ok(())
}

#[test]
fn comparison_79_g_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><mn>2</mn><mi>x</mi></msup><mo>&lt;</mo><msup><mn>3</mn><mi>x</mi></msup></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠆⠘⠭⠀⠐⠅⠀⠼⠒⠘⠭")?;
    Ok(())
}

#[test]
fn sub_ind_79_g_4() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>&#x222B;</mo><mi>u</mi><mo>&#xA0;</mo><mmultiscripts><mi>a</mi><mprescripts/><mo>=</mo><none/></mmultiscripts></mrow></math>";
    test_from_braille("Nemeth", expr, "⠮⠰⠥⠀⠰⠨⠅⠀⠁")?;
    Ok(())
}

#[test]
fn baseline_80_a_1() -> Result<()> {
    let expr = "<math><msqrt><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><msup><mi>y</mi><mn>2</mn></msup></msqrt></math>";
    test_from_braille("Nemeth", expr, "⠜⠭⠘⠆⠐⠬⠽⠘⠆⠐⠻")?;
    Ok(())
}

#[test]
fn superscript_80_a_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><mi>e</mi><msqrt><msup><mi>x</mi><msup><msup><msup><msup><mtext>&#xFFFD;</mtext><mn>2</mn></msup><mrow><mo>+</mo><mi>y</mi></mrow></msup><mn>2</mn></msup><mrow></mrow></msup></msup></msqrt></msup></math>";
    test_from_braille("Nemeth", expr, "⠑⠘⠜⠭⠘⠘⠆⠘⠬⠽⠘⠘⠆⠘⠻")?;
    Ok(())
}

#[test]
fn sub_ind_80_b_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msub><msub><mi>P</mi><mn>1</mn></msub><mn>2</mn></msub><mi>Q</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠏⠂⠐⠰⠆⠐⠠⠟")?;
    Ok(())
}

#[test]
fn left_sub_14_105() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msub><msub><mi>P</mi><mn>1</mn></msub><mn>2</mn></msub><mi>Q</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠏⠂⠐⠰⠆⠐⠠⠟")?;
    Ok(())
}

#[test]
fn sub_ind_mmultiscripts_80_b_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msub><mi>P</mi><msup><mn>1</mn><mn>2</mn></msup></msub><mi>Q</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠏⠂⠰⠆⠐⠠⠟")?;
    Ok(())
}

#[test]
fn sub_ind_80_b_4() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msub><mi>A</mi><mrow></mrow></msub><mover><mi>x</mi><mo>~</mo></mover><msub><mo>+</mo><mrow></mrow></msub><mover><mi>y</mi><mo>~</mo></mover></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠁⠰⠐⠭⠣⠈⠱⠻⠬⠰⠐⠽⠣⠈⠱⠻")?;
    Ok(())
}

#[test]
fn numeric_sub_81_a_1() -> Result<()> {
    let expr = "<math><mo>(</mo><msub><mi>x</mi><mn>1</mn></msub><mo>+</mo><mn>1</mn><mo>)</mo></math>";
    test_from_braille("Nemeth", expr, "⠷⠭⠂⠬⠂⠾")?;
    Ok(())
}

#[test]
fn msubsup_82_a_1() -> Result<()> {
    let expr = "<math><msubsup><mi>x</mi><mi>a</mi><mi>n</mi></msubsup></math>";
    test_from_braille("Nemeth", expr, "⠭⠰⠁⠘⠝")?;
    Ok(())
}

#[test]
fn msubsup_82_a_3() -> Result<()> {
    let expr = "<math><msubsup><mi>x</mi><mn>1</mn><mn>2</mn></msubsup></math>";
    test_from_braille("Nemeth", expr, "⠭⠂⠘⠆")?;
    Ok(())
}

#[test]
fn mmultiscripts_82_a_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msubsup><mi>x</mi><mi>a</mi><mi>n</mi></msubsup></math>";
    test_from_braille("Nemeth", expr, "⠭⠰⠁⠘⠝")?;
    Ok(())
}

#[test]
fn mmultiscripts_82_a_2() -> Result<()> {
    let expr = "<math><mmultiscripts><mi>x</mi><mprescripts/><mi>a</mi><mi>n</mi></mmultiscripts></math>";
    test_from_braille("Nemeth", expr, "⠰⠁⠘⠝⠐⠭")?;
    Ok(())
}

#[test]
fn mmultiscripts_82_a_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msubsup><mi>x</mi><mn>1</mn><mn>2</mn></msubsup></math>";
    test_from_braille("Nemeth", expr, "⠭⠂⠘⠆")?;
    Ok(())
}

#[test]
fn sub_sup_82_b_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><mi>a</mi><mi>n</mi></msup><mi>m</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠁⠘⠝⠐⠰⠍")?;
    Ok(())
}

#[test]
fn mmultiscripts_82_b_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><mi>a</mi><mi>n</mi></msup><mi>m</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠁⠘⠝⠐⠰⠍")?;
    Ok(())
}

#[test]
fn sub_sup_82_b_2() -> Result<()> {
    let expr = "<math><msup><msub><mi>a</mi><mi>m</mi></msub><mi>n</mi></msup></math>";
    test_from_braille("Nemeth", expr, "⠁⠰⠍⠐⠘⠝")?;
    Ok(())
}

#[test]
fn mmultiscripts_82_b_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><msub><mi>a</mi><mi>m</mi></msub><mi>n</mi></msup></math>";
    test_from_braille("Nemeth", expr, "⠁⠰⠍⠐⠘⠝")?;
    Ok(())
}

#[test]
fn mmultiscripts_82_b_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mmultiscripts><mi>x</mi><mprescripts/><mi>b</mi><mi>a</mi></mmultiscripts></math>";
    test_from_braille("Nemeth", expr, "⠘⠁⠐⠰⠃⠐⠭")?;
    Ok(())
}

#[test]
fn mmultiscripts_82_b_4() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><mi>b</mi><mi>a</mi></msup><mi>x</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠰⠃⠐⠘⠁⠐⠭")?;
    Ok(())
}

#[test]
fn mmultiscripts_82_b_5() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><msub><mi>x</mi><mn>1</mn></msub><mn>2</mn></msup></math>";
    test_from_braille("Nemeth", expr, "⠭⠂⠐⠘⠆")?;
    Ok(())
}

#[test]
fn mmultiscripts_82_b_6() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><msubsup><mi>x</mi><mi>a</mi><mo>&#x2032;</mo></msubsup><mi>b</mi></msup></math>";
    test_from_braille("Nemeth", expr, "⠭⠄⠰⠁⠐⠘⠃")?;
    Ok(())
}

#[test]
fn prime_83_b_1() -> Result<()> {
    let expr = "<math><msubsup><mi>x</mi><mi>a</mi><mo>'</mo></msubsup></math>";
    test_from_braille("Nemeth", expr, "⠭⠄⠰⠁")?;
    Ok(())
}

#[test]
fn prime_mmultiscripts_83_b_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><mi>x</mi><mrow><mo>&#x2032;</mo><mn>2</mn></mrow></msup></math>";
    test_from_braille("Nemeth", expr, "⠭⠄⠘⠆")?;
    Ok(())
}

#[test]
fn prime_mathjax_83_b_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><mi>x</mi><mrow><mo>&#x2032;</mo><mn>2</mn></mrow></msup></math>";
    test_from_braille("Nemeth", expr, "⠭⠄⠘⠆")?;
    Ok(())
}

#[test]
fn prime_wiris_83_b_2() -> Result<()> {
    let expr = "<math><msup><mi>x</mi> <mrow><mi>&#x2032;</mi><mn>2</mn></mrow> </msup></math>";
    test_from_braille("Nemeth", expr, "⠭⠄⠘⠆")?;
    Ok(())
}

#[test]
fn prime_83_b_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msubsup><mi>x</mi><mi>a</mi><mrow><mo>&#x2032;</mo><mi>b</mi></mrow></msubsup></math>";
    test_from_braille("Nemeth", expr, "⠭⠄⠰⠁⠘⠃")?;
    Ok(())
}

#[test]
fn prime_83_b_4() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><mi>x</mi><mo>&#x2057;</mo></msup><msup><mtext>&#x2802;</mtext><mn>3</mn></msup></mrow></math>";
    test_from_braille("Nemeth", expr, "⠭⠄⠄⠂⠘⠒")?;
    Ok(())
}

#[test]
fn prime_mmultiscripts_83_b_4() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><mi>x</mi><mo>&#x2057;</mo></msup><msup><mtext>&#x2802;</mtext><mn>3</mn></msup></mrow></math>";
    test_from_braille("Nemeth", expr, "⠭⠄⠄⠂⠘⠒")?;
    Ok(())
}

#[test]
fn prime_83_b_5() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><mi>x</mi><mrow><mo>&#x2032;</mo><mtext>&#x283C;</mtext></mrow></msup></math>";
    test_from_braille("Nemeth", expr, "⠭⠄⠘⠈⠼")?;
    Ok(())
}

#[test]
fn prime_83_b_6() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msup><mi>x</mi><mrow><mtext>&#x283C;</mtext><mo>&#x2032;</mo></mrow></msup></math>";
    test_from_braille("Nemeth", expr, "⠭⠘⠈⠼⠄")?;
    Ok(())
}

#[test]
fn prime_83_b_7() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msubsup><mi>A</mi><mi>ue</mi><mrow><mtext>&#x283C;</mtext><mo>&#x2032;</mo></mrow></msubsup></math>";
    test_from_braille("Nemeth", expr, "⠠⠁⠰⠥⠑⠘⠈⠼⠄")?;
    Ok(())
}

#[test]
fn prime_83_b_8() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msubsup><mi>A</mi><mi>ue</mi><mrow><mo>&#x2032;</mo><mtext>&#x283C;</mtext></mrow></msubsup></math>";
    test_from_braille("Nemeth", expr, "⠠⠁⠄⠰⠥⠑⠘⠈⠼")?;
    Ok(())
}

#[test]
fn underbar_86_a_1() -> Result<()> {
    let expr = "<math><munder><mi>x</mi><mo>&#xAF;</mo></munder></math>";
    test_from_braille("Nemeth", expr, "⠭⠩⠱")?;
    Ok(())
}

#[test]
fn menclose_86_a_1() -> Result<()> {
    // menclose bottom is not recoverable; reverse emits munder.
    let expr = "<math><munder><mi>x</mi><mo>&#xAF;</mo></munder></math>";
    test_from_braille("Nemeth", expr, "⠭⠩⠱")?;
    Ok(())
}

#[test]
fn lim_86_a_3() -> Result<()> {
    let expr = "<math><munder><mi>lim</mi><mrow><mi>x</mi><mo>&#x2192;</mo><mn>0</mn></mrow></munder><mi>f</mi><mo>(</mo><mi>x</mi><mo>)</mo></math>";
    test_from_braille("Nemeth", expr, "⠐⠇⠊⠍⠩⠭⠀⠫⠕⠀⠼⠴⠻⠀⠋⠷⠭⠾")?;
    Ok(())
}

#[test]
fn overbar_86_a_4() -> Result<()> {
    let expr = "<math><mover><msup><mi>x</mi><mn>2</mn></msup><mo>&#xAF;</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠐⠭⠘⠆⠐⠣⠱⠻")?;
    Ok(())
}

#[test]
fn menclose_86_a_4() -> Result<()> {
    // menclose top is not recoverable; reverse emits mover.
    let expr = "<math><mover><msup><mi>x</mi><mn>2</mn></msup><mo>&#xAF;</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠐⠭⠘⠆⠐⠣⠱⠻")?;
    Ok(())
}

#[test]
fn overbar_86_a_5() -> Result<()> {
    let expr = "<math><mover><msup><mi>x</mi><mn>2</mn></msup><mo>&#xAF;</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠐⠭⠘⠆⠐⠣⠱⠻")?;
    Ok(())
}

#[test]
fn mathml_spec_example_86_a() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mover><mrow><mo>(</mo><mrow><mo>&#xAF;</mo><mfrac><mi>a</mi><mi>b</mi></mfrac></mrow><mo>)</mo></mrow><mo>&#xAF;</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠐⠷⠩⠱⠻⠹⠁⠌⠃⠼⠐⠾⠣⠱⠻")?;
    Ok(())
}

#[test]
fn mathml_spec_example_alt_char_86_a() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mover><mrow><mo>(</mo><mrow><mo>&#xAF;</mo><mfrac><mi>a</mi><mi>b</mi></mfrac></mrow><mo>)</mo></mrow><mo>&#xAF;</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠐⠷⠩⠱⠻⠹⠁⠌⠃⠼⠐⠾⠣⠱⠻")?;
    Ok(())
}

#[test]
fn menclose_lesson_12_5_5_5() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>A</mi><mrow><mo>(</mo><mfrac linethickness=\"0\"><mi>s</mi><mrow><mo>&#xAF;</mo><mi>n</mi></mrow></mfrac><mo>)</mo></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠁⠷⠎⠩⠱⠝⠾")?;
    Ok(())
}

#[test]
fn munder_lesson_12_5_5_5() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>A</mi><mrow><mo>(</mo><mfrac linethickness=\"0\"><mi>s</mi><mrow><mo>&#xAF;</mo><mi>n</mi></mrow></mfrac><mo>)</mo></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠁⠷⠎⠩⠱⠝⠾")?;
    Ok(())
}

#[test]
fn overbar_86_b_1() -> Result<()> {
    let expr = "<math><mover><mi>x</mi><mo>&#xAF;</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠭⠱")?;
    Ok(())
}

#[test]
fn menclose_86_b_1() -> Result<()> {
    // menclose top is not recoverable; reverse emits mover.
    let expr = "<math><mover><mi>x</mi><mo>&#xAF;</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠭⠱")?;
    Ok(())
}

#[test]
fn overbar_86_b_2() -> Result<()> {
    let expr = "<math><mover> <mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow> <mo>&#xAF;</mo> </mover></math>";
    test_from_braille("Nemeth", expr, "⠐⠭⠬⠽⠣⠱⠻")?;
    Ok(())
}

#[test]
fn primed_86_b_6() -> Result<()> {
    let expr = "<math><msup><mrow><mover><mi>x</mi><mo>&#xAF;</mo></mover></mrow><mo>&#x2032;</mo></msup></math>";
    test_from_braille("Nemeth", expr, "⠭⠱⠄")?;
    Ok(())
}

#[test]
fn menclose_primed_86_b_6() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mover><mi>x</mi><mo>&#xAF;</mo></mover><mo>&#x2032;</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠭⠱⠄")?;
    Ok(())
}

#[test]
fn overbar_86_b_10() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mover><mn>3.54</mn><mo>&#xAF;</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠼⠒⠨⠢⠲⠱")?;
    Ok(())
}

#[test]
fn overbar_86_b_11() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mover><mrow><mo>(</mo><mrow><mover><mi>a</mi><mo>&#xAF;</mo></mover><mi>&#x1D468;</mi><mo>+</mo><mover><mi>b</mi><mo>&#xAF;</mo></mover><mi>&#x1D469;</mi></mrow><mo>)</mo></mrow><mo>&#xAF;</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠐⠷⠁⠱⠸⠰⠠⠁⠬⠃⠱⠸⠰⠠⠃⠾⠣⠱⠻")?;
    Ok(())
}

#[test]
fn menclose_86_b_11() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mover><mrow><mo>(</mo><mrow><mover><mi>a</mi><mo>&#xAF;</mo></mover><mi>&#x1D468;</mi><mo>+</mo><mover><mi>b</mi><mo>&#xAF;</mo></mover><mi>&#x1D469;</mi></mrow><mo>)</mo></mrow><mo>&#xAF;</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠐⠷⠁⠱⠸⠰⠠⠁⠬⠃⠱⠸⠰⠠⠃⠾⠣⠱⠻")?;
    Ok(())
}

#[test]
fn order2_overbar_87_a_1() -> Result<()> {
    let expr = "<math><mover> <mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow> <mover><mo>&#xAF;</mo><mrow><mi>a</mi><mo>=</mo><mn>3</mn></mrow></mover> </mover></math>";
    test_from_braille("Nemeth", expr, "⠐⠭⠬⠽⠣⠱⠣⠣⠁⠀⠨⠅⠀⠼⠒⠻")?;
    Ok(())
}

#[test]
fn bar_above_and_below_88_1() -> Result<()> {
    let expr = "<math><munderover> <mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow> <mo>&#xAF;</mo> <mo>&#xAF;</mo> </munderover></math>";
    test_from_braille("Nemeth", expr, "⠐⠭⠬⠽⠩⠱⠣⠱⠻")?;
    Ok(())
}

#[test]
fn above_and_below_88_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><munderover><mi>&#x3A3;</mi><mrow><mi>n</mi><mo>=</mo><mn>1</mn></mrow><mo>&#x221E;</mo></munderover><mfrac><mn>1</mn><msup><mn>2</mn><mi>n</mi></msup></mfrac><mo>=</mo><mn>1</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠐⠨⠠⠎⠩⠝⠀⠨⠅⠀⠼⠂⠣⠠⠿⠻⠹⠂⠌⠆⠘⠝⠐⠼⠀⠨⠅⠀⠼⠂")?;
    Ok(())
}

#[test]
fn menclose_top_bottom_88_1() -> Result<()> {
    // menclose top+bottom is not recoverable; reverse emits munderover with bars.
    let expr = "<math><munderover><mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow><mo>&#xAF;</mo><mo>&#xAF;</mo></munderover></math>";
    test_from_braille("Nemeth", expr, "⠐⠭⠬⠽⠩⠱⠣⠱⠻")?;
    Ok(())
}

#[test]
fn binomial_90_1() -> Result<()> {
    let expr = "<math><mo>(</mo><mfrac linethickness='0'><mi>n</mi><mi>k</mi></mfrac><mo>)</mo></math>";
    test_from_braille("Nemeth", expr, "⠷⠝⠩⠅⠾")?;
    Ok(())
}

#[test]
fn binomial_90_1_mtable() -> Result<()> {
    // Forward uses mtable+intent; reverse recovers parenthesized linethickness=0 mfrac.
    let expr = "<math><mo>(</mo><mfrac linethickness=\"0\"><mi>n</mi><mi>k</mi></mfrac><mo>)</mo></math>";
    test_from_braille("Nemeth", expr, "⠷⠝⠩⠅⠾")?;
    Ok(())
}

#[test]
fn modifier_in_script_91_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msub><mi>A</mi><mrow></mrow></msub><mover><mi>x</mi><mo>~</mo></mover></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠁⠰⠐⠭⠣⠈⠱⠻")?;
    Ok(())
}

#[test]
fn arrow_96_1() -> Result<()> {
    let expr = "<math> <mover> <mrow><mi mathvariant='normal'>A</mi> <mi mathvariant='normal'>B</mi></mrow> <mo>→</mo> </mover> </math>";
    test_from_braille("Nemeth", expr, "⠐⠠⠁⠠⠃⠣⠫⠕⠻")?;
    Ok(())
}

#[test]
fn arrow_96_10() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>X</mi><mover><mo>&#x2192;</mo><mrow><mi>f</mi><mo>&#xB0;</mo><mi>g</mi></mrow></mover><mi>Y</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠭⠀⠐⠫⠒⠒⠕⠣⠋⠨⠡⠛⠻⠀⠠⠽")?;
    Ok(())
}

#[test]
fn bar_97_b_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mover><mn>.3</mn><mo>&#xAF;</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠼⠨⠒⠱")?;
    Ok(())
}

#[test]
fn menclose_bar_97_b_1() -> Result<()> {
    // menclose top over a digit is not recoverable; reverse emits mover.
    let expr = "<math><mover><mn>.3</mn><mo>&#xAF;</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠼⠨⠒⠱")?;
    Ok(())
}

#[test]
fn menclose_bar_97_b_3() -> Result<()> {
    let expr = "<math><mn>3.57</mn><mover><mn>29</mn><mo stretchy='true'>&#xAF;</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠼⠒⠨⠢⠶⠐⠆⠔⠣⠱⠻")?;
    Ok(())
}

#[test]
fn carrot_98_1() -> Result<()> {
    let expr = "<math><mover><mi>x</mi><mo>^</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠐⠭⠣⠸⠣⠻")?;
    Ok(())
}

#[test]
fn dots_99_a_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>.</mo><mover><mn>3</mn><mo>&#xB7;</mo></mover></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠨⠐⠒⠣⠡⠻")?;
    Ok(())
}

#[test]
fn dots_99_a_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>.</mo><mover><mn>135</mn><mo>&#xB7;</mo></mover></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠨⠐⠂⠒⠢⠣⠡⠻")?;
    Ok(())
}

#[test]
fn dots_99_a_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>.13</mn><mover><mn>5</mn><mo>&#xB7;</mo></mover></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠨⠂⠒⠐⠢⠣⠡⠻")?;
    Ok(())
}

#[test]
fn ring_dot_100_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mover><mo>=</mo><mo>&#xB0;</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠐⠨⠅⠣⠨⠡⠻")?;
    Ok(())
}

#[test]
fn question_mark_over_equals_101_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mover><mo>=</mo><mo>?</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠐⠨⠅⠣⠸⠦⠻")?;
    Ok(())
}

#[test]
fn question_mark_under_equals_101_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><munder><mo>=</mo><mo>?</mo></munder></math>";
    test_from_braille("Nemeth", expr, "⠐⠨⠅⠩⠸⠦⠻")?;
    Ok(())
}

#[test]
fn sqrt_103_a_2() -> Result<()> {
    let expr = "<math><msqrt><mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow></msqrt></math>";
    test_from_braille("Nemeth", expr, "⠜⠭⠬⠽⠻")?;
    Ok(())
}

#[test]
fn sqrt_103_a_4() -> Result<()> {
    let expr = "<math><msqrt> <msup><mi>x</mi><mn>2</mn></msup> <mo>+</mo> <msup><mi>y</mi><mn>2</mn></msup> </msqrt></math>";
    test_from_braille("Nemeth", expr, "⠜⠭⠘⠆⠐⠬⠽⠘⠆⠐⠻")?;
    Ok(())
}

#[test]
fn sqrt_103_b_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><msqrt><mrow><mo>(</mo><mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow><mo>)</mo></mrow></msqrt></math>";
    test_from_braille("Nemeth", expr, "⠜⠷⠭⠬⠽⠾")?;
    Ok(())
}

#[test]
fn root_104_iii_1() -> Result<()> {
    let expr = "<math><mroot><mn>2</mn><mn>3</mn></mroot></math>";
    test_from_braille("Nemeth", expr, "⠣⠒⠜⠆⠻")?;
    Ok(())
}

#[test]
fn root_104_iii_4() -> Result<()> {
    let expr = "<math><mroot> <mrow><mi>p</mi><mo>+</mo><mi>q</mi></mrow> <mrow><mi>m</mi><mo>+</mo><mi>n</mi></mrow> </mroot></math>";
    test_from_braille("Nemeth", expr, "⠣⠍⠬⠝⠜⠏⠬⠟⠻")?;
    Ok(())
}

#[test]
fn nested_sqrt_105_1() -> Result<()> {
    let expr = "<math><msqrt><mi>x</mi><mo>+</mo> <msqrt><mi>x</mi><mo>+</mo><mi>y</mi></msqrt> <mo>+</mo><mi>z</mi></msqrt></math>";
    test_from_braille("Nemeth", expr, "⠜⠭⠬⠨⠜⠭⠬⠽⠨⠻⠬⠵⠻")?;
    Ok(())
}

#[test]
fn nested_root_105_2() -> Result<()> {
    let expr = "<math><mroot> <mrow> <msup> <mi>x</mi><mn>2</mn> </msup> <mo>+</mo> <mroot> <mrow> <msup> <mi>x</mi> <mn>2</mn> </msup> <mo>+</mo> <msup> <mi>y</mi> <mn>2</mn> </msup> </mrow> <mn>3</mn> </mroot> <mo>+</mo> <msup> <mi>y</mi> <mn>2</mn> </msup> </mrow> <mn>3</mn> </mroot></math>";
    test_from_braille("Nemeth", expr, "⠣⠒⠜⠭⠘⠆⠐⠬⠨⠣⠒⠜⠭⠘⠆⠐⠬⠽⠘⠆⠐⠨⠻⠬⠽⠘⠆⠐⠻")?;
    Ok(())
}

#[test]
fn nested_sqrt_105_3() -> Result<()> {
    let expr = "<math> <msqrt> <mroot> <mi>x</mi><mn>3</mn> </mroot> </msqrt> <mo>=</mo> <mroot> <msqrt><mi>x</mi></msqrt> <mn>3</mn></mroot> </math>";
    test_from_braille("Nemeth", expr, "⠜⠨⠣⠒⠜⠭⠨⠻⠻⠀⠨⠅⠀⠣⠒⠜⠨⠜⠭⠨⠻⠻")?;
    Ok(())
}

#[test]
fn nested_sqrt_105_4() -> Result<()> {
    let expr = "<math> <msqrt><mi>x</mi><mo>+</mo><msqrt><mi>y</mi><mo>+</mo><msqrt><mi>z</mi></msqrt></msqrt></msqrt> </math>";
    test_from_braille("Nemeth", expr, "⠜⠭⠬⠨⠜⠽⠬⠨⠨⠜⠵⠨⠨⠻⠨⠻⠻")?;
    Ok(())
}

#[test]
fn menclose_111_a_4() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>&#x2220;</mo><mtext>&#x2838;</mtext><mtext>&#x282B;</mtext><msup><mn>30</mn><mo>&#xB0;</mo></msup></mrow></math>";
    test_from_braille("Nemeth", expr, "⠫⠪⠸⠫⠼⠒⠴⠘⠨⠡⠐⠻")?;
    Ok(())
}

#[test]
fn menclose_111_a_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>&#x25CB;</mo><mtext>&#x2838;</mtext><mtext>&#x282B;</mtext><mi>A</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠫⠉⠸⠫⠠⠁⠻")?;
    Ok(())
}

#[test]
fn shape_115_a_1() -> Result<()> {
    let expr = "<math><mo>∠</mo><mn>1</mn></math>";
    test_from_braille("Nemeth", expr, "⠫⠪⠀⠼⠂")?;
    Ok(())
}

#[test]
fn shape_115_a_3() -> Result<()> {
    let expr = "<math><mo>&#x25CB;</mo><mi>R</mi></math>";
    test_from_braille("Nemeth", expr, "⠫⠉⠀⠠⠗")?;
    Ok(())
}

#[test]
fn shape_115_a_6() -> Result<()> {
    let expr = "<math><mo>∟</mo><mi>A</mi></math>";
    test_from_braille("Nemeth", expr, "⠫⠪⠨⠗⠻⠀⠠⠁")?;
    Ok(())
}

#[test]
fn shape_115_a_11() -> Result<()> {
    let expr = "<math><mi>m</mi><mo>&#x2220;</mo><mi>A</mi><mi>B</mi><mi>C</mi></math>";
    test_from_braille("Nemeth", expr, "⠍⠫⠪⠀⠠⠁⠠⠃⠠⠉")?;
    Ok(())
}

#[test]
fn function_space_119_c_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>sin</mi><mo>&#xA0;</mo><msup><mn>30</mn><mo>&#xB0;</mo></msup><mi>cos</mi><mo>&#xA0;</mo><msup><mn>45</mn><mo>&#xB0;</mo></msup><mo>+</mo><mi>cos</mi><mo>&#xA0;</mo><msup><mn>30</mn><mo>&#xB0;</mo></msup><mi>sin</mi><mo>&#xA0;</mo><msup><mn>45</mn><mo>&#xB0;</mo></msup></mrow></math>";
    test_from_braille("Nemeth", expr, "⠎⠊⠝⠀⠼⠒⠴⠘⠨⠡⠐⠉⠕⠎⠀⠼⠲⠢⠘⠨⠡⠐⠬⠉⠕⠎⠀⠼⠒⠴⠘⠨⠡⠐⠎⠊⠝⠀⠼⠲⠢⠘⠨⠡")?;
    Ok(())
}

#[test]
fn brace_above_121_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mover><mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow><mo>{</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠐⠭⠬⠽⠣⠨⠷⠻")?;
    Ok(())
}

#[test]
fn brace_below_121_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><munder><mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow><mrow></mrow></munder></math>";
    test_from_braille("Nemeth", expr, "⠐⠭⠬⠽⠩⠨⠾⠻")?;
    Ok(())
}

#[test]
fn bracket_above_121_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mover><mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow><mo>[</mo></mover></math>";
    test_from_braille("Nemeth", expr, "⠐⠭⠬⠽⠣⠈⠷⠻")?;
    Ok(())
}

#[test]
fn racket_below_121_4() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><munder><mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow><mrow></mrow></munder></math>";
    test_from_braille("Nemeth", expr, "⠐⠭⠬⠽⠩⠈⠾⠻")?;
    Ok(())
}

#[test]
fn identity_matrix_126_linearize() -> Result<()> {
    let expr = "<math> <mrow><mo>(</mo> <mtable> <mtr><mtd><mn>1</mn></mtd><mtd><mn>0</mn></mtd><mtd><mn>0</mn></mtd></mtr> <mtr><mtd><mn>0</mn></mtd><mtd><mn>1</mn></mtd><mtd><mn>0</mn></mtd></mtr> <mtr><mtd><mn>0</mn></mtd><mtd><mn>0</mn></mtd><mtd><mn>1</mn></mtd></mtr> </mtable><mo>)</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠷⠼⠂⠀⠼⠴⠀⠼⠴⠀⣍⠴⠀⠼⠂⠀⠼⠴⠀⣍⠴⠀⠼⠴⠀⠼⠂⠠⠾")?;
    Ok(())
}

#[test]
fn multipurpose_134_1() -> Result<()> {
    let expr = "<math><mo>+</mo><mn>2</mn><mo>-</mo><mo>+</mo><mn>3</mn></math>";
    test_from_braille("Nemeth", expr, "⠬⠆⠤⠐⠬⠒")?;
    Ok(())
}

#[test]
fn plus_minus_134_4() -> Result<()> {
    let expr = "<math><mi>x</mi><mo>&#xB1;</mo><mi>y</mi></math>";
    test_from_braille("Nemeth", expr, "⠭⠬⠤⠽")?;
    Ok(())
}

#[test]
fn multipurpose_lesson_5_2_3() -> Result<()> {
    let expr = "<math><mn>10</mn><mo>+</mo><mo>-</mo><mn>5</mn></math>";
    test_from_braille("Nemeth", expr, "⠼⠂⠴⠬⠐⠤⠢")?;
    Ok(())
}

#[test]
fn multipurpose_lesson_5_2_4() -> Result<()> {
    let expr = "<math><mn>10</mn><mo>-</mo><mo>+</mo><mn>5</mn></math>";
    test_from_braille("Nemeth", expr, "⠼⠂⠴⠤⠐⠬⠢")?;
    Ok(())
}

#[test]
fn multipurpose_lesson_5_2_5() -> Result<()> {
    let expr = "<math><mn>10</mn><mo>-</mo><mo>-</mo><mn>5</mn></math>";
    test_from_braille("Nemeth", expr, "⠼⠂⠴⠤⠐⠤⠢")?;
    Ok(())
}

#[test]
fn tilde_137_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>~</mo><mi>p</mi><mo>&#x22C1;</mo><mo>~</mo><mi>q</mi><mo>&#x22C1;</mo><mo>~</mo><mi>r</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠈⠱⠏⠈⠬⠈⠱⠟⠈⠬⠈⠱⠗")?;
    Ok(())
}

#[test]
fn tilde_137_3() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>~~</mo><mi>T</mi><mo>&#x22C1;</mo><mi>R</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠈⠱⠐⠈⠱⠠⠞⠈⠬⠠⠗")?;
    Ok(())
}

#[test]
fn tilde_137_3_mathjax() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>~~</mo><mi>T</mi><mo>&#x22C1;</mo><mi>R</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠈⠱⠐⠈⠱⠠⠞⠈⠬⠠⠗")?;
    Ok(())
}

#[test]
fn tilde_144_1() -> Result<()> {
    let expr = "<math><mi>x</mi><mo>∼</mo><mi>y</mi></math>";
    test_from_braille("Nemeth", expr, "⠭⠀⠈⠱⠀⠽")?;
    Ok(())
}

#[test]
fn set_vertical_bar_145_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>{</mo><mrow><mi>x</mi><mo>&#xA0;</mo><mrow><mo>|</mo><mrow><mo>&#xA0;</mo><mrow><mo>|</mo><mrow><mi>x</mi><mrow><mo>|</mo><mrow><mo>&lt;</mo><mn>10</mn></mrow><mo>}</mo></mrow></mrow></mrow></mrow></mrow></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠨⠷⠭⠀⠳⠀⠳⠭⠳⠀⠐⠅⠀⠼⠂⠴⠨⠾")?;
    Ok(())
}

#[test]
fn vertical_bar_145_4() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>P</mi><mrow><mo>(</mo><mrow><mi>A</mi><mo>&#xA0;</mo><mrow><mo>|</mo><mrow><mo>&#xA0;</mo><mi>B</mi></mrow><mo>)</mo></mrow></mrow></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠏⠷⠠⠁⠀⠳⠀⠠⠃⠾")?;
    Ok(())
}

#[test]
fn ratio_151_10() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>1</mn><mo>&#xA0;</mo><mn>1</mn><mo>&#xA0;</mo><mn>2</mn><mo>&#xA0;</mo><mmultiscripts><mn>3</mn><mprescripts/><mn>2</mn><none/></mmultiscripts><mo>&#xA0;</mo><mn>1</mn><mo>&#xA0;</mo><mn>6</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠂⠀⠐⠂⠀⠼⠆⠀⠰⠆⠀⠼⠒⠀⠐⠂⠀⠼⠖")?;
    Ok(())
}

#[test]
fn ratio_151_11() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>a</mi><mo>+</mo><mi>b</mi><mo>&#xA0;</mo><mn>1</mn><mo>&#xA0;</mo><mi>b</mi><mo>&#xA0;</mo><mmultiscripts><mi>c</mi><mprescripts/><mn>2</mn><none/></mmultiscripts><mo>+</mo><mi>d</mi><mo>&#xA0;</mo><mn>1</mn><mo>&#xA0;</mo><mi>d</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠁⠬⠃⠀⠐⠂⠀⠃⠀⠰⠆⠀⠉⠬⠙⠀⠐⠂⠀⠙")?;
    Ok(())
}

#[test]
fn space_after_punct_bug_152() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mn>7</mn><mover><mo>=</mo><mo>?</mo></mover><mn>8</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠶⠀⠐⠨⠅⠣⠸⠦⠻⠀⠼⠦")?;
    Ok(())
}

#[test]
fn arrow_lesson_9_5_1() -> Result<()> {
    let expr = "<math><mi>A</mi><mo>→</mo><mi>B</mi></math>";
    test_from_braille("Nemeth", expr, "⠠⠁⠀⠫⠕⠀⠠⠃")?;
    Ok(())
}

#[test]
fn not_ratio_nfb_5_7_b_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>{</mo><mrow><mi>x</mi><mo>:</mo><mo>&#xA0;</mo><mi>x</mi><mo>&gt;</mo><mn>0</mn></mrow><mo>}</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠨⠷⠰⠭⠸⠒⠀⠭⠀⠨⠂⠀⠼⠴⠨⠾")?;
    Ok(())
}

#[test]
fn not_ratio_nfb_5_7_b_4() -> Result<()> {
    let expr = "<math><mi>p</mi><mo>:</mo><mi>r</mi><mo>=</mo><mi>q</mi><mo>:</mo><mi>s</mi></math>";
    test_from_braille("Nemeth", expr, "⠰⠏⠸⠒⠗⠀⠨⠅⠀⠟⠸⠒⠰⠎")?;
    Ok(())
}

#[test]
fn trilinear_not_ratio() -> Result<()> {
    let expr = "<math><mi>a</mi><mo>:</mo><mi>b</mi><mo>:</mo><mi>c</mi></math>";
    test_from_braille("Nemeth", expr, "⠰⠁⠸⠒⠰⠃⠸⠒⠰⠉")?;
    Ok(())
}

#[test]
fn extension_field_not_ratio() -> Result<()> {
    let expr = "<math><mo>[</mo><mi>K</mi><mo>:</mo><mi>F</mi><mo>]</mo></math>";
    test_from_braille("Nemeth", expr, "⠈⠷⠰⠠⠅⠸⠒⠰⠠⠋⠈⠾")?;
    Ok(())
}

#[test]
fn proportional_151_12() -> Result<()> {
    let expr = "<math><mi>x</mi><mo>∝</mo><mi>y</mi></math>";
    test_from_braille("Nemeth", expr, "⠭⠀⠸⠿⠀⠽")?;
    Ok(())
}

#[test]
fn comparison_ops_151_14() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>{</mo><mrow><mi>x</mi><mo>&#xA0;</mo><mrow><mo>|</mo><mrow><mo>&#xA0;</mo><mn>0</mn><mo>&#x2264;</mo><mi>x</mi><mo>&#x2264;</mo><mn>1</mn></mrow><mo>}</mo></mrow></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠨⠷⠭⠀⠳⠀⠼⠴⠀⠐⠅⠱⠀⠭⠀⠐⠅⠱⠀⠼⠂⠨⠾")?;
    Ok(())
}

#[test]
fn no_space_comparison_151_16() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>(</mo><mrow><mo>&lt;</mo><mo>,</mo><mo>=</mo><mo>,</mo><mn>.1</mn></mrow><mo>)</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠷⠐⠅⠠⠀⠨⠅⠠⠀⠨⠂⠾")?;
    Ok(())
}

#[test]
fn in_scripts_comparison_151_17() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>&#x222B;</mo><mi>x</mi><mo>&#xA0;</mo><msup><mmultiscripts><mi>a</mi><mprescripts/><mo>=</mo><none/></mmultiscripts><mi>x</mi></msup><mo>&#xA0;</mo><mmultiscripts><mi>b</mi><mprescripts/><none/><mo>=</mo></mmultiscripts><mi>f</mi><mrow><mo>(</mo><mi>x</mi><mo>)</mo></mrow><mi>dx</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠮⠰⠭⠀⠰⠨⠅⠀⠁⠘⠭⠀⠘⠨⠅⠀⠃⠐⠋⠷⠭⠾⠙⠭")?;
    Ok(())
}

#[test]
fn degrees_165_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><mn>90</mn><mo>&#xB0;</mo></msup><mo>+</mo><msup><mn>90</mn><mo>&#xB0;</mo></msup><mo>=</mo><msup><mn>180</mn><mo>&#xB0;</mo></msup></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠔⠴⠘⠨⠡⠐⠬⠔⠴⠘⠨⠡⠀⠨⠅⠀⠼⠂⠦⠴⠘⠨⠡")?;
    Ok(())
}

#[test]
fn prime_172_5() -> Result<()> {
    let expr = "<math><msubsup><mi>x</mi><mi>i</mi><mo>'</mo></msubsup></math>";
    test_from_braille("Nemeth", expr, "⠭⠄⠰⠊")?;
    Ok(())
}

#[test]
fn prime_172_6() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><mi>x</mi><mo>&#x2032;</mo></msup><mtext>&#x2802;</mtext></mrow></math>";
    test_from_braille("Nemeth", expr, "⠭⠄⠂")?;
    Ok(())
}

#[test]
fn prime_172_8() -> Result<()> {
    let expr = "<math><msup><mover><mi>x</mi><mo>&#xAF;</mo></mover><mo>'</mo></msup></math>";
    test_from_braille("Nemeth", expr, "⠭⠱⠄")?;
    Ok(())
}

#[test]
fn prime_172_9() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><mn>5</mn><mo>&#x2032;</mo></msup><msup><mtext>&#x201C;</mtext><mo>&#x2057;</mo></msup></mrow></math>";
    test_from_braille("Nemeth", expr, "⠼⠢⠄⠦⠄⠄")?;
    Ok(())
}

#[test]
fn multipurpose_177_2_1() -> Result<()> {
    let expr = "<math> <mi>x5</mi> </math>";
    test_from_braille("Nemeth", expr, "⠭⠐⠢")?;
    Ok(())
}

#[test]
fn multipurpose_177_2_2() -> Result<()> {
    let expr = "<math> <mi>x</mi> <mn>.6</mn> </math>";
    test_from_braille("Nemeth", expr, "⠭⠐⠨⠖")?;
    Ok(())
}

#[test]
fn multipurpose_177_3_1() -> Result<()> {
    let expr = "<math> <msub><mi>c</mi><mn>0</mn></msub> <msup><mn>10</mn><mn>2</mn></msup> <mo>+</mo> <msub><mi>c</mi><mn>1</mn></msub> <mn>10</mn><mo>+</mo> <msub><mi>c</mi><mn>2</mn></msub> </math>";
    test_from_braille("Nemeth", expr, "⠉⠴⠐⠂⠴⠘⠆⠐⠬⠉⠂⠐⠂⠴⠬⠉⠆")?;
    Ok(())
}

#[test]
fn multipurpose_177_5_1() -> Result<()> {
    let expr = "<math><mn>0.</mn><msub><mi>a</mi><mn>1</mn></msub><msub><mi>a</mi><mn>2</mn></msub><mo>…</mo></math>";
    test_from_braille("Nemeth", expr, "⠼⠴⠨⠐⠁⠂⠁⠆⠀⠄⠄⠄")?;
    Ok(())
}

#[test]
fn multipurpose_177_5_4() -> Result<()> {
    let expr = "<math><mn>3.</mn><mo>+</mo><mn>.4</mn><mo>=</mo><mn>3.4</mn></math>";
    test_from_braille("Nemeth", expr, "⠼⠒⠨⠐⠬⠨⠲⠀⠨⠅⠀⠼⠒⠨⠲")?;
    Ok(())
}

#[test]
fn multipurpose_177_5_5() -> Result<()> {
    let expr = "<math><mo>(</mo><mn>3.</mn><mo>)</mo></math>";
    test_from_braille("Nemeth", expr, "⠷⠒⠨⠐⠾")?;
    Ok(())
}

#[test]
fn multipurpose_177_5_6() -> Result<()> {
    let expr = "<math><mfrac><mn>1.</mn><mn>2.</mn></mfrac></math>";
    test_from_braille("Nemeth", expr, "⠹⠂⠨⠐⠌⠆⠨⠐⠼")?;
    Ok(())
}

#[test]
fn multipurpose_177_7_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>|</mo><mrow><mi>x</mi><mrow><mo>|</mo><mrow><mo>|</mo><mrow><mi>y</mi><mo>|</mo></mrow></mrow></mrow></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠳⠭⠳⠐⠳⠽⠳")?;
    Ok(())
}

#[test]
fn multipurpose_177_7_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>|</mo><mrow><mo>|</mo><mrow><mi>x</mi><mrow><mo>|</mo><mrow><mo>|</mo><mrow><mo>|</mo><mrow><mo>|</mo><mrow><mi>y</mi><mrow><mo>|</mo><mo>|</mo></mrow></mrow></mrow></mrow></mrow></mrow></mrow></mrow></mrow></math>";
    test_from_braille("Nemeth", expr, "⠳⠳⠭⠳⠳⠐⠳⠳⠽⠳⠳")?;
    Ok(())
}

#[test]
fn multipurpose_177_7_9() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>~~</mo><mi>T</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠈⠱⠐⠈⠱⠠⠞")?;
    Ok(())
}

#[test]
fn no_multipurpose_lesson_5_2_6() -> Result<()> {
    let expr = "<math><mo>-</mo><mn>10</mn><mo>+</mo><mo>+</mo><mn>5</mn></math>";
    test_from_braille("Nemeth", expr, "⠤⠼⠂⠴⠬⠬⠢")?;
    Ok(())
}

#[test]
fn multipurpose_lesson_5_9_1_1() -> Result<()> {
    let expr = "<math><mi>n</mi><mo>&gt;</mo><mo>&lt;</mo><mn>1</mn></math>";
    test_from_braille("Nemeth", expr, "⠝⠀⠨⠂⠐⠐⠅⠀⠼⠂")?;
    Ok(())
}

#[test]
fn multipurpose_lesson_5_9_2_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>n</mi><mo>&lt;</mo><mn>.1</mn><mo>&#xA0;</mo><mn>1</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠝⠀⠐⠅⠐⠨⠂⠀⠼⠂")?;
    Ok(())
}

#[test]
fn multipurpose_lesson_5_9_2_2() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>n</mi><mo>&lt;</mo><mo>=</mo><mn>.1</mn><mo>&#xA0;</mo><mn>1</mn></mrow></math>";
    test_from_braille("Nemeth", expr, "⠝⠀⠐⠅⠐⠨⠅⠐⠨⠂⠀⠼⠂")?;
    Ok(())
}

#[test]
fn lesson_11_24_1() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mtext>&#x282B;</mtext><msup><mi>kx</mi><mn>2</mn></msup></mrow></math>";
    test_from_braille("Nemeth", expr, "⠫⠅⠭⠘⠆⠐⠻")?;
    Ok(())
}

#[test]
fn ms_38_4_8() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>(</mo><mrow><mo>?</mo><mi>three</mi><mn>0</mn></mrow><mo>)</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠷⠸⠦⠞⠓⠗⠑⠑⠴⠾")?;
    Ok(())
}

#[test]
fn ms() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mo>&#x2057;</mo><mi>a</mi><mo>&#xA0;</mo><msup><mi>string</mi><mo>&#x2057;</mo></msup><mo>,</mo><mo>&#x2018;</mo><mi>another</mi><mo>&#xA0;</mo><mi>string</mi><mo>&#x1F101;</mo></mrow></math>";
    test_from_braille("Nemeth", expr, "⠄⠄⠁⠀⠎⠞⠗⠊⠝⠛⠄⠄⠠⠀⠸⠠⠦⠁⠝⠕⠞⠓⠑⠗⠀⠎⠞⠗⠊⠝⠛⠠⠴")?;
    Ok(())
}

#[test]
fn full_binomial() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><mrow><mo>(</mo><mrow><mi>x</mi><mo>+</mo><mi>a</mi></mrow><mo>)</mo></mrow><mi>n</mi></msup><mo>=</mo><munderover><mi>&#x3A3;</mi><mrow><mi>k</mi><mo>=</mo><mn>0</mn></mrow><mi>n</mi></munderover><mrow><mo>(</mo><mfrac linethickness=\"0\"><mi>n</mi><mi>k</mi></mfrac><mo>)</mo></mrow><msup><mi>x</mi><mi>k</mi></msup><msup><mi>a</mi><mrow><mi>n</mi><mo>-</mo><mi>k</mi></mrow></msup></mrow></math>";
    test_from_braille("Nemeth", expr, "⠷⠭⠬⠁⠾⠘⠝⠀⠨⠅⠀⠐⠨⠠⠎⠩⠅⠀⠨⠅⠀⠼⠴⠣⠝⠻⠷⠝⠩⠅⠾⠭⠘⠅⠐⠁⠘⠝⠤⠅")?;
    Ok(())
}

#[test]
fn number_space_before() -> Result<()> {
    let expr = "<math><mtext>&#xA0;</mtext><mn>2</mn></math>";
    test_from_braille("Nemeth", expr, "⠼⠆")?;
    Ok(())
}

#[test]
fn number_space_after() -> Result<()> {
    let expr = "<math><mn>2</mn><mtext>&#xA0;</mtext></math>";
    test_from_braille("Nemeth", expr, "⠼⠆")?;
    Ok(())
}

#[test]
fn number_space_before_and_after() -> Result<()> {
    let expr = "<math><mtext>&#xA0;</mtext><mn>2</mn><mtext>&#xA0;</mtext></math>";
    test_from_braille("Nemeth", expr, "⠼⠆")?;
    Ok(())
}

#[test]
fn tensor_from_mathml_spec() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><msup><msub><mi>R</mi><mi>i</mi></msub><mi>j</mi></msup><mi>k</mi><mi>l</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠗⠰⠊⠐⠘⠚⠐⠰⠅⠐⠰⠇")?;
    Ok(())
}

#[test]
fn perpendicular_17_57() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>A</mi><mi>B</mi><mo>&#xA0;</mo><mo>&#x27C2;</mo><mo>&#xA0;</mo><mi>C</mi><mi>D</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠁⠠⠃⠀⠫⠏⠀⠠⠉⠠⠙")?;
    Ok(())
}

#[test]
fn chem_HOH_1_1_1_mchem() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>H</mi><mo>:</mo><mi>O</mi><mo>:</mo><mi>H</mi></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠓⠸⠒⠻⠠⠕⠸⠒⠻⠠⠓")?;
    Ok(())
}

#[test]
fn chem_2_5_1_mchem() -> Result<()> {
    // Forward MathML is not recoverable from this Nemeth; reverse form.
    let expr = "<math><mrow><mi>Ca</mi><msub><mi>C</mi><mn>2</mn></msub><mo>+</mo><mn>2</mn><mi>H</mi><mi>O</mi><mi>H</mi><mo>&#xA0;</mo><mtext>&#x282B;</mtext><mtext>&#x2812;</mtext><mtext>&#x2812;</mtext><mtext>&#x2812;</mtext><mi>o</mi><mo>&#xA0;</mo><mi>H</mi><mo>:</mo><mi>C</mi><mo>&#x2261;</mo><mi>C</mi><mo>:</mo><mi>H</mi><mo>+</mo><mi>Ca</mi><msub><mrow><mo>(</mo><mrow><mi>O</mi><mi>H</mi></mrow><mo>)</mo></mrow><mn>2</mn></msub></mrow></math>";
    test_from_braille("Nemeth", expr, "⠠⠉⠁⠠⠉⠆⠬⠆⠠⠓⠠⠕⠠⠓⠀⠫⠒⠒⠒⠕⠀⠠⠓⠸⠒⠻⠠⠉⠸⠿⠻⠠⠉⠸⠒⠻⠠⠓⠬⠠⠉⠁⠷⠠⠕⠠⠓⠾⠰⠆")?;
    Ok(())
}
