// @generated by notes/_gen_ueb_from_braille_tests.py from tests/braille/UEB/iceb.rs
// Do not edit by hand unless updating the generator.
#![allow(non_snake_case)]

use crate::common::*;
use anyhow::Result;

#[test]
fn bana_2_1() -> Result<()> {
    let expr = "<math><mn>6</mn><mo>=</mo><mn>1</mn><mo>&#xD7;</mo><mn>2</mn><mo>&#xD7;</mo><mn>3</mn> <mo>=</mo><mn>1</mn><mo>+</mo><mn>2</mn><mo>+</mo><mn>3</mn></math>";
    test_from_braille("UEB", expr, "⠼⠋⠀⠐⠶⠀⠼⠁⠐⠦⠼⠃⠐⠦⠼⠉⠀⠐⠶⠀⠼⠁⠐⠖⠼⠃⠐⠖⠼⠉")?;
    Ok(())
}

#[test]
fn bana_5_1() -> Result<()> {
    let expr = "<math><mi>x</mi><mo>+</mo><mi>y</mi><mo>=</mo><mn>6</mn></math>";
    test_from_braille("UEB", expr, "⠭⠐⠖⠽⠀⠐⠶⠀⠼⠋")?;
    Ok(())
}

#[test]
fn bana_5_2() -> Result<()> {
    let expr = "<math><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><msup><mi>y</mi><mn>2</mn></msup><mo>=</mo><mi>C</mi></math>";
    test_from_braille("UEB", expr, "⠭⠰⠔⠼⠃⠐⠖⠽⠔⠼⠃⠀⠐⠶⠀⠰⠠⠉")?;
    Ok(())
}

#[test]
fn bana_5_3() -> Result<()> {
    let expr = "<math><mfrac><mi>a</mi><mi>b</mi></mfrac><mo>+</mo><mfrac><mi>c</mi><mi>d</mi></mfrac></math>";
    test_from_braille("UEB", expr, "⠰⠰⠷⠁⠨⠌⠃⠾⠐⠖⠷⠉⠨⠌⠙⠾")?;
    Ok(())
}

#[test]
fn bana_5_4() -> Result<()> {
    let expr = "<math><msup><mi>a</mi><mi>n</mi></msup><mo>&#xD7;</mo><msup><mi>a</mi><mi>m</mi></msup><mo>=</mo> <msup><mi>a</mi><mrow><mi>n</mi><mo>+</mo><mi>m</mi></mrow></msup></math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠁⠔⠝⠐⠦⠁⠔⠍⠀⠐⠶⠀⠁⠔⠣⠝⠐⠖⠍⠜⠰⠄")?;
    Ok(())
}

#[test]
fn bana_5_5() -> Result<()> {
    let expr = "<math><msub><mi>log</mi><mi>x</mi></msub><mi>y</mi></math>";
    test_from_braille("UEB", expr, "⠰⠰⠇⠕⠛⠢⠭⠽")?;
    Ok(())
}

#[test]
fn bana_5a_1() -> Result<()> {
    let expr = "<math><msup><mn>100</mn><mo>&#xB0;</mo></msup><mi>F</mi></math>";
    test_from_braille("UEB", expr, "⠼⠁⠚⠚⠘⠚⠠⠋")?;
    Ok(())
}

#[test]
fn bana_5a_1_baseline() -> Result<()> {
    // Same braille as bana_5a_1; flat °+F is not recoverable (canonicalize merges
    // to ℉ unless ° is already a superscript on the number).
    let expr = "<math><msup><mn>100</mn><mo>&#xB0;</mo></msup><mi>F</mi></math>";
    test_from_braille("UEB", expr, "⠼⠁⠚⠚⠘⠚⠠⠋")?;
    Ok(())
}

#[test]
fn bana_5a_2() -> Result<()> {
    let expr = "<math><mn>25</mn><mo>&#xA0;</mo><msup><mi class='MathML-unit'>km</mi><mn>2</mn></msup></math>";
    test_from_braille("UEB", expr, "⠼⠃⠑⠀⠅⠍⠰⠔⠼⠃")?;
    Ok(())
}

#[test]
fn bana_5a_2_mtext() -> Result<()> {
    let expr = "<math><mn>25</mn><mo>&#xA0;</mo><msup><mtext class='MathML-unit'>km</mtext><mn>2</mn></msup></math>";
    test_from_braille("UEB", expr, "⠼⠃⠑⠀⠅⠍⠰⠔⠼⠃")?;
    Ok(())
}

#[test]
fn bana_5a_3() -> Result<()> {
    let expr = "<math><mn>6</mn><mo>&#xA0;</mo><mi class='MathML-unit'>m</mi><mo>&#xA0;</mo> <msup><mi class='MathML-unit'>s</mi><mrow><mo>-</mo><mn>1</mn></mrow></msup></math>";
    test_from_braille("UEB", expr, "⠼⠋⠀⠰⠍⠀⠰⠰⠎⠔⠣⠐⠤⠼⠁⠜")?;
    Ok(())
}

#[test]
fn bana_6_1() -> Result<()> {
    let expr = "<math><mi>x</mi><mo>+</mo><mi>y</mi><mo>=</mo><mi>z</mi> <mo>=</mo><msup><mi>t</mi><mn>2</mn></msup><mo>.</mo></math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠭⠐⠖⠽⠀⠐⠶⠀⠵⠀⠐⠶⠀⠞⠔⠼⠃⠲⠰⠄")?;
    Ok(())
}

#[test]
fn cap_1_6_1() -> Result<()> {
    // Same braille as cap_1_6_1_separate; capital word ABCD is ambiguous vs one <mi>.
    let expr = "<math><mi>A</mi><mi>B</mi><mi>C</mi><mi>D</mi></math>";
    test_from_braille("UEB", expr, "⠠⠠⠁⠃⠉⠙")?;
    Ok(())
}

#[test]
fn cap_1_6_1_separate() -> Result<()> {
    let expr = "<math> <mi mathvariant='normal'>A</mi> <mi mathvariant='normal'>B</mi> <mi mathvariant='normal'>C</mi> <mi mathvariant='normal'>D</mi></math>";
    test_from_braille("UEB", expr, "⠠⠠⠁⠃⠉⠙")?;
    Ok(())
}

#[test]
fn cap_1_6_2() -> Result<()> {
    let expr = "<math><mi>V</mi><mo>=</mo><mi>I</mi><mi>R</mi></math>";
    test_from_braille("UEB", expr, "⠰⠠⠧⠀⠐⠶⠀⠠⠠⠊⠗")?;
    Ok(())
}

#[test]
fn cap_1_6_4() -> Result<()> {
    let expr = "<math><mi>A</mi><msup><mi>B</mi><mn>2</mn></msup></math>";
    test_from_braille("UEB", expr, "⠠⠠⠁⠃⠰⠔⠼⠃")?;
    Ok(())
}

#[test]
fn grade1_1_7_1() -> Result<()> {
    let expr = "<math><mn>3</mn><mo>-</mo><mn>2</mn> <mfrac bevelled='true'><mn>1</mn><mn>2</mn></mfrac ><mo>=</mo></math>";
    test_from_braille("UEB", expr, "⠼⠉⠐⠤⠼⠃⠼⠁⠌⠃⠀⠐⠶")?;
    Ok(())
}

#[test]
fn grade1_1_7_2() -> Result<()> {
    let expr = "<math><mi>y</mi><mo>=</mo><mi>x</mi><mo>+</mo><mn>4</mn><mi>c</mi></math>";
    test_from_braille("UEB", expr, "⠰⠽⠀⠐⠶⠀⠭⠐⠖⠼⠙⠰⠉")?;
    Ok(())
}

#[test]
fn grade1_1_7_3_1() -> Result<()> {
    let expr = "<math> <mn>3</mn><mi>x</mi><mo>&#x2212;</mo><mn>4</mn><mi>y</mi><mo>+</mo> <msup><mi>y</mi><mn>2</mn></msup> <mo>=</mo> <msup><mi>x</mi><mn>2</mn></msup> </math>";
    test_from_braille("UEB", expr, "⠼⠉⠭⠐⠤⠼⠙⠽⠐⠖⠽⠔⠼⠃⠀⠐⠶⠀⠭⠰⠔⠼⠃")?;
    Ok(())
}

#[test]
fn grade1_1_7_3_2() -> Result<()> {
    let expr = "<math> <mfrac> <mrow><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><mn>2</mn><mi>x</mi></mrow> <mrow><mn>1</mn><mo>+</mo><msup><mi>x</mi><mn>2</mn></msup></mrow> </mfrac><mo>=</mo><mn>1</mn> </math>";
    test_from_braille("UEB", expr, "⠰⠰⠷⠭⠔⠼⠃⠐⠖⠼⠃⠭⠨⠌⠼⠁⠐⠖⠭⠔⠼⠃⠾⠀⠐⠶⠀⠼⠁")?;
    Ok(())
}

#[test]
fn grade1_1_7_4() -> Result<()> {
    let expr = "<math><msqrt> <mo>(</mo><mi>y</mi><mo>&#x2212;</mo><msup><mi>x</mi><mn>2</mn></msup><mo>)</mo> </msqrt></math>";
    test_from_braille("UEB", expr, "⠰⠰⠩⠐⠣⠽⠐⠤⠭⠔⠼⠃⠐⠜⠬")?;
    Ok(())
}

#[test]
fn number_2_1_2() -> Result<()> {
    let expr = "<math><mn>3,000</mn></math>";
    test_from_braille("UEB", expr, "⠼⠉⠂⠚⠚⠚")?;
    Ok(())
}

#[test]
fn number_2_1_3() -> Result<()> {
    let expr = "<math><mn>5 000 000</mn></math>";
    test_from_braille("UEB", expr, "⠼⠑⠐⠚⠚⠚⠐⠚⠚⠚")?;
    Ok(())
}

#[test]
fn number_2_2_1() -> Result<()> {
    let expr = "<math><mn>8.93</mn></math>";
    test_from_braille("UEB", expr, "⠼⠓⠲⠊⠉")?;
    Ok(())
}

#[test]
fn number_2_2_2() -> Result<()> {
    let expr = "<math><mn>0.7</mn></math>";
    test_from_braille("UEB", expr, "⠼⠚⠲⠛")?;
    Ok(())
}

#[test]
fn number_2_2_3() -> Result<()> {
    let expr = "<math><mn>.7</mn></math>";
    test_from_braille("UEB", expr, "⠼⠲⠛")?;
    Ok(())
}

#[test]
fn time_2_4_1() -> Result<()> {
    let expr = "<math><mn>5</mn><mo>:</mo><mn>30</mn><mo>&#xA0;</mo><mtext>pm</mtext></math>";
    test_from_braille("UEB", expr, "⠼⠑⠒⠼⠉⠚⠀⠏⠍")?;
    Ok(())
}

#[test]
fn time_2_4_1_mtext() -> Result<()> {
    // Flat mtext time is not recoverable; reverse emits structured 5:30.
    let expr = "<math><mn>5</mn><mo>:</mo><mn>30</mn></math>";
    test_from_braille("UEB", expr, "⠼⠑⠒⠼⠉⠚")?;
    Ok(())
}

#[test]
fn roman_numeral_2_6_1() -> Result<()> {
    let expr = "<math><mi mathvariant='normal'>I</mi><mo>,</mo> <mo>&#xA0;</mo><mi>II</mi> <mo>&#xA0;</mo><mtext>and</mtext><mo>&#xA0;</mo><mi mathvariant='normal'>V</mi></math>";
    test_from_braille("UEB", expr, "⠠⠊⠂⠀⠠⠠⠊⠊⠀⠯⠀⠰⠠⠧")?;
    Ok(())
}

#[test]
fn roman_numeral_2_6_2() -> Result<()> {
    let expr = "<math><mi mathvariant='normal'>i</mi><mo>,</mo> <mo>&#xA0;</mo><mi>vi</mi> <mo>&#xA0;</mo><mtext>and</mtext><mo>&#xA0;</mo><mi mathvariant='normal'>x</mi></math>";
    test_from_braille("UEB", expr, "⠊⠂⠀⠧⠊⠀⠯⠀⠰⠭")?;
    Ok(())
}

#[test]
fn roman_numeral_2_6_3() -> Result<()> {
    // Forward uses <mn>CD</mn>; reverse emits <mi>CD</mi> (roman packaging not recoverable).
    let expr = "<math><mi>CD</mi></math>";
    test_from_braille("UEB", expr, "⠰⠠⠠⠉⠙")?;
    Ok(())
}

#[test]
fn bold_2_7_1() -> Result<()> {
    // Forward packs mixed bold into one <mn>; reverse recovers 67 + bold word 845.
    let expr = "<math><mn>67</mn><mn mathvariant='bold'>845</mn></math>";
    test_from_braille("UEB", expr, "⠼⠋⠛⠘⠆⠼⠓⠙⠑")?;
    Ok(())
}

#[test]
fn bold_2_7_2() -> Result<()> {
    let expr = "<math><mn>67</mn><mn mathvariant='bold'>845</mn></math>";
    test_from_braille("UEB", expr, "⠼⠋⠛⠘⠂⠼⠓⠙⠑")?;
    Ok(())
}

#[test]
fn bold_2_7_3() -> Result<()> {
    let expr = "<math><mn>67</mn><mn mathvariant='bold'>84</mn><mn>5</mn></math>";
    test_from_braille("UEB", expr, "⠼⠋⠛⠘⠂⠼⠓⠙⠘⠄⠼⠑")?;
    Ok(())
}

#[test]
fn signs_2_10_2() -> Result<()> {
    let expr = "<math><mo>$</mo><mn>0.30</mn><mo>,</mo><mo>&#xA0;</mo> <mn>30</mn><mi mathvariant='normal'>c</mi><mo>&#xA0;</mo> <mtext>or</mtext><mo>&#xA0;</mo><mn>30</mn><mo>&#xA2;</mo></math>";
    test_from_braille("UEB", expr, "⠈⠎⠼⠚⠲⠉⠚⠂⠀⠼⠉⠚⠰⠉⠀⠕⠗⠀⠼⠉⠚⠈⠉")?;
    Ok(())
}

#[test]
fn signs_2_10_5() -> Result<()> {
    let expr = "<math><mn>1</mn><mo>&#xA0;</mo><mi>ft</mi><mo>&#xA0;</mo><mn>6</mn><mo>&#xA0;</mo><mi>in</mi> <mo>&#xA0;</mo><mtext>or</mtext><mo>&#xA0;</mo> <mn>1</mn><mo>&#x2032;</mo><mo>&#xA0;</mo><mn>6</mn><mo>&#x2032;</mo><mo>&#x2032;</mo></math>";
    test_from_braille("UEB", expr, "⠼⠁⠀⠋⠞⠀⠼⠋⠀⠔⠀⠕⠗⠀⠼⠁⠶⠀⠼⠋⠶⠶")?;
    Ok(())
}

#[test]
fn signs_2_10_8() -> Result<()> {
    // Spaces around "or" and flat ° are not recoverable; reverse uses msup(°,C/F).
    let expr = "<math><msup><mn>0</mn><mo>&#xB0;</mo></msup><mi>C</mi><mi>or</mi><msup><mn>32</mn><mo>&#xB0;</mo></msup><mi>F</mi></math>";
    test_from_braille("UEB", expr, "⠼⠚⠘⠚⠠⠉⠀⠕⠗⠀⠼⠉⠃⠘⠚⠠⠋")?;
    Ok(())
}

#[test]
fn signs_2_10_16() -> Result<()> {
    let expr = "<math><mn>1</mn><mo>&#xA0;</mo><mi mathvariant='normal'>&#xC5;</mi><mo>=</mo> <mfrac><mn>1</mn><mrow><mn>10</mn><mo>,</mo><mn>000</mn></mrow></mfrac><mo>&#xA0;</mo> <mi mathvariant='normal'>&#x3BC;</mi></math>";
    test_from_braille("UEB", expr, "⠼⠁⠀⠠⠘⠫⠁⠀⠐⠶⠀⠼⠁⠌⠁⠚⠂⠚⠚⠚⠀⠨⠍")?;
    Ok(())
}

#[test]
fn expr_3_1_1_spaces() -> Result<()> {
    let expr = "<math><mn>3</mn><mo>+</mo><mn>5</mn><mo>=</mo><mn>8</mn></math>";
    test_from_braille_prefs("UEB", vec![("UseSpacesAroundAllOperators", "true")], expr, "⠼⠉⠀⠐⠖⠀⠼⠑⠀⠐⠶⠀⠼⠓")?;
    Ok(())
}

#[test]
fn expr_3_1_2_spaces() -> Result<()> {
    let expr = "<math><mn>8</mn><mo>-</mo><mn>5</mn><mo>=</mo><mn>3</mn></math>";
    test_from_braille_prefs("UEB", vec![("UseSpacesAroundAllOperators", "true")], expr, "⠼⠓⠀⠐⠤⠀⠼⠑⠀⠐⠶⠀⠼⠉")?;
    Ok(())
}

#[test]
fn expr_3_1_1() -> Result<()> {
    let expr = "<math><mn>3</mn><mo>+</mo><mn>5</mn><mo>=</mo><mn>8</mn></math>";
    test_from_braille("UEB", expr, "⠼⠉⠐⠖⠼⠑⠀⠐⠶⠀⠼⠓")?;
    Ok(())
}

#[test]
fn expr_3_1_2() -> Result<()> {
    let expr = "<math><mn>8</mn><mo>-</mo><mn>5</mn><mo>=</mo><mn>3</mn></math>";
    test_from_braille("UEB", expr, "⠼⠓⠐⠤⠼⠑⠀⠐⠶⠀⠼⠉")?;
    Ok(())
}

#[test]
fn expr_3_1_3() -> Result<()> {
    let expr = "<math><mn>3</mn><mo>&#xD7;</mo><mn>5</mn><mo>=</mo><mn>5</mn><mo>&#xD7;</mo><mn>3</mn><mo>=</mo><mn>15</mn></math>";
    test_from_braille("UEB", expr, "⠼⠉⠐⠦⠼⠑⠀⠐⠶⠀⠼⠑⠐⠦⠼⠉⠀⠐⠶⠀⠼⠁⠑")?;
    Ok(())
}

#[test]
fn expr_3_1_6() -> Result<()> {
    let expr = "<math><mn>5</mn><mo>.</mo><mn>72</mn><mo>&#xA0;</mo><mtext>m</mtext><mo>&#xF7;</mo><mn>10</mn><mo>=</mo> <mn>57</mn><mo>.</mo><mn>2</mn><mo>&#xA0;</mo><mi>cm</mi></math>";
    test_from_braille("UEB", expr, "⠼⠑⠲⠛⠃⠀⠍⠐⠌⠼⠁⠚⠀⠐⠶⠀⠼⠑⠛⠲⠃⠀⠉⠍")?;
    Ok(())
}

#[test]
fn expr_3_1_7() -> Result<()> {
    let expr = "<math><mn>15</mn><mo>&#xB1;</mo><mn>0</mn><mo>.</mo><mn>5</mn></math>";
    test_from_braille("UEB", expr, "⠼⠁⠑⠸⠖⠼⠚⠲⠑")?;
    Ok(())
}

#[test]
fn expr_3_1_8() -> Result<()> {
    let expr = "<math><mi>Area</mi><mo>=</mo><mi>b</mi><mi>h</mi><mo>=</mo> <mn>5</mn><mo>&#xB7;</mo><mn>3</mn><mo>=</mo><mn>15</mn></math>";
    test_from_braille("UEB", expr, "⠠⠜⠑⠁⠀⠐⠶⠀⠃⠓⠀⠐⠶⠀⠼⠑⠐⠲⠼⠉⠀⠐⠶⠀⠼⠁⠑")?;
    Ok(())
}

#[test]
fn expr_3_1_9_wiris() -> Result<()> {
    let expr = "<math><mn>3</mn><mo>.</mo><mn>9</mn><mo>&#xD7;</mo><mn>4</mn><mo>.</mo><mn>1</mn><mo>&#x2243;</mo><mn>16</mn></math>";
    test_from_braille("UEB", expr, "⠼⠉⠲⠊⠐⠦⠼⠙⠲⠁⠀⠸⠔⠀⠼⠁⠋")?;
    Ok(())
}

#[test]
fn expr_3_1_9() -> Result<()> {
    let expr = "<math><mn>3.9</mn><mo>&#xD7;</mo><mn>4.1</mn><mo>&#x2243;</mo><mn>16</mn></math>";
    test_from_braille("UEB", expr, "⠼⠉⠲⠊⠐⠦⠼⠙⠲⠁⠀⠸⠔⠀⠼⠁⠋")?;
    Ok(())
}

#[test]
fn expr_3_1_10() -> Result<()> {
    let expr = "<math><mn>5</mn><mo>-</mo><mn>3</mn><mo>&#x2260;</mo><mn>3</mn><mo>-</mo><mn>5</mn></math>";
    test_from_braille("UEB", expr, "⠼⠑⠐⠤⠼⠉⠀⠐⠶⠈⠱⠀⠼⠉⠐⠤⠼⠑")?;
    Ok(())
}

#[test]
fn ratio_3_1_11() -> Result<()> {
    let expr = "<math><mn>1</mn><mo>:</mo><mn>200</mn></math>";
    test_from_braille("UEB", expr, "⠼⠁⠒⠼⠃⠚⠚")?;
    Ok(())
}

#[test]
fn ratio_3_1_12() -> Result<()> {
    let expr = "<math><mn>2</mn><mo>:</mo><mn>4</mn><mo>=</mo><mn>6</mn><mo>:</mo><mn>12</mn></math>";
    test_from_braille("UEB", expr, "⠼⠃⠒⠼⠙⠀⠐⠶⠀⠼⠋⠒⠼⠁⠃")?;
    Ok(())
}

#[test]
fn alg_3_2_1_1() -> Result<()> {
    let expr = "<math><mi>y</mi><mo>&#x221D;</mo><mi>x</mi></math>";
    test_from_braille("UEB", expr, "⠰⠽⠀⠸⠐⠶⠀⠰⠭")?;
    Ok(())
}

#[test]
fn alg_3_2_1_2() -> Result<()> {
    let expr = "<math><mi>y</mi><mo>=</mo><mi>k</mi><mi>x</mi></math>";
    test_from_braille("UEB", expr, "⠰⠽⠀⠐⠶⠀⠅⠭")?;
    Ok(())
}

#[test]
fn alg_3_2_2() -> Result<()> {
    let expr = "<math><mn>0</mn><mo>&#x2264;</mo><mi>&#x3B8;</mi> <mo>&#x2264;</mo><mn>2</mn><mi mathvariant='normal'>&#x3C0;</mi></math>";
    test_from_braille("UEB", expr, "⠼⠚⠀⠸⠈⠣⠀⠨⠹⠀⠸⠈⠣⠀⠼⠃⠨⠏")?;
    Ok(())
}

#[test]
fn alg_3_2_3() -> Result<()> {
    let expr = "<math><mi>y</mi><mo>=</mo><mi>x</mi><mo>+</mo><mn>4</mn></math>";
    test_from_braille("UEB", expr, "⠰⠽⠀⠐⠶⠀⠭⠐⠖⠼⠙")?;
    Ok(())
}

#[test]
fn alg_3_2_4() -> Result<()> {
    let expr = "<math><mn>2</mn><mi>y</mi><mo>=</mo><mn>2</mn><mi>c</mi><mo>-</mo><mn>4</mn></math>";
    test_from_braille("UEB", expr, "⠼⠃⠽⠀⠐⠶⠀⠼⠃⠰⠉⠐⠤⠼⠙")?;
    Ok(())
}

#[test]
fn alg_3_2_5() -> Result<()> {
    let expr = "<math><mi>d</mi><mo>+</mo><mi>a</mi><mi>b</mi><mo>=</mo><mi>a</mi><mi>c</mi></math>";
    test_from_braille("UEB", expr, "⠙⠐⠖⠁⠃⠀⠐⠶⠀⠰⠁⠉")?;
    Ok(())
}

#[test]
fn ratio_3_2_6() -> Result<()> {
    let expr = "<math><mi>x</mi><mo>:</mo><mi>y</mi></math>";
    test_from_braille("UEB", expr, "⠭⠰⠒⠽")?;
    Ok(())
}

#[test]
fn standing_alone_1() -> Result<()> {
    let expr = "<math><mo>(</mo><mi>n</mi><mo>=</mo><mn>7</mn><mo>)</mo></math>";
    test_from_braille("UEB", expr, "⠐⠣⠰⠝⠀⠐⠶⠀⠼⠛⠐⠜")?;
    Ok(())
}

#[test]
fn example_3_4_1() -> Result<()> {
    // mtext nbsp around "to" is not recoverable; reverse emits <mi>to</mi>.
    let expr = "<math><mo>-</mo><mn>4</mn><mi>to</mi><mo>+</mo><mn>5</mn></math>";
    test_from_braille("UEB", expr, "⠐⠤⠼⠙⠀⠞⠕⠀⠐⠖⠼⠑")?;
    Ok(())
}

#[test]
fn example_3_4_2() -> Result<()> {
    let expr = "<math> <msup> <mrow/> <mo>&#x2212;</mo></msup> <mn>2</mn> <mo>+</mo> <msup> <mrow/> <mo>&#x2212;</mo></msup> <mn>3</mn> </math>";
    test_from_braille("UEB", expr, "⠰⠔⠐⠤⠼⠃⠐⠖⠔⠐⠤⠼⠉")?;
    Ok(())
}

#[test]
fn omission_3_6_1() -> Result<()> {
    let expr = "<math><mn>3</mn><mo>+</mo><mn>7</mn><mo>=</mo><mo>―</mo></math>";
    test_from_braille("UEB", expr, "⠼⠉⠐⠖⠼⠛⠀⠐⠶⠀⠐⠠⠤")?;
    Ok(())
}

#[test]
fn omission_3_6_2() -> Result<()> {
    let expr = "<math><mn>3</mn><mo>+</mo><mn>7</mn><mo>=</mo><mi>_</mi></math>";
    test_from_braille("UEB", expr, "⠼⠉⠐⠖⠼⠛⠀⠐⠶⠀⠨⠤")?;
    Ok(())
}

#[test]
fn omission_3_6_3() -> Result<()> {
    let expr = "<math><mn>3</mn><mo>+</mo><mn>7</mn><mo>=</mo><mo>?</mo></math>";
    test_from_braille("UEB", expr, "⠼⠉⠐⠖⠼⠛⠀⠐⠶⠀⠰⠦")?;
    Ok(())
}

#[test]
fn omission_3_6_4() -> Result<()> {
    let expr = "<math><mn>3</mn><mo>&#x25A1;</mo><mn>7</mn><mo>=</mo><mn>10</mn></math>";
    test_from_braille("UEB", expr, "⠼⠉⠫⠼⠙⠱⠼⠛⠀⠐⠶⠀⠼⠁⠚")?;
    Ok(())
}

#[test]
fn omission_3_6_5() -> Result<()> {
    let expr = "<math><mn>3</mn><mo>&#xA0;</mo><mo>&#xA0;</mo><mn>7</mn><mo>=</mo><mn>10</mn></math>";
    test_from_braille("UEB", expr, "⠼⠉⠬⠼⠛⠀⠐⠶⠀⠼⠁⠚")?;
    Ok(())
}

#[test]
fn omission_3_6_6() -> Result<()> {
    let expr = "<math><mfrac><mn>9</mn><mn>12</mn></mfrac><mo>=</mo><mfrac><mn>3</mn><mrow/></mfrac></math>";
    test_from_braille("UEB", expr, "⠼⠊⠌⠁⠃⠀⠐⠶⠀⠰⠷⠼⠉⠨⠌⠬⠾")?;
    Ok(())
}

#[test]
fn omission_3_6_7() -> Result<()> {
    let expr = "<math><mrow><mn>5</mn><mo>=</mo><msqrt><mrow/></msqrt></mrow></math>";
    test_from_braille("UEB", expr, "⠼⠑⠀⠐⠶⠀⠰⠰⠩⠬⠬")?;
    Ok(())
}

#[test]
fn fraction_6_1_1() -> Result<()> {
    let expr = "<math><mfrac><mn>5</mn><mn>8</mn></mfrac></math>";
    test_from_braille("UEB", expr, "⠼⠑⠌⠓")?;
    Ok(())
}

#[test]
fn fraction_6_1_2() -> Result<()> {
    let expr = "<math><mfrac><mrow><mn>5</mn><mo>.</mo><mn>7</mn></mrow><mrow><mn>2</mn><mo>,</mo><mn>000</mn></mrow></mfrac></math>";
    test_from_braille("UEB", expr, "⠼⠑⠲⠛⠌⠃⠂⠚⠚⠚")?;
    Ok(())
}

#[test]
fn fraction_6_2_1() -> Result<()> {
    let expr = "<math><mn>2</mn><mfrac bevelled='true'><mn>1</mn><mn>2</mn></mfrac></math>";
    test_from_braille("UEB", expr, "⠼⠃⠼⠁⠌⠃")?;
    Ok(())
}

#[test]
fn fraction_6_2_2() -> Result<()> {
    let expr = "<math><mn>1750</mn> <mo>&#xA0;</mo><mi mathvariant='normal' class='MathML-Unit'>cm</mi><mo>=</mo> <mn>1</mn><mfrac bevelled='true'><mn>3</mn><mn>4</mn></mfrac> <mo>&#xA0;</mo><mi mathvariant='normal' class='MathML-Unit'>m</mi></math>";
    test_from_braille("UEB", expr, "⠼⠁⠛⠑⠚⠀⠉⠍⠀⠐⠶⠀⠼⠁⠼⠉⠌⠙⠀⠰⠍")?;
    Ok(())
}

#[test]
fn fraction_6_2_2_unicode_frac() -> Result<()> {
    // Forward uses U+00BE; reverse recovers mixed number + simple fraction.
    let expr = "<math><mn>1750</mn><mi>cm</mi><mo>=</mo><mn>1</mn><mfrac><mn>3</mn><mn>4</mn></mfrac><mi>m</mi></math>";
    test_from_braille("UEB", expr, "⠼⠁⠛⠑⠚⠀⠉⠍⠀⠐⠶⠀⠼⠁⠼⠉⠌⠙⠀⠰⠍")?;
    Ok(())
}

#[test]
fn fraction_6_3_1() -> Result<()> {
    let expr = "<math><mn>3</mn><mo>/</mo><mn>8</mn></math>";
    test_from_braille("UEB", expr, "⠼⠉⠸⠌⠼⠓")?;
    Ok(())
}

#[test]
fn fraction_6_4_1() -> Result<()> {
    let expr = "<math><mi>y</mi><mo>=</mo><mfrac><mi>x</mi><mn>2</mn></mfrac></math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠽⠀⠐⠶⠀⠷⠭⠨⠌⠼⠃⠾⠰⠄")?;
    Ok(())
}

#[test]
fn fraction_6_4_2() -> Result<()> {
    let expr = "<math><mfrac> <mrow><mn>2</mn><mfrac><mn>1</mn><mn>2</mn></mfrac></mrow> <mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow> </mfrac></math>";
    test_from_braille("UEB", expr, "⠰⠷⠼⠃⠼⠁⠌⠃⠨⠌⠭⠐⠖⠽⠾")?;
    Ok(())
}

#[test]
fn fraction_6_4_3() -> Result<()> {
    let expr = "<math><mfrac><mrow><mn>2</mn><mo>/</mo><mn>3</mn></mrow><mn>5</mn></mfrac></math>";
    test_from_braille("UEB", expr, "⠰⠷⠼⠃⠸⠌⠼⠉⠨⠌⠼⠑⠾")?;
    Ok(())
}

#[test]
fn fraction_6_4_4() -> Result<()> {
    let expr = "<math><mfrac> <mrow><mfrac><mi>x</mi><mn>2</mn></mfrac><mo>+</mo><mfrac><mi>y</mi><mn>3</mn></mfrac></mrow> <mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow> </mfrac></math>";
    test_from_braille("UEB", expr, "⠰⠰⠷⠷⠭⠨⠌⠼⠃⠾⠐⠖⠷⠽⠨⠌⠼⠉⠾⠨⠌⠭⠐⠖⠽⠾")?;
    Ok(())
}

#[test]
fn fraction_6_4_5() -> Result<()> {
    let expr = "<math><mfrac> <mrow><mfrac><mi>x</mi><mn>2</mn></mfrac><mo>+</mo><mfrac><mi>y</mi><mn>3</mn></mfrac></mrow> <mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow> </mfrac></math>";
    test_from_braille("UEB", expr, "⠰⠰⠷⠷⠭⠨⠌⠼⠃⠾⠐⠖⠷⠽⠨⠌⠼⠉⠾⠨⠌⠭⠐⠖⠽⠾")?;
    Ok(())
}

#[test]
fn fraction_6_4_6() -> Result<()> {
    let expr = "<math><mtext>speed</mtext><mo>=</mo><mfrac><mtext>distance</mtext><mtext>time</mtext></mfrac></math>";
    test_from_braille("UEB", expr, "⠎⠏⠑⠫⠀⠐⠶⠀⠰⠰⠷⠙⠊⠎⠞⠁⠝⠉⠑⠨⠌⠞⠊⠍⠑⠾")?;
    Ok(())
}

#[test]
fn msup_7_3_2() -> Result<()> {
    let expr = "<math><msup><mi>x</mi><mn>2</mn></msup><mi>y</mi></math>";
    test_from_braille("UEB", expr, "⠭⠰⠔⠼⠃⠽")?;
    Ok(())
}

#[test]
fn msup_7_3_3() -> Result<()> {
    let expr = "<math><msup><mi>x</mi><mrow><mn>2</mn><mi>y</mi></mrow></msup></math>";
    test_from_braille("UEB", expr, "⠰⠰⠭⠔⠣⠼⠃⠽⠜")?;
    Ok(())
}

#[test]
fn msup_7_3_4() -> Result<()> {
    let expr = "<math><msup><mi>x</mi><mi>y</mi></msup><mo>+</mo><mn>1</mn></math>";
    test_from_braille("UEB", expr, "⠭⠰⠔⠽⠐⠖⠼⠁")?;
    Ok(())
}

#[test]
fn msup_7_3_6() -> Result<()> {
    let expr = "<math><msup><mi>x</mi><mrow><mi>y</mi><mo>+</mo><mn>1</mn></mrow></msup><mo>+</mo><mn>3</mn></math>";
    test_from_braille("UEB", expr, "⠰⠰⠭⠔⠣⠽⠐⠖⠼⠁⠜⠐⠖⠼⠉")?;
    Ok(())
}

#[test]
fn msup_7_3_7() -> Result<()> {
    // Unicode vulgar ⅔ not recoverable; reverse emits mfrac 2/3.
    let expr = "<math><msup><mi>x</mi><mfrac><mn>2</mn><mn>3</mn></mfrac></msup></math>";
    test_from_braille("UEB", expr, "⠭⠰⠔⠼⠃⠌⠉")?;
    Ok(())
}

#[test]
fn msup_7_3_11() -> Result<()> {
    let expr = "<math><msup><mi>x</mi><mfrac><mi>a</mi><mi>b</mi></mfrac></msup><mi>y</mi><mo>=</mo><mi>x</mi></math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠭⠔⠷⠁⠨⠌⠃⠾⠽⠀⠐⠶⠀⠭⠰⠄")?;
    Ok(())
}

#[test]
fn msup_7_4_1() -> Result<()> {
    let expr = "<math><msup><mi>e</mi><msup><mi>x</mi><mn>2</mn></msup></msup></math>";
    test_from_braille("UEB", expr, "⠰⠰⠑⠔⠣⠭⠔⠼⠃⠜")?;
    Ok(())
}

#[test]
fn msup_7_4_2() -> Result<()> {
    let expr = "<math><msup><mi>e</mi><mrow><mo>(</mo><msup><mi>x</mi><mn>2</mn></msup><mo>)</mo></mrow></msup></math>";
    test_from_braille("UEB", expr, "⠰⠰⠑⠔⠐⠣⠭⠔⠼⠃⠐⠜")?;
    Ok(())
}

#[test]
fn msub_7_4_3() -> Result<()> {
    let expr = "<math><msub><mi>P</mi><msub><mi>x</mi><mi>i</mi></msub></msub></math>";
    test_from_braille("UEB", expr, "⠰⠰⠠⠏⠢⠣⠭⠢⠊⠜")?;
    Ok(())
}

#[test]
fn msup_7_5_1() -> Result<()> {
    let expr = "<math><mn>0</mn><mo>.</mo><mn>0045</mn><mo>=</mo> <mn>4</mn><mo>.</mo><mn>5</mn><mo>&#xD7;</mo><msup><mn>10</mn><mrow><mo>-</mo><mn>3</mn></mrow></msup> </math>";
    test_from_braille("UEB", expr, "⠼⠚⠲⠚⠚⠙⠑⠀⠐⠶⠀⠼⠙⠲⠑⠐⠦⠼⠁⠚⠔⠣⠐⠤⠼⠉⠜")?;
    Ok(())
}

#[test]
fn msup_7_5_3() -> Result<()> {
    let expr = "<math><msup><mi>a</mi><mrow><mo>-</mo><mn>2</mn><mi>b</mi></mrow></msup></math>";
    test_from_braille("UEB", expr, "⠰⠰⠁⠔⠣⠐⠤⠼⠃⠰⠃⠜")?;
    Ok(())
}

#[test]
fn msup_7_6_2() -> Result<()> {
    let expr = "<math><msup><mi mathvariant='normal'>H</mi><mo>+</mo></msup></math>";
    test_from_braille("UEB", expr, "⠠⠓⠰⠔⠐⠖")?;
    Ok(())
}

#[test]
fn msubsup_7_7_1() -> Result<()> {
    let expr = "<math><msubsup><mi>x</mi><mn>1</mn><mn>2</mn></msubsup><mo>=</mo><msubsup><mi>y</mi><mn>2</mn><mn>3</mn></msubsup></math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠭⠢⠼⠁⠔⠼⠃⠀⠐⠶⠀⠽⠢⠼⠃⠔⠼⠉⠰⠄")?;
    Ok(())
}

#[test]
fn msubsup_7_7_2() -> Result<()> {
    let expr = "<math><msub><msup><mi>x</mi><mn>2</mn></msup><mi>k</mi></msub></math>";
    test_from_braille("UEB", expr, "⠭⠰⠔⠼⠃⠢⠅")?;
    Ok(())
}

#[test]
fn pre_msubsup_7_8_1() -> Result<()> {
    let expr = "<math><mmultiscripts><mi>U</mi><mprescripts/><mn>92</mn><mn>238</mn></mmultiscripts></math>";
    test_from_braille("UEB", expr, "⠰⠢⠼⠊⠃⠔⠼⠃⠉⠓⠠⠥")?;
    Ok(())
}

#[test]
fn pre_sup_7_8_2() -> Result<()> {
    let expr = "<math><mmultiscripts><mn>2</mn><mprescripts/><none/><mo>-</mo></mmultiscripts> <mo>+</mo><mmultiscripts><mn>3</mn><mprescripts/><none/><mo>-</mo></mmultiscripts> <mo>=</mo><mmultiscripts><mn>5</mn><mprescripts/><none/><mo>-</mo></mmultiscripts> </math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠔⠐⠤⠼⠃⠐⠖⠔⠐⠤⠼⠉⠀⠐⠶⠀⠔⠐⠤⠼⠑⠰⠄")?;
    Ok(())
}

#[test]
fn sum_7_9_1() -> Result<()> {
    let expr = "<math><munderover><mo>&#x2211;</mo><mrow><mi>x</mi><mo>=</mo><mn>1</mn></mrow><mi>n</mi></munderover> <msubsup><mi>x</mi><mi>i</mi><mn>2</mn></msubsup></math>";
    test_from_braille("UEB", expr, "⠰⠰⠠⠨⠎⠨⠢⠣⠭⠐⠶⠼⠁⠜⠨⠔⠝⠭⠢⠊⠔⠼⠃")?;
    Ok(())
}

#[test]
fn lim_7_9_2() -> Result<()> {
    let expr = "<math><munder><mi>lim</mi><mrow><mi>x</mi><mo>&#x2192;</mo><mi>a</mi></mrow></munder> <mi>f</mi><mo>(</mo><mi>x</mi><mo>)</mo><mo>=</mo><mn>1</mn></math>";
    test_from_braille("UEB", expr, "⠰⠰⠇⠊⠍⠨⠢⠣⠭⠳⠕⠁⠜⠋⠐⠣⠭⠐⠜⠀⠐⠶⠀⠼⠁")?;
    Ok(())
}

#[test]
fn sqrt_8_1_1() -> Result<()> {
    let expr = "<math><msqrt><mn>9</mn></msqrt><mo>=</mo><mn>3</mn></math>";
    test_from_braille("UEB", expr, "⠰⠩⠼⠊⠬⠀⠐⠶⠀⠼⠉")?;
    Ok(())
}

#[test]
fn sqrt_8_1_2() -> Result<()> {
    let expr = "<math><mi>r</mi><mo>=</mo> <msqrt><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><msup><mi>y</mi><mn>2</mn></msup></msqrt></math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠗⠀⠐⠶⠀⠩⠭⠔⠼⠃⠐⠖⠽⠔⠼⠃⠬⠰⠄")?;
    Ok(())
}

#[test]
fn sqrt_8_1_3() -> Result<()> {
    let expr = "<math> <msqrt> <mfrac> <mrow><mn>783.2</mn><mo>&#xD7;</mo><mn>6.547</mn></mrow> <mn>0.4628</mn> </mfrac> </msqrt> </math>";
    test_from_braille("UEB", expr, "⠰⠰⠩⠷⠼⠛⠓⠉⠲⠃⠐⠦⠼⠋⠲⠑⠙⠛⠨⠌⠼⠚⠲⠙⠋⠃⠓⠾⠬")?;
    Ok(())
}

#[test]
fn sqrt_8_1_4() -> Result<()> {
    let expr = "<math> <mi>x</mi> <mo>=</mo> <mfrac> <mrow> <mo>&#x2212;</mo><mi>b</mi><mo>&#x00B1;</mo> <msqrt> <msup><mi>b</mi> <mn>2</mn></msup> <mo>&#x2212;</mo><mn>4</mn><mi>a</mi><mi>c</mi> </msqrt> </mrow> <mrow><mn>2</mn><mi>a</mi></mrow> </mfrac> </math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠭⠀⠐⠶⠀⠷⠐⠤⠃⠸⠖⠩⠃⠔⠼⠃⠐⠤⠼⠙⠰⠁⠉⠬⠨⠌⠼⠃⠰⠁⠾⠰⠄")?;
    Ok(())
}

#[test]
fn root_8_2_1() -> Result<()> {
    let expr = "<math><mroot><mn>8</mn><mn>3</mn></mroot><mo>=</mo><mn>2</mn></math>";
    test_from_braille("UEB", expr, "⠰⠰⠩⠔⠼⠉⠼⠓⠬⠀⠐⠶⠀⠼⠃")?;
    Ok(())
}

#[test]
fn root_8_2_2() -> Result<()> {
    let expr = "<math><mi>q</mi><mo>=</mo> <mroot><mrow> <msup><mi>x</mi><mn>3</mn></msup><mo>+</mo> <msup><mi>y</mi><mn>3</mn></msup><mo>+</mo> <msup><mi>z</mi><mn>3</mn></msup> </mrow><mn>3</mn></mroot></math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠟⠀⠐⠶⠀⠩⠔⠼⠉⠭⠔⠼⠉⠐⠖⠽⠔⠼⠉⠐⠖⠵⠔⠼⠉⠬⠰⠄")?;
    Ok(())
}

#[test]
fn root_8_2_3() -> Result<()> {
    let expr = "<math><mroot><mrow><mi>x</mi><mi>y</mi></mrow><mrow><mi>m</mi><mi>n</mi></mrow></mroot></math>";
    test_from_braille("UEB", expr, "⠰⠰⠩⠔⠣⠍⠝⠜⠭⠽⠬")?;
    Ok(())
}

#[test]
fn root_8_2_4() -> Result<()> {
    let expr = "<math> <msup><mn>81</mn><mfrac><mn>3</mn><mn>4</mn></mfrac></msup> <mo>=</mo> <msup><mrow><mo>(</mo><mroot><mn>81</mn><mn>4</mn></mroot><mo>)</mo></mrow><mn>3</mn></msup><mo>=</mo> <msup><mrow><mo>(</mo><msqrt><msqrt><mn>81</mn></msqrt></msqrt><mo>)</mo></mrow><mn>3</mn></msup><mo>=</mo> <msup><mrow><mo>(</mo><msqrt><mn>9</mn></msqrt><mo>)</mo></mrow><mn>3</mn></msup> <mo>=</mo> <msup><mn>3</mn><mn>3</mn></msup> <mo>=</mo> <mn>27</mn> </math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠼⠓⠁⠔⠼⠉⠌⠙⠀⠐⠶⠀⠐⠣⠩⠔⠼⠙⠼⠓⠁⠬⠐⠜⠔⠼⠉⠀⠐⠶⠀⠐⠣⠩⠩⠼⠓⠁⠬⠬⠐⠜⠔⠼⠉⠀⠐⠶⠀⠐⠣⠩⠼⠊⠬⠐⠜⠔⠼⠉⠀⠐⠶⠀⠼⠉⠔⠼⠉⠀⠐⠶⠀⠼⠃⠛⠰⠄")?;
    Ok(())
}

#[test]
fn root_letter_base() -> Result<()> {
    let expr = "<math><mroot><mi>b</mi><mn>3</mn></mroot><mroot><mi>x</mi><mn>3</mn></mroot></math>";
    test_from_braille("UEB", expr, "⠰⠰⠩⠔⠼⠉⠰⠃⠬⠩⠔⠼⠉⠭⠬")?;
    Ok(())
}

#[test]
fn spacing_9_3_1_1() -> Result<()> {
    let expr = "<math> <mi>Sin</mi><mo>&#x2061;</mo> <mn>30</mn> </math>";
    test_from_braille("UEB", expr, "⠠⠎⠔⠼⠉⠚")?;
    Ok(())
}

#[test]
fn spacing_9_3_1_2() -> Result<()> {
    let expr = "<math><mn>3</mn><mi>tan</mi><mn>45</mn><mo>&#xB0;</mo></math>";
    test_from_braille("UEB", expr, "⠼⠉⠞⠁⠝⠼⠙⠑⠘⠚")?;
    Ok(())
}

#[test]
fn spacing_9_3_1_3() -> Result<()> {
    let expr = "<math><mn>4</mn><mi>cos</mi><mn>5</mn><mi>x</mi></math>";
    test_from_braille("UEB", expr, "⠼⠙⠰⠉⠕⠎⠼⠑⠭")?;
    Ok(())
}

#[test]
fn spacing_9_3_2_1() -> Result<()> {
    let expr = "<math><mi>log</mi><mi>y</mi></math>";
    test_from_braille("UEB", expr, "⠇⠕⠛⠀⠰⠽")?;
    Ok(())
}

#[test]
fn spacing_9_3_2_2() -> Result<()> {
    let expr = "<math><mi>sin</mi><mi>&#x3B8;</mi></math>";
    test_from_braille("UEB", expr, "⠎⠔⠨⠹")?;
    Ok(())
}

#[test]
fn spacing_9_3_2_3() -> Result<()> {
    let expr = "<math><mi>Sec</mi><mi>A</mi></math>";
    test_from_braille("UEB", expr, "⠠⠎⠑⠉⠠⠁")?;
    Ok(())
}

#[test]
fn spacing_9_3_2_4() -> Result<()> {
    let expr = "<math><mi>log</mi><mo>(</mo><mi>x</mi><mo>+</mo><mi>y</mi><mo>)</mo></math>";
    test_from_braille("UEB", expr, "⠇⠕⠛⠐⠣⠭⠐⠖⠽⠐⠜")?;
    Ok(())
}

#[test]
fn spacing_9_3_2_5() -> Result<()> {
    let expr = "<math><mi>Lim</mi><mfrac><mi>x</mi><mn>2</mn></mfrac></math>";
    test_from_braille("UEB", expr, "⠰⠰⠠⠇⠊⠍⠷⠭⠨⠌⠼⠃⠾")?;
    Ok(())
}

#[test]
fn spacing_9_3_3_1() -> Result<()> {
    let expr = "<math><mi>x</mi><mi>sin</mi><mn>60</mn></math>";
    test_from_braille("UEB", expr, "⠰⠭⠀⠎⠔⠼⠋⠚")?;
    Ok(())
}

#[test]
fn spacing_9_3_3_2() -> Result<()> {
    let expr = "<math><mi>x</mi><mrow><mi>Sin</mi><mo>&#x2061;</mo><mn>60</mn></mrow></math>";
    test_from_braille("UEB", expr, "⠭⠠⠎⠔⠼⠋⠚")?;
    Ok(())
}

#[test]
fn spacing_9_3_3_3() -> Result<()> {
    let expr = "<math><mi>X</mi><mi>log</mi><mi>y</mi></math>";
    test_from_braille("UEB", expr, "⠰⠠⠭⠀⠇⠕⠛⠀⠰⠽")?;
    Ok(())
}

#[test]
fn spacing_9_3_3_4() -> Result<()> {
    let expr = "<math><mi>x</mi><mi>Log</mi><mi>y</mi></math>";
    test_from_braille("UEB", expr, "⠭⠠⠇⠕⠛⠀⠰⠽")?;
    Ok(())
}

#[test]
fn spacing_9_3_3_5() -> Result<()> {
    let expr = "<math> <mi>sin</mi><mo>&#x2061;</mo><mrow><mo>(</mo><mi>A</mi><mo>+</mo><mi>B</mi><mo>)</mo> </mrow> <mo>=</mo><mi>sin</mi><mo>&#x2061;</mo><mi>A</mi><mi>cos</mi><mo>&#x2061;</mo> <mi>B</mi> <mo>+</mo><mi>cos</mi><mo>&#x2061;</mo><mi>A</mi><mi>sin</mi><mo>&#x2061;</mo><mi>B</mi></math>";
    test_from_braille("UEB", expr, "⠎⠔⠐⠣⠠⠁⠐⠖⠠⠃⠐⠜⠀⠐⠶⠀⠎⠔⠠⠁⠀⠉⠕⠎⠠⠃⠐⠖⠉⠕⠎⠠⠁⠀⠎⠔⠠⠃")?;
    Ok(())
}

#[test]
fn spacing_9_3_3_6() -> Result<()> {
    let expr = "<math><mi>sin</mi><mn>2</mn><mi>&#x3B2;</mi><mo>=</mo> <mn>2</mn><mi>sin</mi><mi>&#x3B2;</mi><mi>cos</mi><mi>&#x3B2;</mi></math>";
    test_from_braille("UEB", expr, "⠎⠔⠼⠃⠨⠃⠀⠐⠶⠀⠼⠃⠎⠊⠝⠨⠃⠉⠕⠎⠨⠃")?;
    Ok(())
}

#[test]
fn text_9_7_1_mtext() -> Result<()> {
    let expr = "<math><mtext>Pr</mtext><mo>(</mo><mi>A</mi><mo>&#xA0;</mo><mtext>and</mtext><mo>&#xA0;</mo><mi>B</mi><mo>)</mo><mo>=</mo> <mtext>Pr</mtext><mi>A</mi><mo>+</mo><mtext>Pr</mtext><mi>B</mi></math>";
    test_from_braille("UEB", expr, "⠠⠏⠗⠐⠣⠠⠁⠀⠯⠀⠰⠠⠃⠐⠜⠀⠐⠶⠀⠠⠏⠗⠠⠁⠐⠖⠠⠏⠗⠠⠃")?;
    Ok(())
}

#[test]
fn text_9_7_1() -> Result<()> {
    let expr = "<math><mi>Pr</mi><mo>(</mo><mi>A</mi><mo>&#xA0;</mo><mi>and</mi><mo>&#xA0;</mo><mi>B</mi><mo>)</mo><mo>=</mo> <mi>Pr</mi><mi>A</mi><mo>+</mo><mi>Pr</mi><mi>B</mi></math>";
    test_from_braille("UEB", expr, "⠠⠏⠗⠐⠣⠠⠁⠀⠯⠀⠰⠠⠃⠐⠜⠀⠐⠶⠀⠠⠏⠗⠠⠁⠐⠖⠠⠏⠗⠠⠃")?;
    Ok(())
}

#[test]
fn stat_9_7_2() -> Result<()> {
    let expr = "<math><mi>Exp</mi><mo>(</mo><mi>R</mi><mo>)</mo><mo>=</mo> <mfrac><mi>n</mi><mn>2</mn></mfrac><mo>+</mo><mn>1</mn></math>";
    test_from_braille("UEB", expr, "⠠⠑⠭⠏⠐⠣⠠⠗⠐⠜⠀⠐⠶⠀⠰⠰⠷⠝⠨⠌⠼⠃⠾⠐⠖⠼⠁")?;
    Ok(())
}

#[test]
fn set_10_1() -> Result<()> {
    let expr = "<math><mi>A</mi><mo>=</mo> <mfenced open='{' close='}'> <mrow><mn>1</mn><mo>,</mo><mn>2</mn><mo>,</mo><mn>3</mn><mo>,</mo><mn>4</mn></mrow> </mfenced></math>";
    test_from_braille("UEB", expr, "⠠⠁⠀⠐⠶⠀⠸⠣⠼⠁⠂⠀⠼⠃⠂⠀⠼⠉⠂⠀⠼⠙⠸⠜")?;
    Ok(())
}

#[test]
fn set_10_3() -> Result<()> {
    let expr = "<math><mn>3</mn><mo>&#x2208;</mo><mi>A</mi><mo>&#x2229;</mo><mi>B</mi></math>";
    test_from_braille("UEB", expr, "⠼⠉⠀⠘⠑⠀⠠⠁⠨⠦⠠⠃")?;
    Ok(())
}

#[test]
fn set_10_4() -> Result<()> {
    let expr = "<math><mi>A</mi><mo>&#x2229;</mo><mi>B</mi><mo>&#x2282;</mo><mi>A</mi><mo>&#x222A;</mo><mi>B</mi></math>";
    test_from_braille("UEB", expr, "⠠⠁⠨⠦⠠⠃⠀⠘⠣⠀⠠⠁⠨⠖⠠⠃")?;
    Ok(())
}

#[test]
fn set_10_5() -> Result<()> {
    let expr = "<math><msup><mi>A</mi><mo>'</mo></msup><mo>∪</mo><msup><mi>B</mi><mo>'</mo></msup><mo>=</mo> <msup><mrow><mo>(</mo><mi>A</mi><mo>∩</mo><mi>B</mi><mo>)</mo></mrow><mo>'</mo></msup></math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠠⠁⠶⠨⠖⠠⠃⠶⠀⠐⠶⠀⠐⠣⠠⠁⠨⠦⠠⠃⠐⠜⠶⠰⠄")?;
    Ok(())
}

#[test]
fn set_10_6() -> Result<()> {
    let expr = "<math><mo>[</mo><mo>(</mo><mi>p</mi><mo>&#x2228;</mo><mi>q</mi><mo>)</mo><mo>&#x2227;</mo><mo>&#xAC;</mo><mi>p</mi><mo>]</mo> <mo>⊢</mo><mi>q</mi></math>";
    test_from_braille("UEB", expr, "⠨⠣⠐⠣⠏⠈⠖⠟⠐⠜⠈⠦⠈⠹⠏⠨⠜⠀⠸⠒⠀⠰⠟")?;
    Ok(())
}

#[test]
fn example_11_5_1_2() -> Result<()> {
    // Juxtaposed d y / d x recovers as dy/dx identifiers.
    let expr = "<math><mfrac><mi>dy</mi><mi>dx</mi></mfrac></math>";
    test_from_braille("UEB", expr, "⠰⠰⠷⠙⠽⠨⠌⠙⠭⠾")?;
    Ok(())
}

#[test]
fn example_11_5_1_3() -> Result<()> {
    let expr = "<math><mi>f</mi><mo>'</mo><mo>(</mo><mi>x</mi><mo>)</mo></math>";
    test_from_braille("UEB", expr, "⠋⠰⠶⠐⠣⠭⠐⠜")?;
    Ok(())
}

#[test]
fn example_11_5_1_4() -> Result<()> {
    let expr = "<math><mfrac><mrow><mo>&#x2202;</mo><mi>y</mi></mrow><mrow><mo>&#x2202;</mo><mi>x</mi></mrow></mfrac></math>";
    test_from_braille("UEB", expr, "⠰⠰⠷⠈⠙⠽⠨⠌⠈⠙⠭⠾")?;
    Ok(())
}

#[test]
fn example_11_5_2() -> Result<()> {
    // Evaluation bar / dx packaging differs from forward mfenced form.
    let expr = "<math><mrow><msubsup><mo>&#x222B;</mo><mn>2</mn><mn>3</mn></msubsup><mrow><mo>(</mo><mrow><mn>2</mn><mi>x</mi><mo>+</mo><mn>1</mn></mrow><mo>)</mo></mrow><mi>dx</mi><mo>=</mo><msubsup><mrow><mo>[</mo><mrow><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><mi>x</mi></mrow><mo>]</mo></mrow><mn>2</mn><mn>3</mn></msubsup><mo>=</mo><mrow><mo>(</mo><mrow><msup><mn>3</mn><mn>2</mn></msup><mo>+</mo><mn>3</mn></mrow><mo>)</mo></mrow><mo>&#x2212;</mo><mrow><mo>(</mo><mrow><msup><mn>2</mn><mn>2</mn></msup><mo>+</mo><mn>2</mn></mrow><mo>)</mo></mrow><mo>=</mo><mn>12</mn><mo>&#x2212;</mo><mn>6</mn><mo>=</mo><mn>6</mn></mrow></math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠮⠢⠼⠃⠔⠼⠉⠐⠣⠼⠃⠭⠐⠖⠼⠁⠐⠜⠙⠭⠀⠐⠶⠀⠨⠣⠭⠔⠼⠃⠐⠖⠭⠨⠜⠢⠼⠃⠔⠼⠉⠀⠐⠶⠀⠐⠣⠼⠉⠔⠼⠃⠐⠖⠼⠉⠐⠜⠐⠤⠐⠣⠼⠃⠔⠼⠃⠐⠖⠼⠃⠐⠜⠀⠐⠶⠀⠼⠁⠃⠐⠤⠼⠋⠀⠐⠶⠀⠼⠋⠰⠄")?;
    Ok(())
}

#[test]
fn example_11_5_3() -> Result<()> {
    // Combinatorics packaging: empty-base n-sup + C_r; paren sizes not recoverable.
    let expr = "<math><mrow><mrow><msup><mrow></mrow><mi>n</mi></msup><msub><mi>C</mi><mi>r</mi></msub></mrow><mo>=</mo><mrow><mo>(</mo><mfrac linethickness=\"0\"><mi>n</mi><mi>r</mi></mfrac><mo>)</mo></mrow><mo>=</mo><mfrac><mrow><mi>n</mi><mo>!</mo></mrow><mrow><mi>r</mi><mo>!</mo><mrow><mo>(</mo><mrow><mi>n</mi><mo>&#x2212;</mo><mi>r</mi></mrow><mo>)</mo></mrow><mo>!</mo></mrow></mfrac></mrow></math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠔⠝⠠⠉⠢⠗⠀⠐⠶⠀⠐⠣⠝⠰⠻⠗⠐⠜⠀⠐⠶⠀⠷⠝⠖⠨⠌⠗⠖⠐⠣⠝⠐⠤⠗⠐⠜⠖⠾⠰⠄")?;
    Ok(())
}

#[test]
fn example_11_5_4() -> Result<()> {
    // Spacing around ∗ / ∘ not recoverable as separate factors.
    let expr = "<math><mrow><mi>a</mi><mo>&#x2217;</mo><mrow><mo>(</mo><mrow><mi>b</mi><mo>&#x25E6;</mo><mi>c</mi></mrow><mo>)</mo></mrow><mo>=</mo><mrow><mo>(</mo><mrow><mi>a</mi><mo>&#x2217;</mo><mi>b</mi></mrow><mo>)</mo></mrow><mo>&#x25E6;</mo><mrow><mo>(</mo><mrow><mi>a</mi><mo>&#x2217;</mo><mi>c</mi></mrow><mo>)</mo></mrow></mrow></math>";
    test_from_braille("UEB", expr, "⠁⠐⠔⠐⠣⠃⠐⠴⠉⠐⠜⠀⠐⠶⠀⠐⠣⠁⠐⠔⠃⠐⠜⠐⠴⠐⠣⠁⠐⠔⠉⠐⠜")?;
    Ok(())
}

#[test]
fn example_11_5_5_2() -> Result<()> {
    let expr = "<math> <msup> <mi>f</mi> <mrow> <mo>&#x2212;</mo> <mn>1</mn> </mrow> </msup> <mo>:</mo> <mi>Y</mi> <mo>&#x2192;</mo> <mi>X</mi> </math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠋⠔⠣⠐⠤⠼⠁⠜⠒⠀⠠⠽⠀⠳⠕⠀⠠⠭⠰⠄")?;
    Ok(())
}

#[test]
fn example_11_5_5_3() -> Result<()> {
    let expr = "<math> <mi mathvariant='normal'>&#x2200;</mi> <mi>y</mi> <mo>&#x2208;</mo> <mi>Y</mi> <mstyle scriptlevel='0'> <mspace width='0.278em'></mspace> </mstyle> <mi mathvariant='normal'>&#x2203;</mi> <mi>x</mi> <mo>&#x2208;</mo> <mi>X</mi> </math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠘⠁⠽⠀⠘⠑⠀⠠⠽⠀⠘⠢⠭⠀⠘⠑⠀⠠⠭⠰⠄")?;
    Ok(())
}

#[test]
fn example_11_5_6() -> Result<()> {
    let expr = "<math> <mo>{</mo> <mo>(</mo> <mi>x</mi> <mo>,</mo> <mi>y</mi> <mo>)</mo> <mo>|</mo> <mi>x</mi> <mo>+</mo> <mi>y</mi> <mo>=</mo> <mn>6</mn> return Ok(()); <mo>}</mo> </math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠸⠣⠐⠣⠭⠂⠀⠽⠐⠜⠀⠸⠳⠀⠭⠐⠖⠽⠀⠐⠶⠀⠼⠋⠸⠜⠰⠄")?;
    Ok(())
}

#[test]
fn example_11_6_math_variant() -> Result<()> {
    let expr = "<math><mi mathvariant='fraktur'>R</mi></math>";
    test_from_braille("UEB", expr, "⠈⠆⠰⠠⠗")?;
    Ok(())
}

#[test]
fn example_11_6() -> Result<()> {
    let expr = "<math><mi>ℜ</mi></math>";
    test_from_braille("UEB", expr, "⠈⠆⠰⠠⠗")?;
    Ok(())
}

#[test]
fn bar_over_12_1_1() -> Result<()> {
    let expr = "<math><mover><mi>x</mi><mo>_</mo></mover><mo>=</mo> <mfrac><mrow><mn>10</mn><mo>+</mo><mn>11</mn><mo>+</mo><mn>12</mn></mrow><mn>3</mn></mfrac></math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠭⠱⠀⠐⠶⠀⠷⠼⠁⠚⠐⠖⠼⠁⠁⠐⠖⠼⠁⠃⠨⠌⠼⠉⠾⠰⠄")?;
    Ok(())
}

#[test]
fn bar_under_12_1_2() -> Result<()> {
    let expr = "<math><munder><mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow><mo>_</mo></munder></math>";
    test_from_braille("UEB", expr, "⠰⠰⠣⠭⠐⠖⠽⠜⠠⠱")?;
    Ok(())
}

#[test]
fn bar_menclose_12_1_2() -> Result<()> {
    // menclose bottom is not recoverable from braille; reverse emits munder.
    let expr = "<math><munder><mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow><mo>_</mo></munder></math>";
    test_from_braille("UEB", expr, "⠰⠰⠣⠭⠐⠖⠽⠜⠠⠱")?;
    Ok(())
}

#[test]
fn dot_12_1_4() -> Result<()> {
    // Dot-above braille is ambiguous among '.', '·', '˙'; reverse prefers ˙.
    let expr = "<math><mn>0</mn><mo>.</mo><mover><mn>3</mn><mo>&#x2D9;</mo></mover></math>";
    test_from_braille("UEB", expr, "⠼⠚⠲⠣⠼⠉⠜⠘⠲")?;
    Ok(())
}

#[test]
fn dot_12_1_5() -> Result<()> {
    let expr = "<math><mn>0</mn><mo>.</mo><mn>56</mn><mover><mn>1</mn><mo>&#x2D9;</mo></mover> <mn>2</mn><mover><mn>3</mn><mo>&#x2D9;</mo></mover></math>";
    test_from_braille("UEB", expr, "⠼⠚⠲⠑⠋⠣⠼⠁⠜⠘⠲⠼⠃⠣⠼⠉⠜⠘⠲")?;
    Ok(())
}

#[test]
fn dot_12_1_6_single() -> Result<()> {
    let expr = "<math><mover><mi>x</mi><mo>&#x2D9;</mo></mover></math>";
    test_from_braille("UEB", expr, "⠭⠘⠲")?;
    Ok(())
}

#[test]
fn dot_12_1_6_double() -> Result<()> {
    let expr = "<math><mover><mi>x</mi><mo>&#xA8;</mo></mover></math>";
    test_from_braille("UEB", expr, "⠰⠰⠭⠨⠔⠣⠲⠲⠜")?;
    Ok(())
}

#[test]
fn hat_12_1_7() -> Result<()> {
    let expr = "<math><mi>A</mi><mover><mi>B</mi><mo>^</mo></mover><mi>C</mi></math>";
    test_from_braille("UEB", expr, "⠠⠁⠠⠃⠰⠐⠱⠠⠉")?;
    Ok(())
}

#[test]
fn arrow_over_12() -> Result<()> {
    let expr = "<math><mover><mi>x</mi><mo>→</mo></mover></math>";
    test_from_braille("UEB", expr, "⠭⠰⠘⠱")?;
    Ok(())
}

#[test]
fn arrow_under_12() -> Result<()> {
    let expr = "<math><munder><mi>x</mi><mo>→</mo></munder></math>";
    test_from_braille("UEB", expr, "⠭⠰⠠⠘⠱")?;
    Ok(())
}

#[test]
fn bar_12_2_1() -> Result<()> {
    let expr = "<math><msup><mi>x</mi><mover><mi>y</mi><mo>&#xAF;</mo></mover></msup></math>";
    test_from_braille("UEB", expr, "⠰⠰⠭⠔⠣⠽⠱⠜")?;
    Ok(())
}

#[test]
fn bar_12_2_2() -> Result<()> {
    let expr = "<math><mover><msup><mi>x</mi><mi>y</mi></msup><mo>&#xAF;</mo></mover></math>";
    test_from_braille("UEB", expr, "⠰⠰⠣⠭⠔⠽⠜⠱")?;
    Ok(())
}

#[test]
fn shape_14_1_1_1() -> Result<()> {
    // Capital word ABC after a shape is ambiguous; reverse emits single letters.
    let expr = "<math><mo>&#x25B3;</mo><mi>A</mi><mi>B</mi><mi>C</mi></math>";
    test_from_braille("UEB", expr, "⠰⠫⠼⠉⠀⠠⠠⠁⠃⠉")?;
    Ok(())
}

#[test]
fn shape_14_1_2_1() -> Result<()> {
    let expr = "<math><mo>&#x25B3;</mo><mtext>ABC</mtext></math>";
    test_from_braille("UEB", expr, "⠰⠫⠼⠉⠱⠠⠠⠁⠃⠉")?;
    Ok(())
}

#[test]
fn shape_14_1_2_2() -> Result<()> {
    // Forward source MathML was corrupted; reverse recovers the shape list.
    let expr = "<math><mo>{</mo><mo>&#x25A1;</mo><mo>,</mo><mo>&#x25CD;</mo><mo>,</mo><mo>&#x25B2;</mo><mo>,</mo><mo>&#x25A7;</mo><mo>&#x2026;</mo><mo>}</mo></math>";
    test_from_braille("UEB", expr, "⠸⠣⠰⠫⠼⠙⠱⠂⠀⠨⠫⠿⠱⠂⠀⠸⠫⠼⠉⠱⠂⠀⠨⠫⠼⠙⠀⠲⠲⠲⠸⠜")?;
    Ok(())
}

#[test]
fn binomial_14_3_3_2() -> Result<()> {
    let expr = "<math><mfenced><mfrac linethickness='0'><mi>n</mi><mi>r</mi></mfrac></mfenced></math>";
    test_from_braille("UEB", expr, "⠐⠣⠝⠰⠻⠗⠐⠜")?;
    Ok(())
}

#[test]
fn binomial_14_3_3_2_mtable() -> Result<()> {
    // Forward MathML uses mtable+intent; reverse recovers only parenthesized linethickness=0 mfrac.
    let expr = "<math><mrow><mo>(</mo><mfrac linethickness=\"0\"><mi>n</mi><mi>r</mi></mfrac><mo>)</mo></mrow></math>";
    test_from_braille("UEB", expr, "⠐⠣⠝⠰⠻⠗⠐⠜")?;
    Ok(())
}

#[test]
fn matrix_15_2_1() -> Result<()> {
    // Parallel to braille::UEB::iceb::matrix_15_2_1 (I = identity matrix).
    let expr = r#"<math><mi>I</mi><mo>=</mo>
       <mrow><mo>(</mo><mtable>
          <mtr><mtd><mn>1</mn></mtd><mtd><mn>0</mn></mtd></mtr>
          <mtr><mtd><mn>0</mn></mtd><mtd><mn>1</mn></mtd></mtr>
        </mtable><mo>)</mo>
      </mrow></math>"#;
    test_from_braille("UEB", expr, "⠠⠊⠀⠐⠶⠀⠠⠐⠣⠼⠁⠀⠼⠚⠠⠐⠜⠸⠀⠠⠐⠣⠼⠚⠀⠼⠁⠠⠐⠜")?;
    Ok(())
}

#[test]
fn matrix_15_2_2() -> Result<()> {
    // Parallel to braille::UEB::iceb::matrix_15_2_2 (matrix multiplication).
    let expr = r#"<math>
      <mrow><mo>[</mo><mtable>
        <mtr><mtd><mn>1</mn></mtd><mtd><mn>2</mn></mtd><mtd><mn>3</mn></mtd></mtr>
        <mtr><mtd><mn>4</mn></mtd><mtd><mn>5</mn></mtd><mtd><mn>6</mn></mtd></mtr>
      </mtable><mo>]</mo></mrow>
      <mrow><mo>[</mo><mtable>
        <mtr><mtd><mn>1</mn></mtd><mtd><mn>2</mn></mtd></mtr>
        <mtr><mtd><mo>-</mo><mn>3</mn></mtd><mtd><mn>4</mn></mtd></mtr>
        <mtr><mtd><mn>5</mn></mtd><mtd><mo>-</mo><mn>6</mn></mtd></mtr>
      </mtable><mo>]</mo></mrow>
    </math>"#;
    test_from_braille(
        "UEB",
        expr,
        "⠠⠨⠣⠼⠁⠀⠼⠃⠀⠼⠉⠠⠨⠜⠸⠀⠠⠨⠣⠼⠙⠀⠼⠑⠀⠼⠋⠠⠨⠜⠠⠨⠣⠼⠁⠀⠼⠃⠠⠨⠜⠸⠀⠠⠨⠣⠐⠤⠼⠉⠀⠼⠙⠠⠨⠜⠸⠀⠠⠨⠣⠼⠑⠀⠐⠤⠼⠋⠠⠨⠜",
    )?;
    Ok(())
}

#[test]
fn matrix_15_2_3() -> Result<()> {
    // Parallel to braille::UEB::iceb::matrix_15_2_3 ((a −b ; −c d)).
    let expr = r#"<math><mrow><mo>(</mo><mtable>
        <mtr><mtd><mi>a</mi></mtd><mtd><mrow><mo>-</mo><mi>b</mi></mrow></mtd></mtr>
        <mtr><mtd><mrow><mo>-</mo><mi>c</mi></mrow></mtd><mtd><mi>d</mi></mtd></mtr>
      </mtable><mo>)</mo></mrow></math>"#;
    test_from_braille("UEB", expr, "⠠⠐⠣⠁⠀⠐⠤⠃⠠⠐⠜⠸⠀⠠⠐⠣⠐⠤⠉⠀⠙⠠⠐⠜")?;
    Ok(())
}

#[test]
fn determinant_15_3_1() -> Result<()> {
    // Parallel to braille::UEB::iceb::determinant_15_3_1 (|P| = |a b; c d| = ad − bc).
    let expr = r#"<math>
      <mrow><mo>|</mo><mi>P</mi><mo>|</mo></mrow>
      <mo>=</mo>
      <mrow><mo>|</mo><mtable>
        <mtr><mtd><mi>a</mi></mtd><mtd><mi>b</mi></mtd></mtr>
        <mtr><mtd><mi>c</mi></mtd><mtd><mi>d</mi></mtd></mtr>
      </mtable><mo>|</mo></mrow>
      <mo>=</mo>
      <mrow><mi>a</mi><mi>d</mi><mo>-</mo><mi>b</mi><mi>c</mi></mrow>
    </math>"#;
    test_from_braille(
        "UEB",
        expr,
        "⠸⠳⠠⠏⠸⠳⠀⠐⠶⠀⠠⠸⠳⠁⠀⠃⠠⠸⠳⠸⠀⠠⠸⠳⠉⠀⠙⠠⠸⠳⠀⠐⠶⠀⠁⠙⠐⠤⠃⠉",
    )?;
    Ok(())
}

#[test]
fn omission_15_4_1() -> Result<()> {
    // Parallel to braille::UEB::iceb::omission_15_4_1 (determinant with omission dots).
    let expr = r#"<math><mrow><mo>|</mo><mtable>
      <mtr>
        <mtd><msub><mi>a</mi><mn>11</mn></msub></mtd>
        <mtd><msub><mi>a</mi><mn>12</mn></msub></mtd>
        <mtd><mo>⋯</mo></mtd>
        <mtd><msub><mi>a</mi><mrow><mn>1</mn><mi>n</mi></mrow></msub></mtd>
      </mtr>
      <mtr>
        <mtd><msub><mi>a</mi><mn>21</mn></msub></mtd>
        <mtd><msub><mi>a</mi><mn>22</mn></msub></mtd>
        <mtd><mo>⋯</mo></mtd>
        <mtd><msub><mi>a</mi><mrow><mn>2</mn><mi>n</mi></mrow></msub></mtd>
      </mtr>
      <mtr>
        <mtd><mo>.</mo></mtd>
        <mtd><mo>.</mo></mtd>
        <mtd><mo>⋯</mo></mtd>
        <mtd><mo>.</mo></mtd>
      </mtr>
      <mtr>
        <mtd><msub><mi>a</mi><mrow><mi>m</mi><mn>1</mn></mrow></msub></mtd>
        <mtd><msub><mi>a</mi><mrow><mi>m</mi><mn>2</mn></mrow></msub></mtd>
        <mtd><mo>⋯</mo></mtd>
        <mtd><msub><mi>a</mi><mrow><mi>m</mi><mi>n</mi></mrow></msub></mtd>
      </mtr>
    </mtable><mo>|</mo></mrow></math>"#;
    test_from_braille(
        "UEB",
        expr,
        "⠰⠰⠰⠠⠸⠳⠁⠢⠼⠁⠁⠀⠁⠢⠼⠁⠃⠀⠄⠄⠄⠀⠁⠢⠣⠼⠁⠝⠜⠠⠸⠳⠸⠀⠠⠸⠳⠁⠢⠼⠃⠁⠀⠁⠢⠼⠃⠃⠀⠄⠄⠄⠀⠁⠢⠣⠼⠃⠝⠜⠠⠸⠳⠸⠀⠠⠸⠳⠲⠀⠲⠀⠄⠄⠄⠀⠲⠠⠸⠳⠸⠀⠠⠸⠳⠁⠢⠣⠍⠼⠁⠜⠀⠁⠢⠣⠍⠼⠃⠜⠀⠄⠄⠄⠀⠁⠢⠣⠍⠝⠜⠠⠸⠳⠰⠄",
    )?;
    Ok(())
}

#[test]
fn chem_16_2_8() -> Result<()> {
    let expr = "<math><mi>Ca</mi><msub><mrow><mo>(</mo><mi>OH</mi><mo>)</mo></mrow><mn>2</mn></msub></math>";
    test_from_braille("UEB", expr, "⠰⠰⠠⠉⠁⠐⠣⠠⠕⠠⠓⠐⠜⠢⠼⠃")?;
    Ok(())
}

#[test]
fn chem_16_2_9() -> Result<()> {
    // Nested formula groups match reverse+canonicalize (not flat mhchem phantoms).
    let expr = "<math><mrow><mi>Cu</mi><mi>S</mi><msub><mi>O</mi><mn>4</mn></msub><mo>&#xB7;</mo><mn>5</mn><msub><mi>H</mi><mn>2</mn></msub><mi>O</mi></mrow></math>";
    test_from_braille("UEB", expr, "⠰⠰⠠⠉⠥⠠⠎⠠⠕⠢⠼⠙⠐⠲⠼⠑⠠⠓⠢⠼⠃⠠⠕")?;
    Ok(())
}

#[test]
fn chem_16_2_10() -> Result<()> {
    // Bare chem + recovers as msup (same braille as GTM msup_7_6_2).
    let expr = "<math><msup><mi mathvariant='normal'>H</mi><mo>+</mo></msup></math>";
    test_from_braille("UEB", expr, "⠠⠓⠰⠔⠐⠖")?;
    Ok(())
}

#[test]
fn chem_16_2_11() -> Result<()> {
    let expr = "<math> <mi mathvariant='normal'>S</mi> <mmultiscripts> <mi mathvariant='normal'>O</mi> <mn>4</mn> <mrow><mo>-</mo><mo>-</mo></mrow> </mmultiscripts> </math>";
    test_from_braille("UEB", expr, "⠠⠎⠠⠕⠰⠢⠼⠙⠔⠣⠐⠤⠐⠤⠜")?;
    Ok(())
}

#[test]
fn chem_16_2_12() -> Result<()> {
    // Golden = reverse MathML (mhchem phantoms/nesting not recoverable).
    let expr = "<math><mrow><mi>R</mi><mo>&#xB7;</mo><mi>C</mi><mi>H</mi><mrow><mo>(</mo><mrow><mi>O</mi><mi>H</mi></mrow><mo>)</mo></mrow><mo>&#xB7;</mo><mi>C</mi><msub><mi>H</mi><mn>2</mn></msub><mo>&#xB7;</mo><mi>C</mi><msub><mi>H</mi><mn>2</mn></msub><mo>&#xB7;</mo><mi>C</mi><msub><mi>O</mi><mn>2</mn></msub><mi>H</mi></mrow></math>";
    test_from_braille("UEB", expr, "⠰⠰⠠⠠⠠⠗⠐⠲⠉⠓⠐⠣⠕⠓⠐⠜⠐⠲⠉⠓⠢⠼⠃⠐⠲⠉⠓⠢⠼⠃⠐⠲⠉⠕⠢⠼⠃⠰⠓⠠⠄")?;
    Ok(())
}

#[test]
fn chem_16_2_13() -> Result<()> {
    // Cl₃ as msub is recoverable; forward packs it as mmultiscripts+none.
    let expr = "<math><mmultiscripts><mi>Fe</mi><none/><mi>III</mi></mmultiscripts><msub><mi>Cl</mi><mn>3</mn></msub></math>";
    test_from_braille("UEB", expr, "⠰⠰⠠⠋⠑⠔⠣⠠⠠⠊⠊⠊⠜⠠⠉⠇⠢⠼⠉")?;
    Ok(())
}

#[test]
fn chem_16_3_1() -> Result<()> {
    let expr = "<math><msubsup><mrow/><mn>92</mn><mn>238</mn></msubsup><mi>U</mi></math>";
    test_from_braille("UEB", expr, "⠰⠢⠼⠊⠃⠔⠼⠃⠉⠓⠠⠥")?;
    Ok(())
}

#[test]
fn chem_16_4_2() -> Result<()> {
    let expr = "<math><msup><mrow/><mn>1</mn></msup><msub><mi mathvariant=\"normal\">S</mi><mn>0</mn></msub></math>";
    test_from_braille("UEB", expr, "⠰⠔⠼⠁⠠⠎⠢⠼⠚")?;
    Ok(())
}

#[test]
fn chem_16_4_3() -> Result<()> {
    let expr = "<math xmlns=\"http://www.w3.org/1998/Math/MathML\" display=\"block\"> <mn>4</mn><msup><mi mathvariant=\"normal\">d</mi><mn>9</mn></msup> <mn>5</mn><msup><mi mathvariant=\"normal\">s</mi><mn>2</mn></msup> <mstyle scriptlevel=\"0\"><mspace width=\"0.278em\"/></mstyle> <msup><mrow/><mn>2</mn></msup> <msub><mi mathvariant=\"normal\">D</mi><mrow><mn>5</mn><mo>/</mo><mn>2</mn></mrow></msub> </math>";
    test_from_braille("UEB", expr, "⠼⠙⠰⠙⠔⠼⠊⠼⠑⠎⠔⠼⠃⠀⠰⠔⠼⠃⠠⠙⠢⠣⠼⠑⠸⠌⠼⠃⠜")?;
    Ok(())
}

#[test]
fn chem_16_5_1() -> Result<()> {
    // Golden = reverse MathML (mhchem phantoms/nesting not recoverable).
    let expr = "<math><mrow><mn>2</mn><mi>Na</mi><mi>O</mi><mi>H</mi><mo>+</mo><msub><mi>H</mi><mn>2</mn></msub><mi>S</mi><msub><mi>O</mi><mn>4</mn></msub><mo>&#x2192;</mo><msub><mi>Na</mi><mn>2</mn></msub><mi>S</mi><msub><mi>O</mi><mn>4</mn></msub><mo>+</mo><mn>2</mn><msub><mi>H</mi><mn>2</mn></msub><mi>O</mi></mrow></math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠼⠃⠠⠝⠁⠠⠕⠠⠓⠐⠖⠠⠓⠢⠼⠃⠠⠎⠠⠕⠢⠼⠙⠀⠳⠕⠀⠠⠝⠁⠢⠼⠃⠠⠎⠠⠕⠢⠼⠙⠐⠖⠼⠃⠠⠓⠢⠼⠃⠠⠕⠰⠄")?;
    Ok(())
}

#[test]
fn chem_16_5_2() -> Result<()> {
    // mtext "Haber process" not recoverable; reverse emits Haber + process identifiers.
    let expr = "<math><msub><mi>N</mi><mn>2</mn></msub><munderover><mo>&#x2192;</mo><mrow><mi>Haber</mi><mi>process</mi></mrow><msub><mi>H</mi><mn>2</mn></msub></munderover><mi>N</mi><msub><mi>H</mi><mn>3</mn></msub></math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠠⠝⠢⠼⠃⠀⠳⠕⠨⠢⠣⠠⠓⠁⠃⠑⠗⠀⠏⠗⠕⠉⠑⠎⠎⠜⠨⠔⠣⠠⠓⠢⠼⠃⠜⠀⠠⠝⠠⠓⠢⠼⠉⠰⠄")?;
    Ok(())
}

#[test]
fn chem_16_5_3() -> Result<()> {
    // Golden = reverse MathML (state fences / HI packaging differ from mhchem).
    let expr = "<math><mrow><msub><mi>H</mi><mn>2</mn></msub><mrow><mo>(</mo><mi>g</mi><mo>)</mo></mrow><mo>+</mo><msub><mi>I</mi><mn>2</mn></msub><mrow><mo>(</mo><mi>s</mi><mo>)</mo></mrow><mo>=</mo><mn>2</mn><mi>H</mi><mi>I</mi><mrow><mo>(</mo><mi>g</mi><mo>)</mo></mrow></mrow></math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠠⠓⠢⠼⠃⠀⠐⠣⠛⠐⠜⠐⠖⠠⠊⠢⠼⠃⠀⠐⠣⠎⠐⠜⠀⠐⠶⠀⠼⠃⠠⠓⠠⠊⠀⠐⠣⠛⠐⠜⠰⠄")?;
    Ok(())
}

#[test]
fn chem_16_5_4() -> Result<()> {
    // Golden = reverse MathML (mhchem/latex packaging not recoverable).
    let expr = "<math><mrow><mi>H</mi><mi>N</mi><mi>C</mi><mi>O</mi><mo>+</mo><mi>R</mi><mi>O</mi><mi>H</mi><mo>&#x2192;</mo><mi>N</mi><msub><mi>H</mi><mn>2</mn></msub><mo>&#xB7;</mo><mi>C</mi><mi>O</mi><mo>&#xB7;</mo><mi>OR</mi><mo>&#x2192;</mo><mi>N</mi><msub><mi>H</mi><mn>2</mn></msub><mi>C</mi><mi>O</mi><mo>&#xB7;</mo><mi>N</mi><mi>H</mi><mo>&#xB7;</mo><mi>C</mi><msub><mi>O</mi><mn>2</mn></msub><mi>R</mi></mrow></math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠠⠠⠠⠓⠝⠉⠕⠐⠖⠗⠕⠓⠀⠳⠕⠀⠝⠓⠢⠼⠃⠐⠲⠉⠕⠐⠲⠕⠗⠀⠳⠕⠀⠝⠓⠢⠼⠃⠰⠉⠕⠐⠲⠝⠓⠐⠲⠉⠕⠢⠼⠃⠗⠠⠄⠰⠄")?;
    Ok(())
}

#[test]
fn chem_16_5_5() -> Result<()> {
    // Forward equilibrium as stacked harpoons; reverse recovers ⇌.
    let expr = "<math><mmultiscripts><mi>Pb</mi><none/><mrow><mo>+</mo><mo>+</mo></mrow></mmultiscripts><mo>+</mo><mn>2</mn><mi>e</mi><mo>&#x21CC;</mo><mi>Pb</mi></math>";
    test_from_braille("UEB", expr, "⠰⠰⠰⠠⠏⠃⠔⠣⠐⠖⠐⠖⠜⠐⠖⠼⠃⠰⠑⠀⠘⠸⠶⠀⠠⠏⠃⠰⠄")?;
    Ok(())
}
