// @generated by notes/_gen_ueb_from_braille_tests.py from tests/braille/UEB/other.rs
// Do not edit by hand unless updating the generator.
#![allow(non_snake_case)]

use crate::common::*;
use anyhow::Result;

#[test]
fn overscript_grouping_aph_5_4_8() -> Result<()> {
    let expr = "<math> <mover> <mi>MN</mi> <mo>&#x2194;</mo> </mover> </math>";
    test_from_braille("UEB", expr, "⠰⠰⠣⠠⠠⠍⠝⠜⠨⠔⠳⠺⠗⠕")?;
    Ok(())
}

#[test]
fn word_symbol_aph_6_7_5() -> Result<()> {
    let expr = "<math><mn>4</mn><mo>+</mo><mn>5</mn><mo>≟</mo><mn>12</mn></math>";
    test_from_braille("UEB", expr, "⠼⠙⠐⠖⠼⠑⠀⠰⠰⠦⠻⠐⠶⠀⠼⠁⠃")?;
    Ok(())
}

#[test]
fn blank_aph_7_1_ex5() -> Result<()> {
    // Omission blank ⠨⠤ is recovered as <mi>_</mi> (same as ICEB 3.6.2).
    let expr = "<math><mn>3</mn><mo>:</mo><mn>15</mn><mo>::</mo><mn>60</mn><mo>:</mo><mi>_</mi></math>";
    test_from_braille("UEB", expr, "⠼⠉⠒⠼⠁⠑⠀⠒⠒⠀⠼⠋⠚⠒⠨⠤")?;
    Ok(())
}

#[test]
fn word_symbol_aph_10_3_11() -> Result<()> {
    let expr = "<math> <mi>p</mi> <mo>&#x22bb;</mo> <mi>q</mi> </math>";
    test_from_braille("UEB", expr, "⠰⠰⠏⠈⠖⠠⠱⠟")?;
    Ok(())
}

#[test]
fn number_space_before() -> Result<()> {
    let expr = "<math><mo>&#xA0;</mo><mn>2</mn></math>";
    test_from_braille("UEB", expr, "⠀⠼⠃")?;
    Ok(())
}

#[test]
fn number_space_after() -> Result<()> {
    let expr = "<math><mn>2</mn><mo>&#xA0;</mo></math>";
    test_from_braille("UEB", expr, "⠼⠃⠀")?;
    Ok(())
}

#[test]
fn number_space_before_and_after() -> Result<()> {
    let expr = "<math><mo>&#xA0;</mo><mn>2</mn><mo>&#xA0;</mo></math>";
    test_from_braille("UEB", expr, "⠀⠼⠃⠀")?;
    Ok(())
}

#[test]
fn not_number_space_blocks() -> Result<()> {
    // Braille space between digit groups recovers as nbsp (not forward's nbsp+U+2063).
    let expr = "<math><mn>123</mn><mo>&#xA0;</mo><mn>456</mn></math>";
    test_from_braille("UEB", expr, "⠼⠁⠃⠉⠀⠼⠙⠑⠋")?;
    Ok(())
}

#[test]
fn dot_above_bug_204() -> Result<()> {
    // Same braille as ˙; reverse prefers ˙ over middot.
    let expr = "<math><mn>0</mn><mo>.</mo><mover><mn>6</mn><mo>&#x2D9;</mo></mover></math>";
    test_from_braille("UEB", expr, "⠼⠚⠲⠣⠼⠋⠜⠘⠲")?;
    Ok(())
}

#[test]
fn tilde_prefix_bug_244() -> Result<()> {
    let expr = "<math> <mo>~</mo> <mi>p</mi> </math>";
    test_from_braille("UEB", expr, "⠈⠔⠏")?;
    Ok(())
}

#[test]
fn double_tilde_prefix_bug_244() -> Result<()> {
    let expr = "<math> <mo>~~</mo> <mi>p</mi> </math>";
    test_from_braille("UEB", expr, "⠈⠔⠈⠔⠏")?;
    Ok(())
}

#[test]
fn space_hack_between_digits() -> Result<()> {
    // Braille spaces between digits recover as nbsp (not forward's nbsp+U+2063).
    let expr = "<math><mn>1</mn><mo>&#xA0;</mo><mn>3</mn><mo>&#xA0;</mo><mn>5</mn></math>";
    test_from_braille("UEB", expr, "⠼⠁⠀⠼⠉⠀⠼⠑")?;
    Ok(())
}

#[test]
fn space_hack_around_operator() -> Result<()> {
    // Forward uses mtext nbsp+U+2063 around '='; braille space is absorbed as normal operator spacing.
    let expr = "<math><mi>y</mi><mo>=</mo><mn>5</mn></math>";
    test_from_braille("UEB", expr, "⠰⠽⠀⠐⠶⠀⠼⠑")?;
    Ok(())
}

#[test]
fn forced_g1_symbol_mode() -> Result<()> {
    let expr = "<math><mo>∫</mo><mn>3</mn><msup><mi>x</mi><mn>2</mn></msup><mi>dx</mi></math>";
    test_from_braille("UEB", expr, "⠰⠮⠼⠉⠭⠔⠼⠃⠰⠙⠭")?;
    Ok(())
}

#[test]
fn contractions_1() -> Result<()> {
    let expr = "<math> <mi>sech</mi><mo>&#x2061;</mo><mi>x</mi><mo>+</mo> <mi>cosh</mi><mo>&#x2061;</mo><mi>y</mi><mo>+</mo> <mi>arccos</mi><mo>&#x2061;</mo><mi>t</mi> </math>";
    test_from_braille("UEB", expr, "⠎⠑⠡⠀⠭⠐⠖⠉⠕⠩⠀⠽⠐⠖⠜⠉⠉⠕⠎⠀⠰⠞")?;
    Ok(())
}

#[test]
fn contractions_2() -> Result<()> {
    let expr = "<math><mi>ker</mi><mo>&#x2061;</mo><mi>h</mi></math>";
    test_from_braille("UEB", expr, "⠅⠻⠀⠰⠓")?;
    Ok(())
}

#[test]
fn contractions_3() -> Result<()> {
    // Forward shortens "argument" to braille that reverse reads as "argut".
    let expr = "<math><mi>argut</mi><mo>&#x2061;</mo><mo>(</mo><mi>f</mi><mo>)</mo></math>";
    test_from_braille("UEB", expr, "⠜⠛⠥⠰⠞⠐⠣⠋⠐⠜")?;
    Ok(())
}

#[test]
fn contractions_4() -> Result<()> {
    // Forward mtext + literary shortenings are not fully recoverable.
    let expr = "<math><mi>error</mi><mi>funcn</mi><mi>erf</mi></math>";
    test_from_braille("UEB", expr, "⠻⠗⠕⠗⠀⠋⠥⠝⠉⠰⠝⠀⠻⠋")?;
    Ok(())
}

#[test]
fn contractions_5() -> Result<()> {
    let expr = "<math><mi>Real</mi><mo>(</mo><mi>z</mi><mo>)</mo></math>";
    test_from_braille("UEB", expr, "⠠⠗⠂⠇⠐⠣⠵⠐⠜")?;
    Ok(())
}

#[test]
fn caps_bug_279() -> Result<()> {
    let expr = "<math><mfrac><mrow><mi>A</mi><mi>B</mi></mrow><mi>B</mi></mfrac></math>";
    test_from_braille("UEB", expr, "⠰⠰⠷⠠⠠⠁⠃⠨⠌⠠⠃⠾")?;
    Ok(())
}

#[test]
fn caps_bug_295() -> Result<()> {
    let expr = "<math><mi>P</mi><mo>⁢</mo><mi>Q</mi><mo>+</mo> <mi>Q</mi><mo>⁢</mo><mi>R</mi><mo>=</mo> <mi>R</mi><mo>⁢</mo><mi>S</mi><mo>+</mo> <mi>Q</mi><mo>⁢</mo><mi>R</mi></math>";
    test_from_braille("UEB", expr, "⠠⠠⠠⠏⠟⠐⠖⠟⠗⠀⠐⠶⠀⠗⠎⠐⠖⠟⠗⠠⠄")?;
    Ok(())
}

#[test]
fn unicode_superscript_chars_in_and_out_of_script_position() -> Result<()> {
    // Forward uses U+00B9; reverse recovers plain digit in msup (braille is script+number).
    let expr = "<math><msup><mi>x</mi><mn>1</mn></msup></math>";
    test_from_braille("UEB", expr, "⠭⠰⠔⠼⠁")?;
    Ok(())
}

#[test]
fn unicode_superscript_chars_in_and_out_of_script_position_2() -> Result<()> {
    // Same braille as _1; flat unicode superscript is not recoverable.
    let expr = "<math><msup><mi>x</mi><mn>1</mn></msup></math>";
    test_from_braille("UEB", expr, "⠭⠰⠔⠼⠁")?;
    Ok(())
}

#[test]
fn unicode_superscript_chars_in_and_out_of_script_position_3() -> Result<()> {
    // Forward uses U+207A; reverse recovers plain '+' in msup.
    let expr = "<math><msup><mi>x</mi><mo>+</mo></msup></math>";
    test_from_braille("UEB", expr, "⠭⠰⠔⠐⠖")?;
    Ok(())
}

#[test]
fn unicode_superscript_chars_in_and_out_of_script_position_4() -> Result<()> {
    let expr = "<math><msup><mi>x</mi><mo>+</mo></msup></math>";
    test_from_braille("UEB", expr, "⠭⠰⠔⠐⠖")?;
    Ok(())
}

#[test]
fn unicode_subscript_chars_in_and_out_of_script_position() -> Result<()> {
    // Forward uses U+2081; reverse recovers plain digit in msub.
    let expr = "<math><msub><mi>x</mi><mn>1</mn></msub></math>";
    test_from_braille("UEB", expr, "⠭⠰⠢⠼⠁")?;
    Ok(())
}

#[test]
fn unicode_subscript_chars_in_and_out_of_script_position_2() -> Result<()> {
    let expr = "<math><msub><mi>x</mi><mn>1</mn></msub></math>";
    test_from_braille("UEB", expr, "⠭⠰⠢⠼⠁")?;
    Ok(())
}

#[test]
fn unicode_subscript_chars_in_and_out_of_script_position_3() -> Result<()> {
    // Forward uses U+208A; reverse recovers plain '+' in msub.
    let expr = "<math><msub><mi>x</mi><mo>+</mo></msub></math>";
    test_from_braille("UEB", expr, "⠭⠰⠢⠐⠖")?;
    Ok(())
}

#[test]
fn unicode_subscript_chars_in_and_out_of_script_position_4() -> Result<()> {
    let expr = "<math><msub><mi>x</mi><mo>+</mo></msub></math>";
    test_from_braille("UEB", expr, "⠭⠰⠢⠐⠖")?;
    Ok(())
}

#[test]
fn multiple_lines() -> Result<()> {
    // Bare equation-line mtable: `⠸⠀` between rows, no start/end bounds.
    let expr = "<math><mtable><mtr><mtd><mi>x</mi></mtd><mtd><mrow><mo>=</mo><mi>f</mi><mo>(</mo><mi>t</mi><mo>)</mo></mrow></mtd></mtr><mtr><mtd><mi>y</mi></mtd><mtd><mrow><mo>=</mo><mi>g</mi><mo>(</mo><mi>t</mi><mo>)</mo></mrow></mtd></mtr></mtable></math>";
    test_from_braille(
        "UEB",
        expr,
        "⠰⠭⠀⠐⠶⠀⠋⠐⠣⠞⠐⠜⠸⠀⠰⠽⠀⠐⠶⠀⠛⠐⠣⠞⠐⠜",
    )?;
    Ok(())
}
