// @generated by notes/_gen_ueb_from_braille_tests.py from tests/braille/UEB/other.rs
// Do not edit by hand unless updating the generator.
#![allow(non_snake_case)]

use crate::common::*;
use anyhow::Result;

#[test]
fn overscript_grouping_aph_5_4_8() -> Result<()> {
    let expr = "<math> <mover> <mi>MN</mi> <mo>&#x2194;</mo> </mover> </math>";
    test_from_braille("UEB", expr, "⠰⠰⠣⠠⠠⠍⠝⠜⠨⠔⠳⠺⠗⠕")?;
    Ok(())
}

#[test]
fn word_symbol_aph_6_7_5() -> Result<()> {
    let expr = "<math><mn>4</mn><mo>+</mo><mn>5</mn><mo>≟</mo><mn>12</mn></math>";
    test_from_braille("UEB", expr, "⠼⠙⠐⠖⠼⠑⠀⠰⠰⠦⠻⠐⠶⠀⠼⠁⠃")?;
    Ok(())
}

#[test]
fn blank_aph_7_1_ex5() -> Result<()> {
    let expr = "<math><mn>3</mn><mo>:</mo><mn>15</mn> <mo>::</mo> <mn>60</mn><mo>:</mo><mo>_</mo></math>";
    test_from_braille("UEB", expr, "⠼⠉⠒⠼⠁⠑⠀⠒⠒⠀⠼⠋⠚⠒⠨⠤")?;
    Ok(())
}

#[test]
fn word_symbol_aph_10_3_11() -> Result<()> {
    let expr = "<math> <mi>p</mi> <mo>&#x22bb;</mo> <mi>q</mi> </math>";
    test_from_braille("UEB", expr, "⠰⠰⠏⠈⠖⠠⠱⠟")?;
    Ok(())
}

#[test]
fn number_space_before() -> Result<()> {
    let expr = "<math><mtext>&#xA0;</mtext><mn>2</mn></math>";
    test_from_braille("UEB", expr, "⠀⠼⠃")?;
    Ok(())
}

#[test]
fn number_space_after() -> Result<()> {
    let expr = "<math><mn>2</mn><mtext>&#xA0;</mtext></math>";
    test_from_braille("UEB", expr, "⠼⠃⠀")?;
    Ok(())
}

#[test]
fn number_space_before_and_after() -> Result<()> {
    let expr = "<math><mtext>&#xA0;</mtext><mn>2</mn><mtext>&#xA0;</mtext></math>";
    test_from_braille("UEB", expr, "⠀⠼⠃⠀")?;
    Ok(())
}

#[test]
fn not_number_space_blocks() -> Result<()> {
    let expr = "<math><mn>123</mn><mtext>&nbsp;&#x2063;</mtext><mn>456</mn></math>";
    test_from_braille("UEB", expr, "⠼⠁⠃⠉⠀⠼⠙⠑⠋")?;
    Ok(())
}

#[test]
fn dot_above_bug_204() -> Result<()> {
    let expr = "<math> <mn>0.</mn> <mover> <mn>6</mn> <mo>&middot;</mo> </mover> </math>";
    test_from_braille("UEB", expr, "⠼⠚⠲⠣⠼⠋⠜⠘⠲")?;
    Ok(())
}

#[test]
fn tilde_prefix_bug_244() -> Result<()> {
    let expr = "<math> <mo>~</mo> <mi>p</mi> </math>";
    test_from_braille("UEB", expr, "⠈⠔⠏")?;
    Ok(())
}

#[test]
fn double_tilde_prefix_bug_244() -> Result<()> {
    let expr = "<math> <mo>~~</mo> <mi>p</mi> </math>";
    test_from_braille("UEB", expr, "⠈⠔⠈⠔⠏")?;
    Ok(())
}

#[test]
fn space_hack_between_digits() -> Result<()> {
    let expr = "<math><mn>1</mn><mtext>&#x00a0;&#x2063;</mtext><mn>3</mn><mtext>&#x00a0;&#x2063;</mtext><mn>5</mn></math>";
    test_from_braille("UEB", expr, "⠼⠁⠀⠼⠉⠀⠼⠑")?;
    Ok(())
}

#[test]
fn space_hack_around_operator() -> Result<()> {
    let expr = "<math><mi>y</mi><mtext>&#x00a0;&#x2063;</mtext><mo>=</mo><mtext>&#x00a0;&#x2063;</mtext><mn>5</mn></math>";
    test_from_braille("UEB", expr, "⠰⠽⠀⠐⠶⠀⠼⠑")?;
    Ok(())
}

#[test]
fn forced_g1_symbol_mode() -> Result<()> {
    let expr = "<math><mo>∫</mo><mn>3</mn><msup><mi>x</mi><mn>2</mn></msup><mi>dx</mi></math>";
    test_from_braille("UEB", expr, "⠰⠮⠼⠉⠭⠔⠼⠃⠰⠙⠭")?;
    Ok(())
}

#[test]
fn contractions_1() -> Result<()> {
    let expr = "<math> <mi>sech</mi><mo>&#x2061;</mo><mi>x</mi><mo>+</mo> <mi>cosh</mi><mo>&#x2061;</mo><mi>y</mi><mo>+</mo> <mi>arccos</mi><mo>&#x2061;</mo><mi>t</mi> </math>";
    test_from_braille("UEB", expr, "⠎⠑⠡⠀⠭⠐⠖⠉⠕⠩⠀⠽⠐⠖⠜⠉⠉⠕⠎⠀⠰⠞")?;
    Ok(())
}

#[test]
fn contractions_2() -> Result<()> {
    let expr = "<math><mi>ker</mi><mo>&#x2061;</mo><mi>h</mi></math>";
    test_from_braille("UEB", expr, "⠅⠻⠀⠰⠓")?;
    Ok(())
}

#[test]
fn contractions_3() -> Result<()> {
    let expr = "<math><mi>argument</mi><mo>&#x2061;</mo><mo>(</mo><mi>f</mi><mo>)</mo></math>";
    test_from_braille("UEB", expr, "⠜⠛⠥⠰⠞⠐⠣⠋⠐⠜")?;
    Ok(())
}

#[test]
fn contractions_4() -> Result<()> {
    let expr = "<math><mtext>error&#xA0;function&#xA0;</mtext><mi>erf</mi></math>";
    test_from_braille("UEB", expr, "⠻⠗⠕⠗⠀⠋⠥⠝⠉⠰⠝⠀⠻⠋")?;
    Ok(())
}

#[test]
fn contractions_5() -> Result<()> {
    let expr = "<math><mi>Real</mi><mo>(</mo><mi>z</mi><mo>)</mo></math>";
    test_from_braille("UEB", expr, "⠠⠗⠂⠇⠐⠣⠵⠐⠜")?;
    Ok(())
}

#[test]
fn caps_bug_279() -> Result<()> {
    let expr = "<math><mfrac><mrow><mi>A</mi><mi>B</mi></mrow><mi>B</mi></mfrac></math>";
    test_from_braille("UEB", expr, "⠰⠰⠷⠠⠠⠁⠃⠨⠌⠠⠃⠾")?;
    Ok(())
}

#[test]
fn caps_bug_295() -> Result<()> {
    let expr = "<math><mi>P</mi><mo>⁢</mo><mi>Q</mi><mo>+</mo> <mi>Q</mi><mo>⁢</mo><mi>R</mi><mo>=</mo> <mi>R</mi><mo>⁢</mo><mi>S</mi><mo>+</mo> <mi>Q</mi><mo>⁢</mo><mi>R</mi></math>";
    test_from_braille("UEB", expr, "⠠⠠⠠⠏⠟⠐⠖⠟⠗⠀⠐⠶⠀⠗⠎⠐⠖⠟⠗⠠⠄")?;
    Ok(())
}

#[test]
fn unicode_superscript_chars_in_and_out_of_script_position() -> Result<()> {
    let expr = "<math><msup><mi>x</mi><mo>¹</mo></msup></math>";
    test_from_braille("UEB", expr, "⠭⠰⠔⠼⠁")?;
    Ok(())
}

#[test]
fn unicode_superscript_chars_in_and_out_of_script_position_2() -> Result<()> {
    let expr = "<math><mrow><mi>x</mi><mo>¹</mo></mrow></math>";
    test_from_braille("UEB", expr, "⠭⠰⠔⠼⠁")?;
    Ok(())
}

#[test]
fn unicode_superscript_chars_in_and_out_of_script_position_3() -> Result<()> {
    let expr = "<math><msup><mi>x</mi><mo>⁺</mo></msup></math>";
    test_from_braille("UEB", expr, "⠭⠰⠔⠐⠖")?;
    Ok(())
}

#[test]
fn unicode_superscript_chars_in_and_out_of_script_position_4() -> Result<()> {
    let expr = "<math><mrow><mi>x</mi><mo>⁺</mo></mrow></math>";
    test_from_braille("UEB", expr, "⠭⠰⠔⠐⠖")?;
    Ok(())
}

#[test]
fn unicode_subscript_chars_in_and_out_of_script_position() -> Result<()> {
    let expr = "<math><msub><mi>x</mi><mn>₁</mn></msub></math>";
    test_from_braille("UEB", expr, "⠭⠰⠢⠼⠁")?;
    Ok(())
}

#[test]
fn unicode_subscript_chars_in_and_out_of_script_position_2() -> Result<()> {
    let expr = "<math><mrow><mi>x</mi><mn>₁</mn></mrow></math>";
    test_from_braille("UEB", expr, "⠭⠰⠢⠼⠁")?;
    Ok(())
}

#[test]
fn unicode_subscript_chars_in_and_out_of_script_position_3() -> Result<()> {
    let expr = "<math><msub><mi>x</mi><mo>₊</mo></msub></math>";
    test_from_braille("UEB", expr, "⠭⠰⠢⠐⠖")?;
    Ok(())
}

#[test]
fn unicode_subscript_chars_in_and_out_of_script_position_4() -> Result<()> {
    let expr = "<math><mrow><mi>x</mi><mo>₊</mo></mrow></math>";
    test_from_braille("UEB", expr, "⠭⠰⠢⠐⠖")?;
    Ok(())
}
